Kitware/CDash

cdash/config.php, cdash/do_submit.php, cdash/processsubmissions.php, xml_handlers/GcovTar_handler.php, xml_handlers/build_handler.php, xml_handlers/testing_handler.php, xml_handlers/update_handler.php
1) Disable feed.  This takes a relatively long time during the
submission process.
2) Shorten up the backlog of finished submissions.  If this table
gets too many rows, it can take a relatively long time to find the
next submission to process.
=> New options to speedup submission processing.

xml_handlers/GcovTar_handler.php
More than one file can be included in a gcov tarball, and
target labels should apply to all of their source files.
=> Fix parsing of Labels.json files

cdash/sendemail.php, coverageRow.xsl, index.php, index.xsl, models/build.php, models/buildconfigure.php, models/buildtest.php, models/buildupdate.php, models/coveragefilelog.php, models/coveragesummary.php, models/project.php, overview.php, sql/mysql/cdash.sql, sql/pgsql/cdash.sql, upgrade.php, xml_handlers/configure_handler.php
This changes the way that subprojects are handled.
Before this commit, the number of build errors, test failures, etc.
was accumulated across related subproject builds every time index.php
was rendered.
Now this math is only done once at the time of submission.  This
simplifies the logic in index.php, allowing it to render more quickly
while using less memory.  Going forward, it should also allow us to
introduce new subproject features, such as viewing all build errors
across packages for a particular build.
=> Introduce the concept of parent builds

iphone/index.xsl, testDetails.xsl
see mail from mailinglist: http://public.kitware.com/pipermail/cdash/2015-January/001541.html
to sum:
clicking on previous in the top menu then clicking on "current" or "next" was causing an issue which prevents page loading. is that okay if we move jquery.mobile.js file into iphone folder since we do not use it for desktops?
If not, what would be the solution?
=> workaround for cdash mobile script issue

index.php
The previous check used a query that was not valid syntax for PostgreSQL.
=> update database version check

tests/prepend_coverage.php.in
Don't rely on PHPUNIT_SELENIUM_TEST_ID, which no longer seems to be getting set.  This fixes some PHP errors that we were experiencing during coverage builds.
=> Change how temporary coverage files are named

xml_handlers/GcovTar_handler.php
SplFileInfo::getExtension() requires PHP >= 5.3.6.
=> Workaround for older PHP versions without SplFileInfo::getExtension.

manageSubproject.php, models/subproject.php
When a subproject is removed, we should also remove any dependencies on it.  This fixes a bug that could cause manageSubproject.php to not render.
=> Delete subproject dependencies

viewBuildError.php
whitespace is significant inside <pre> tags.
=> fix minor formatting error

api/viewBuildError.php, viewBuildError.php
When an anonymous user attempts to view a build error for a private project, we now provide a link to the login form instead of showing an unhelpful blank page.
=> Link to login page when necessary

coverageRow.xsl, index.php, indexchildren.xsl, javascript/cdashTableSorter.js, subprojectGroupCoverage.xsl
Slightly different look for index.php when you are viewing the children of a single build.  No need to repeat build & site name on each row since it never changes.  Also move the name of the SubProject to the first column.
=> new view for subproject builds

index.php, javascript/controllers/manageBuildGroup.js
* on the manage page, use numerical (not alphabetical) order when sorting by position.
* fix sql error on index.php when limiting number of builds.
=> misc fixes

index.php
Don't show dynamic builds when the user has applied a filter to index.php
=> hide dynamic builds for filtered results

javascript/controllers/manageBuildGroup.js
Now they will actually be shown in position order.
=> fix sorting of BuildGroups on manage page

cdash/common.php, coverageRow.xsl, index.php, indexchildren.xsl, javascript/cdashTableSorter.js, subprojectGroupCoverage.xsl, viewCoverage.php
* For a build with 0 total LOC, report coverage as 100% rather than 0%.
* Use all three colors (red/yellow/green) for coverage summaries.  Previously red was not used.
* Fix sorting coverage by percentage for subproject builds.  This was previously using lexographical (rather than numerical) sort.
* Sort grouped coverage from lowest to highest percentage by default.
=> Fix various issues with how coverage data is displayed

index.php
We shouldn't show empty rows for expected builds when displaying
a single subproject result.
=> Don't include expected builds when parentid is set

javascript/cdashOauth2.js, login.xsl
Before this commit, if you used the "login with Google account"
link, it would strip any anchor tags off of the URL you were
attempting to access.  This commit fixes that issue.
=> restore stripped anchors upon Google login

cdash/repository.php, tests/test_github_PR_comment.php
Use LOG_TESTING instead of attempting to modify log
settings from within a test.
=> Get Github PR test passing more reliably

index.php
This commit fixes a bug that prevented index.php from rendering
properly when a subproject parameter was specified and coverage
data was present.
=> Fix bug related to subprojects & coverage

cdash/config.php, cdash/pdocore.php
The introduction of CDASH_MAX_QUERY_RETRIES caused a handful of tests
to fail.  Apparently we expect or tolerate some queries to fail.
As far as I could tell, there is no way to configure simpletest to
wait longer for a response, so for now we redefine the default
value of CDASH_MAX_QUERY_RETRIES to 1.
=> fix failing tests

filterdataFunctions.php
- The Sierra project makes heavy use of the 'Labels' field to differentiate tests between different teams and 'Build Type' to show grouping of different testing platforms, e.g., development, production, experimental.
- I added these two fields to the "Tests Query" function to allow filtering by these two fields.
- I tested these changes in the local Sierra repository with good success.
=> filterdataFunctions: Added fields to tests query

cdash/config.php, xml_handlers/project_handler.php
Some projects upload Project.xml files with variable content.
This can cause subprojects to be deleted & recreated over and
over.  To avoid this, you can now set CDASH_DELETE_OLD_SUBPROJECTS
to false in your config file.
=> making deletion of old subprojects optional

.editorconfig, api/v1/build.php, api/v1/index.php, javascript/controllers/index.js
This branch fixes a bug where BuildGroups would sometimes not appear in the correct order.  This occurred when one or more of the BuildGroups were pruned for not containing any builds.
=> Always honor BuildGroup order as specified by project admins

.editorconfig, api/v1/viewSubProjects.php, cdash/common.php, views/index.html, views/manageBuildGroup.html, views/manageSubProject.html, views/viewBuildError.html, views/viewNotes.html, views/viewSubProjects.html, views/viewTest.html
If you create a header.html or footer.html in local/views that version will be used instead of the default one that ships with CDash.
=> Enable local overrides for header & footer on AngularJS pages

views/index.html, views/manageBuildGroup.html, views/manageSubProject.html, views/viewBuildError.html, views/viewNotes.html, views/viewSubProjects.html, views/viewTest.html
Our move to support local overrides for the header & footer
inadvertently broke the spinner that's displayed while CDash
loads data.
=> restore spinner functionality

cdash/common.php
We encountered a problem where manageProjectRoles.php would not load properly.  The PHP error log had the following clue:
`Warning:  DOMDocument::loadXML(): Input is not proper UTF-8, indicate encoding !`
I eventually tracked this down to a user with an í in their name.
=> Fix XML encoding error

javascript/controllers/viewSubProjects.js, views/partials/subProjectTable.html
Note: The 'Projects' table on the viewSubProjects page will only contain
one project so does not need to be sorted.
PTAL @zackgalbreath
=> Sort subprojects by multiple columns

cdash/common.php
A bug in our new JSON sanitization method was erroneously casting floats to int.
=> Fix sorting by floating point values

composer.json, package.json, recoverPassword.php
The original implementation of recoverPassword.php uses a timestamp for
seeding the random number generator (via srand). If two people reset
their passwords at the exact same time, their passwords will be
identical. An attacker who resets their password and another users at
almost the same time can determine the approx. int value used as the
seed and then generate a list of possible passwords, iterating through
the seed values. This creates a password list that can be used to
brute-force a victims password.
This attack was tested against CDash and was found to be effective.
If you're happy with this approach, we can replace other uses of
insecure random number generators in the codebase in a similar way.
References:
http://www.openwall.com/php_mt_seed/ …
=> Update recoverPassword.php to use a secure random number generator.

javascript/cdash_angular.js, views/partials/subProjectTable.html
Move any SubProjects that are missing data to the bottom
of the table.  This behavior was inadvertently lost when
we enabled sorting by multiple columns.
=> restore SubProject filtering

api/v1/index.php
CDash should only add an 'expected' build row if that build has not yet submitted today.
=> Fix bug where expected builds would appear twice

api/v1/viewTest.php, javascript/controllers/viewTest.js, views/viewTest.html
The 'History' and 'Summary' columns on viewTest.php can be expensive to compute.  When a build has more than 25 tests, we now use AJAX calls to compute this info as tests are revealed to the user.
=> Speedup test history

install.php
We previously had an implicit assumption that a database would
exist that shares its name with our db user.  Instead, attempt to
connect to the CDash PostgreSQL database, since it is not created
for you during the install step anyway.
=> Make PostgreSQL install more robust

tests/ctest/coveragedriver.ctest.in, tests/ctest/ctestdriver.ctest.in, tests/js/e2e_tests/manageBuildGroup.js
Call `ctest_empty_binary_directory` from our CTest driver scripts.  These scripts are used internally during some of CDash's automated tests.
=> clean CTest binary dir

include/filterdataFunctions.php, models/build.php, public/api/v1/index.php, tests/test_subprojectnextprevious.php
When viewing the children of a parent build, the link at the top of the page should take you to the previous parent build for that configuration.  Before this change, the link would simply take you to the build results for the previous day.  Similar behavior is expected for the next and current buttons.
=> Update previous/current/next links to honor parentid

public/api/v1/index.php
We recently added a new filter called 'subprojects' to index.php.
This allows you to blacklist or whitelist what subprojects will
be included in the tally of build errors & such on this page.
This commit causes these filters to be preserved when you delve
down into the child build view.  So if you excluded a subproject
at the parent view, it also will not appear after you click
on a child build.
=> Pass subproject filters along to the child view

public/js/controllers/index.js, public/js/controllers/viewSubProjects.js, public/views/partials/subProjectTable.html
Previously, the sorting on the 'Subproject Dependencies' table
(e.g. index.php?subproject...) was broken.
PTAL @zackgalbreath
=> Fixed 'Subproject Dependencies' multicolumn sorting

tests/test_excludesubprojects.php
Replace '$this->pass(...)' with '$this->fail(...)'.
PTAL @zackgalbreath
=> Fixed type in excludessubprojectstest

public/api/v1/index.php
This information is redundant since the results will be generated
based on the parentid paramater.
=> Don't include date in child build hyperlink

tests/kwtest/simpletest/browser.php
CircleCI was using SimpleTidyPageBuilder instead, which caused
compressedtest to fail there.
=> Always use SimplePHPPageBuilder for SimpleTest

public/googleauth_callback.php
We need to include config.php before any other files because it
sets up our include path.
=> Fix Google authentication

config/config.php, public/ajax/processsubmissions.php
We now delete completed submissions from the submission table
as soon as they are processed when CDASH_ASYNC_EXPIRATION_TIME
is set to 0.
=> Add option to instantly delete parsed submissions

config/config.php, include/ctestparser.php
We now delete XML files as soon as they are parsed if
CDASH_BACKUP_TIMEFRAME is set to '0'.
=> Add option to instantly delete parsed XML files

circle.yml
For some reason their version of gcc and gcov no longer match.  This is causing two of our tests (simple and simple_async) to fail.
=> Fix failing CircleCI test

public/api/v1/index.php, tests/test_subprojectnextprevious.php
Most of the time we only display how many labels a build has, not what
they actually are.
=> Simplify how labels are handled by index.php

public/api/v1/getuserid.php, public/recoverPassword.php, tests/test_api.php
Fix a couple locations that made it possible to determine whether or not an email address was a valid CDash account.
=> Prevent user discovery

public/api/v1/index.php
PostgreSQL and MySQL differ in how they handle the GROUP BY
clause.
=> Fix main query for Postgres

include/common.php
Check that this function exists before calling it.  We use it
to make sure that our JSON data is UTF-8 encoded.
It is part of the mbstring module, which is not necessarily
loaded depending on the content of your php.ini file.
=> Check that mb_detect_encoding exists

include/common.php, include/login_functions.php, public/manageProjectRoles.php, public/register.php
Partial fix for #160, but sufficient enough to close the issue. Essentially the same fix I committed late last year, but in other areas of the codebase.
=> Fix insecure random number generator use

config/config.php, include/login_functions.php, public/editUser.php, public/install.php, public/register.php, tests/CMakeLists.txt, tests/test_passwordcomplexity.php
This allows CDash instance administrators to dictate how complex its users passwords must be.
=> New config option to enforce password complexity

include/CDash/Database.php
=> Allow SSL CA to be set independently of key and certificate

public/upgrade.php
Only call ```UpgradeConfigureDuration``` and ```UpgradeTestDuration``` when necessary.
=> Don't rerun upgrade functions

include/pdocore.php
Return zero if we have a non-numeric value after escaping.
=> Make sure pdo_real_escape_numeric returns a number

public/api/v1/index.php, public/api/v1/queryTests.php, public/api/v1/viewTest.php
Add a call to the htmlentities function in the API where
'filterstring' is pulled from the webpage to prevent XSS.
=> Add htmlentities to API usage of filterstring

public/login.php
srand() returns nothing, so the value of $stamp was actually static.
Perhaps rand() was meant instead of srand()?
=> Incorrect use of srand()

include/submission_functions.php
When CDash is configured to not keep completed submissions,
we also need to delete the corresponding record from submission2ip
Otherwise we will eventually encounter DUPLICATE KEY errors
in the MySQL log.
=> delete completed submission2ip rows

include/common.php, include/ctestparser.php
Improve support for the ```$CDASH_BACKUP_TIMEFRAME === '0'``` case.
This PR also disables the inadvertent _turbo mode_ we noticed where unprocessed files were getting deleted at the beginning of the next testing day.
=> Immediate deletion of parsed submissions

include/login_functions.php
'rememberme' is a checkbox, so the test for whether or not it's checked
should be a simple isset. We were running pdo_real_escape_numeric on the
value (which was "on") so $rememberme was always set to 0. It's only
ever used as a boolean so it was always evaluating to false.
This can be tested by logging into a CDash instance (checking the remember me box) and seeing if a CDash-servername cookie exists.
=> Remove escaping of remember me checkbox input

include/createRSS.php, models/buildgroup.php, public/googleauth_callback.php, xml_handlers/GcovTar_handler.php
It seems like some log entries were always being recorded as LOG_INFO
because certain invocations of add_log thought the second argument is
the log level, when it's actually the third argument.
=> Fix improper usage of add_log

include/index_functions.php, public/api/v1/index.php, public/mobile/old_index.php
These groups now show you the most recent build that occurred on
or before the day that you're currently viewing.  Previously they
showed you the newest build no matter what date you specified.
Thus it was impossible to see any result but the most recent.
=> Improve behavior of Latest buildgroups

models/coveragefilelog.php, tests/test_branchcoverage.php, xml_handlers/GcovTar_handler.php, xml_handlers/JSCoverTar_handler.php, xml_handlers/JavaJSONTar_handler.php, xml_handlers/coverage_log_handler.php
Fix some issues as we move towards a real world deployment of aggregate coverage:
* Make sure we end up with the exact same source file no matter how it was submitted.
* More carefully handle the difference between a line of code that's uncoverable vs one that's merely uncovered.
=> Improve coverage aggregate

include/ctestparser.php, xml_handlers/GcovTar_handler.php, xml_handlers/JSCoverTar_handler.php, xml_handlers/JavaJSONTar_handler.php
This begins the long road to abstracting the filesystem by dealing with part that cannot be abstracted due to the way the phar extension works.
=> Use system temp directory when extracting coverage files

tests/test_sequenceindependence.php, xml_handlers/upload_handler.php
This commit fixes a bug where the Upload Handler would set the
build's start time equal to the build stamp.  For nightly builds,
this is the nightly start time set for this project.
The result was builds that looked as if they started at 1am in
the morning, no matter when they actually began.
=> Bug fix: don't set start time to build stamp

include/common.php
On my development environment I noticed certain pages (notably register) redirect to HTTPS even if `$CDASH_USE_HTTPS` is false. This should take that setting into account.
=> Only redirect to HTTPS if configuration allows

public/ajax/getviewcoverage.php, public/viewCoverage.php
We have two different methods for computing how well a file is
covered.  The gcov metric looks at how many lines were covered,
and the bullseye metric is based on how many branches and functions
were covered.
When these were first introduced in CDash we had no way of
handling branch coverage from gcov.  Now we do.  Thus we need
to update our criteria for determining which metric to use.
Now we only use the bullseye metric when no line coverage is
present, but we have some information about branch and/or function
level coverage.
=> Don't use the bullseye metric for line coverage

models/build.php
Previously, the value of 'timestatus' was checked before it was set. This
caused the current test time to be compared to a moving target and made
it unlikely that the test time status would fail.
=> Update test time status check

models/buildtest.php, public/api/v1/viewTest.php, public/js/controllers/viewTest.js, public/views/partials/parentbuild.html, public/views/viewTest.html, tests/data/BuildDetails/Insight_Experimental_Test_Subbuild.xml, tests/test_builddetails.php
This adds support for parent build ids in the viewTest.php endpoint. "etests" are currently unsupported for parent builds but continue to function as they did before for others.
=> Add aggregate view of tests

xml_handlers/upload_handler.php
As previously noted in f9a2d55, Upload.xml does not indicate
when it was created.  So we have to generate safe values
for start time and end time that fall within the correct testing
day.
This commit fixes a bug that caused builds to be associated with
the prior testing day.  This occurred when the project had a
nightly start time after noon (server time).
=> Fix bug in upload_handler's setting of start time

public/api/v1/index.php, tests/test_excludesubprojects.php
This commit fixes a bug that occurred when using the include
or exclude SubProjects filter.  An incorrect label was being
displayed when only one SubProject survived filtration.
=> Display the right label when filtering SubProjects

public/api/v1/index.php, public/js/controllers/index.js, public/views/index.html, public/views/partials/build.html, public/views/partials/buildNameElements.html, public/views/partials/footer.html, tests/js/e2e_tests/done_build.js, tests/js/e2e_tests/expected_build.js, tests/js/e2e_tests/filterLabels.js, tests/js/e2e_tests/remove_build.js, tests/js/e2e_tests/subprojectGroupOrder.js
Improve render speed of index.php by reducing the number of watchers that Angular generates.  This is done through the use of one-time binding.
=> Fewer watchers

models/build.php, xml_handlers/GcovTar_handler.php, xml_handlers/JavaJSONTar_handler.php, xml_handlers/update_handler.php
Make $ParentId a private member and add logic to SetParentId
that prevents a build from being its own parent.
=> Don't let a build be its own parent

public/views/partials/buildError.html
When introducing 635e4268c08831031c47a617ce9b895b00d99854, I moved buildError html into a partial and lost the style attribute that was on the table tag - this resulted in funky scroll output noticed here: https://open.cdash.org/viewBuildError.php?buildid=4332313.
Thanks @mathstuf for noticing.
=> Add back styling that was removed in aggregate view branch

include/common.php, models/build.php, models/coveragefilelog.php, tests/test_buildgetdate.php, xml_handlers/GcovTar_handler.php
To assign aggregate coverage to the correct build we need to know
the beginning and end of the current testing day, as well as
the siteid of 'CDash Server'.
These values are not specific to the covered source file.
So rather than looking them up in CoverageFileLog::UpdateAggregate(),
we now find them in GcovTar_Handler instead.  This means that we are
only finding this data once per tarball instead of finding it for each
.gcov file.
=> Speedup coverage aggregation for GcovTar_handler

include/pdocore.php, models/build.php
Update pdo_error() to make logging of the error optional.
During parallel submission processing we sometimes anticipate
an SQL error (due to a race condition) and handle it internally.
In these cases we should not write the error to the CDash log.
=> Make logging optional from pdo_error

include/copy_build_data.php
CDash checks for duplicates before asking the client to upload
a tarball of coverage data.  When a duplicate is detected it
skips the upload and copies the existing coverage info into this
new build.
As part of this process, we were also copying the difference in
coverage from the previous build.  This was wrong.  We now call
CoverageSummary::ComputeDifference() after the copy is done.
=> Don't copy CoverageSummaryDiff

public/views/index.html
This broke CDash's ability to display the login form on index.php.
Instead it would just display an empty version of the index page.
=> Don't use one-time binding for requirelogin

public/api/v1/index.php, public/views/index.html, tests/js/e2e_tests/filterLabels.js
This new approach handles the case of parent builds that only
contain coverage info (no configure/build/test data).
=> More robustly report number of child builds

include/common.php, models/build.php, models/coveragefilelog.php, models/coveragesummary.php, tests/data/CoverageAcrossSubProjects/MyExperimentalFeature/Build.xml, tests/data/CoverageAcrossSubProjects/MyProductionCode/Build.xml, tests/data/CoverageAcrossSubProjects/MyThirdPartyDependency/Build.xml, tests/test_crosssubprojectcoverage.php, xml_handlers/GcovTar_handler.php
Our recent additions of cross-subproject & aggregate coverage have slowed this parser down when lots of .gcov files are submitted.  This PR speeds things back up considerably.
=> Speed up GcovTar parsing

public/api/v1/overview.php
Check that $subprojectgroupid is not null before using it as an index into an array.
=> Avoid potential PHP error in overview.php

include/common.php, models/coveragefilelog.php
Unknown column 'subproject2build.subprojectid' in 'where clause'
=> Prevent SQL error

models/coveragefile.php, models/image.php, models/project.php, models/test.php, public/createProject.php, public/displayImage.php, tests/test_image.php
``pg_escape_bytea()`` is the only function that we use from the PHP pgsql module (as opposed to PDO_PGSQL).
CircleCI doesn't provide pgsql.so, so by eliminating our use of this function we will be able to start automatically testing CDash with PostgreSQL on CircleCI.
=> Use prepared statements instead of pg_escape_bytea

public/ajax/getviewcoverage.php
This commit fixes a bug that occurred when coverage was split
across two or more similarly named directories.
Suppose you have coverage for the following files:
app/foo.cxx
apptest/bar.cxx
While viewing the results from the app/ directory, you would also
see a file named "est/bar.cxx".
We now search for a trailing / to make sure we are only grabbing
files from the specified directory.
=> More carefully split coverage by directory

include/common.php
If any of these characters were present in our user-submitted data they would prevent our XSLT-generated pages from rendering properly.
=> Remove characters that are not valid XML

public/js/controllers/queryTests.js, public/js/controllers/viewTest.js, public/views/queryTests.html, public/views/viewTest.html
Remember what value the user specified for Items Per Page
on viewTest.php and queryTests.php.  Previously this would
default back to 25 whenever the page was revisited.
=> Remember Items Per Page setting

.gitignore, gulpfile.js, package.json
This commit splits our Javascript files into two categories:
1st party and 3rd party.  Each bundle is only rebuilt if something
changed within them.
This speeds up our gulp execution time in the case where no 3rd
party code has been modified.  Previously running gulp after changing
a CDash Javascript file took ~90 seconds.  With this change, it now
takes ~3 seconds.
=> Introduce gulp incremental builds

include/filterdataFunctions.php
TIMESTAMPDIFF() is a MySQL-specific function.
=> Fix duration filters for Postgres

Vagrantfile, ansible/requirements.yml
I ran into an issue with the PHP role changed and the provisioned instance no longer passed the test suite.
I pinned the major roles to versions, and setup a nightly build on my machine to ensure that tests pass on a vagrant machine (trusty64) provisioned with Ansible.
=> Pin important Ansible galaxy roles

public/api/v1/index.php
The configure column was not always being displayed when it should be.
This logic has been updated to more closely match how we handle the
conditional display of the Test column.
=> Fix disappearing configure column

include/common.php, include/filterdataFunctions.php, tests/CMakeLists.txt, tests/test_indexfilters.php, tests/test_seconds_from_interval.php
Instead of having to input a number of seconds (or minutes, in some cases...) you can now input a time duration as CDash reports it, eg ``17m 48s``.
=> Improve usability of duration filters

models/builderror.php, public/js/controllers/viewBuildError.js, tests/js/e2e_tests/viewBuildError.js
@jcfr fixes #332
The API was returning the correct data for both views, however Angular only marked the embedded html as "trusted" for the individual build errors (not the subproject build errors).
=> Trust HTML for build errors in subproject view

config/config.php, include/login_functions.php, sql/mysql/cdash-upgrade-2.0-2.4.sql, sql/mysql/cdash.sql, sql/pgsql/cdash-upgrade-2.0-2.4.sql, sql/pgsql/cdash.sql, tests/CMakeLists.txt, tests/test_accountlockout.php
New optional feature to lock a user account for *X* minutes after *Y* failed authentication attempts.
=> New feature: account lockout

public/views/index.html, tests/js/e2e_tests/sort_index.js
Distinguish the column on the far right of index.php (which shows
when the build started) from the advanced 'Time' column under the
'Build' heading (which shows how long the build took to complete).
=> Rename Build Time column to Start Time

include/index_functions.php, models/coveragefilelog.php, models/coveragesummary.php, models/coveragesummarydiff.php, public/api/v1/index.php, xml_handlers/GcovTar_handler.php
1) We were failing to display coverage for builds that reported 0 covered lines of code.
2) The difference in coverage from one build to the next could be inaccurately reported by the GcovTar handler.
3) The difference in aggregate coverage from one day to the next was not being calculated for SubProject builds.
=> Fix some bugs with our coverage summary reporting

config/config.php, include/CDash/Database.php, include/pdocore.php
This is the recommended method of operation when connecting to a Cloud SQL database from a GAE application.
=> Support connecting via unix_socket in PDO

include/filterdataFunctions.php, public/js/controllers/filters.js
The term 'Build Time' was ambiguous.  Did it refer to when the
build occurred, or how long it took?
We opt for 'Build Start Time' rather than the less verbose 'Start Time'
because this filter is available on both index.php (which displays builds)
and queryTests.php (which displays tests).
=> Rename 'Build Time' filter to 'Build Start Time'

include/filterdataFunctions.php, tests/test_excludesubprojects.php, tests/test_indexfilters.php
We recently redefined Build Time to be just the time spent during
the build step, rather than how long the entire build took
(including update/configure/test/etc).
Because of this change, we also need to modify the Build Duration filter
so that it finds builds based on their build step duration rather than
their total duration.
=> Fix behavior of Build Duration filter

ansible/site.yml
This gets the nightly builds for the Vagrant setup running again (missed a night).
=> Add php5-memcache as a system dependency for Ansible

public/api/v1/viewBuildError.php, public/views/partials/header.html, tests/test_subprojectnextprevious.php
While performing manual testing I found a couple scenarios where these links would discard parameters from the query string.
=> Fix a couple minor bugs with Previous/Next/Current links

ansible/site.yml, circle.yml, composer.json, composer.lock, config/config.php, include/memcache_functions.php, public/api/v1/overview.php, public/googleauth_callback.php
Unfortunately, it turns out that [AWS ElastiCache Node Auto Discovery](http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/AutoDiscovery.html) only works with the [memcached](http://php.net/manual/en/book.memcached.php) extension. ~~Now, either of the two memcache(d) extensions may be used and are optional.~~ Now, the memcached extension is used instead of the memcache extension and is optional.
PTAL @danlamanna.
=> Add support for ext-memcached and make optional

config/config.php, include/do_submit.php
@zackgalbreath I've set this up so we can manage the triggering of dailyupdates via a cron job, and skip the processing on each submission.
=> Allow daily updates to be disabled for submissions

models/build.php
The test of this feature was failing periodically.  I tracked
this down to database deadlocks occurring within UpdateBuildDuration().
Removing the transaction from this function seems to have fixed
the problem.  This transaction was unnecessary since the UPDATEs
performed here are atomic.
=> Make parallel submissions more robust

public/header.xsl
The parameters that userStatistics.php accepts changed recently.
Update the links from old-style (XSLT) pages accordingly.
=> Update link to userStatistics.php for XSLT pages

include/repository.php
Don't attempt to calculate the difference between two revisions without a current revision.
=> Check for current revision for version-only diff

public/ajax/showbuildgraph.php, public/buildSummary.xsl, public/js/cdashBuildGraph.js
Previously, the axis for errors, warnings and build failures was labeled
as 'minutes' even though it should have been dimensionless. Also, the scales for
the different graph types could be very different.
=> Split build graph into 4 separate graphs

tests/CMakeLists.txt, tests/data/TruncateOutput/Build.xml, tests/test_truncateoutput.php, xml_handlers/build_handler.php
When truncating long output preserve the beginning and the end of
the message, truncating the middle.  These portions are more likely
to hold useful information for our users.
=> Remove the middle when truncating long output

include/filterdataFunctions.php, tests/test_excludesubprojects.php
`build_survives_filter` is used to reevaluate our filters (build duration, test failures, etc) when we are including or excluding SubProject(s).
Within this function we need to convert interval strings ('10m 45s') to a number of seconds (645).  This number of seconds is then used to check whether or not a build should be filtered out.
As part of this commit we also strengthen the ExcludeSubProjects test to verify that this bug stays fixed.
=> Use get_seconds_from_interval for SubProject filters

include/ctestparser.php
This fixes the issue where backups were created for the duration of processing even when `CDASH_BACKUP_TIMEFRAME` was '0'.
=> Disable intermediate backup file creation when backups are disabled

public/register.php, tests/test_login.php
@zackgalbreath and I noticed this bug since GAE is running a revision closer to master.
It seems like the verification process has been confirming users without properly setting their passwords for a few months now. I'm assuming the reason we didn't catch this earlier is a combination of:
1) Production boxes being on older, stabler versions
2) Our tests didn't actually test the verification step of user registration
The latter being resolved in this PR.
=> Fix user registration

include/common.php, tests/test_removebuilds.php
For installations with lots of data `remove_build` can take a long time to run.  One bottleneck I identified was JOINing the `build2test` to itself, as this table can be very large.  Instead, we now perform multiple related queries to find tests that can be safely deleted.
Before making this change, I created a more robust test of remove_build.  This new test case verifies that all the correct data is successfully deleted, while shared resources are left intact when appropriate.
=> Improve performance of remove_build

include/filterdataFunctions.php, public/api/v1/compareCoverage.php, public/api/v1/index.php, public/js/controllers/compareCoverage.js, public/views/compareCoverage.html, public/views/index.html, tests/js/e2e_tests/subprojectGroupOrder.js, tests/test_aggregatesubprojectcoverage.php, tests/test_crosssubprojectcoverage.php
Make it easier for CDash users to view coverage results for the set of SubProjects that they care about.
1) Add a **Total** row to group-by-group coverage results on index.php and compareCoverage.php.
2) Add a **SubProject** filter to compareCoverage.php.
=> Make it easier to filter SubProject coverage results

composer.json, composer.lock
See https://github.com/ramsey/uuid/issues/80 for details.
@mgrauer @zackgalbreath 
Will leave this WIP until I verify it's fixed the issue.
This was responsible for the "Checksum failure on file.." issue, the submission process was creating multiple jobs (with different files/checksums) underneath the same submission uuid.
=> Use newer version of random_compat to avoid UUID collisions

public/views/partials/buildError.html
For references to source files in the pre and post context fields, show the user an actual link as opposed to the literal text `<a href='...>`
=> Fix builderror links from precontext and postcontext

public/js/controllers/filters.js
When constructing a filter URL, the order of the existing query string parameters no longer matters.
Our previous approach removed any parameters that occurred before `filtercount`.  This could remove values that should be preserved such as `project` or `date` if they occurred towards the end of the query string.
=> Ignore query string parameter order in createHyperlink()

gulpfile.js, package.json, public/js/controllers/index.js, public/js/controllers/viewBuildError.js, public/js/directives/daterange.js, public/views/buildSummary.html, public/views/compareCoverage.html, public/views/createProject.html, public/views/index.html, public/views/manageBuildGroup.html, public/views/manageOverview.html, public/views/manageSubProject.html, public/views/overview.html, public/views/queryTests.html, public/views/testDetails.html, public/views/testOverview.html, public/views/testSummary.html, public/views/userStatistics.html, public/views/viewBuildError.html, public/views/viewNotes.html, public/views/viewProjects.html, public/views/viewSubProjects.html, public/views/viewTest.html
A while back we implemented cache busting for CDash's javascript code.  The idea behind cache busting is that users shouldn't have to delete their cache when we make changes to the site.
One part of CDash that's still being cached is our "partials": chunks of HTML code that can be shared among views.  This PR implements cache busting for these partials.
=> Cache busting for partials

config/config.php
PHP now throws a warning if you do not set a default timezone.
=> Set default timezone to UTC

public/api/v1/createProject.php, public/header.xsl, public/headeradminproject.xsl, public/manageClient.xsl, public/subscribeProject.xsl, public/user.xsl, public/views/partials/header.html, tests/CMakeLists.txt, tests/test_createprojectpermissions.php
Project administrators were not allowed to edit their project.  This PR fixes this bug and adds a new test of permissions on `createProject.php`.
This PR also removes the `edit` parameter from createProject.php.  We can tell whether we're creating a new project or editing an existing one based on the presence of the `projectid` parameter.
=> Fix createProject.php permissions bug

models/dynamicanalysis.php
Only store 1MB of log file, since that's all we display to users.
=> Truncate dynamic analysis log

include/ctestparserutils.php
The function extract_date_from_buildstamp() did not properly handle the case
where the build's group name contained a '-'.  This caused the build to appear
as if it started at the beginning of the UNIX epoch (1980).
=> Fix build starttime bug for upload handler

include/common.php, tests/CMakeLists.txt, tests/test_extracttar.php
Before the errors from extract_tar using Archive_Tar were just being output via print, now we can catch them and log them to the CDash logging system.
=> Allow tar extraction errors to be logged

config/config.php, include/pdocore.php
Placing the block in `pdo_error` doesn't cover all cases (I don't think), but at least this is a step in the right direction.
The logic for this is to deal with environments (namely GAE) where a request needs to return a non 2xx exit status to be considered a failure. This also deals with shortcomings of CDash where certain functions succeed when database queries fail.
=> Force an exit on critical PDO errors

include/filterdataFunctions.php, tests/CMakeLists.txt, tests/test_revisionfilteracrossdates.php
When the revision filter is specified, return any matching builds
regardless of when they occurred.
=> Consider the revision filter as a date clause

models/project.php, models/subproject.php, public/api/v1/viewSubProjects.php
Improve the queries used to tally the total number of builds with errors,
warnings, etc. in the project and subproject models.  This improves the
rendering speed of user.php and viewSubProjects.php for projects that
contain subprojects.
* In the project model, when counting builds, only consider parent or standalone
builds (not children).
* Encapsulate common query structure in subproject model.
* Remove unnecessary echoes from subproject model.
* On viewSubProjects.php, the "Project" section now shows the number of parent
builds with errors/warnings/etc.
=> Speedup project models

public/api/v1/manageBuildGroup.php, public/views/manageBuildGroup.html, tests/js/e2e_tests/manageBuildGroup.js
The queries required to render this tab take too long to complete.
Admins should now use index.php to move builds instead.
=> Remove the Move Builds tab from manageBuildGroup

public/api/v1/project.php, tests/kwtest/kw_web_tester.php, tests/test_createprojectpermissions.php
This fixes a bug that prevented project admins from saving changes
they have made to their project.  They could load the createProject.php
page but clicking the "Update Project" button did nothing.
We also improve the relevant test as part of this commit.
=> Allow project admins to edit their own projects

include/pdocore.php
Showing that an SQL error occurred in pdo_execute() isn't terribly
informative.  Also include a stack trace so CDash devs/admins can
more easily find what's going wrong.
=> Include stack trace in SQL error log

include/common.php, tests/test_autoremovebuilds_on_submit.php
I noticed one of our later build deletion tests was removing the
entire upload directory.  This is not good.
* Return early if no files to delete were found in the database.
* Update this function to use PDO.
* Add a new test case to make sure this problem stays fixed.
=> Revamp unlink_uploaded_file

.styleci.yml, include/pdocore.php, include/upgrade_functions.php
Apparently our StyleCI webhook broke and we didn't notice, so a couple
style violations slipped in.  This commit also adds a StyleCI configuration
file to the repository.
=> StyleCI fixes

public/views/partials/footer.html
The current implementation always requests the Google Analytics snippet
from Google's server (even after fixing the typo in ng-if). Fix this
by moving the actual script loading into an inline template and only
including it if a Google Analytics token is provided in the
configuration.
=> Selectively include Google Analytics snippet

models/build.php, models/buildtest.php, public/api/v1/viewTest.php, public/css/cdash.css, public/css/colorblind.css, tests/CMakeLists.txt, tests/data/DisabledTests/Test.xml, tests/test_disabledtests.php
A new test property in CMake will allow developers to mark a test as _disabled_.  Disabled tests are another type of _Not Run_ test.  Internally, this distinction is stored in the Details field of the test.
`viewTest.php` has been updated to show the details column for Not Run tests.  Disabled tests are shown in a different color on this page.
CDash's summary email has been updated to not include disabled tests in its list of Not Run tests.
=> Support for Disabled tests

include/common.php
This was inadvertently causing some git commit checksums to be converted to 0.
=> Disregard E notation for numbers in cast_data_for_JSON

public/upgrade.php
This upgrade path was accidentally added to the 2.4 section,
meaning that CDash installations already on v2.5 would not get this
change when performing an upgrade.
=> Move configure restruction to 2.6 block

public/api/v1/compareCoverage.php, public/api/v1/queryTests.php, public/api/v1/testDetails.php, public/api/v1/testSummary.php, public/api/v1/viewBuildError.php, public/api/v1/viewNotes.php, public/api/v1/viewTest.php
begin_JSON_response() needs to be called after can_create_project().
can_create_project() sets up the $_SESSION array by including login.php.
This is then read by begin_JSON_response() to determine whether to display
the "Login" or "My CDash" link in the upper-left corner of the page.
=> Restore "My CDash" link

models/buildconfigure.php, tests/test_buildconfigure.php
This still assumed that the configure table has a column for buildid, but this field has been moved to the build2configure table.
=> Fix query in GetConfigureForBuild

public/views/viewTest.html
This fixes a bug where viewTest.php did not correctly load the login
screen for private projects.  Not using one-time binding for
cdash.requirelogin is consistent with how our other views work.
=> Fix login prompt forviewTest.php

include/sendemail.php, models/build.php, tests/data/EmailProjectExample/cdash_3.log, tests/data/EmailProjectExample/cdash_committeremail.log, tests/data/SubProjectExample/cdash_2.log, tests/data/TimeoutsAndMissingTests/cdash_4.log, tests/data/TimeoutsAndMissingTests/cdash_5.log
- This change removes the separation of time out tests and failed tests in the email
- This change add the details of failure to the notification
- This changes "test failing" to "tests not passing"
=> removes separation of timeout tests, changes fail to not passing

tests/test_recoverpassword.php
Not sure how this works without this fix. Did something change recently with `User:: GetIdFromEmail`?
=> fixes false positive by filling and updating simpletest user

tests/CMakeLists.txt, tests/data/JUNit_example.xml, tests/test_junithandler.php, xml_handlers/testing_junit_handler.php
Give submitters a way to specify non-Nightly builds in JUnit test XML files.
=> Add track option to JUnit test parser

public/api/v1/createProject.php, tests/test_createprojectpermissions.php
createProject.php's API endpoint was accidentally attempting to
redirect to the login page.
Instead, it should note whether or not the user is logged in and
respond with an appropriate error if they are not authorized to
access this page for a given project.  This is consistent with how
the rest of our API endpoints operate.
=> Fix unauthenticated display of createProject.php

tests/kwtest/kw_web_tester.php, tests/test_autoremovebuilds.php, tests/test_autoremovebuilds_on_submit.php, tests/test_banner.php, tests/test_builderrordiff.php, tests/test_buildgroupposition.php, tests/test_buildgrouprule.php, tests/test_buildmodel.php, tests/test_buildtestdiff.php, tests/test_buildusernote.php, tests/test_dailyupdatefile.php, tests/test_image.php, tests/test_importbuilds.php, tests/test_projectmodel.php, tests/test_testmodel.php, tests/test_user.php
More reliably generate coverage information for tests that do not
interact with the web server.
=> Encapsulate testing hooks for code coverage

public/views/viewNotes.html
`<pre>` tags are sensitive to whitespace, so we need to be careful to inline them compactly in our views.
=> Fix erroneous indentation at the beginning of notes

public/api/v1/build.php
Somehow we ended up in a state where old build2grouprule rows were not getting
marked as finished when moving a build to a new group.  The result was two
active rules matching the build, with the oldest one winning out due to database
ordering.  This meant that builds would not move even after an admin told them
to.
We make this behavior more robust by not checking the old groupid when moving
a build to a new group.
=> Don't check old groupid when moving a build

models/build.php, public/ajax/buildinfogroup.php, public/ajax/expectedbuildgroup.php, public/ajax/finduserproject.php, public/ajax/findusers.php, public/ajax/getfeed.php, public/ajax/showtestfailuregraph.php, public/api/v1/index.php, public/views/index.html, tests/data/MultipleSubprojects/Notes.xml, tests/test_multiplesubprojects.php
For our new method of submitting SubProject builds all at once, any notes submitted get assigned to the parent build, not the individual children SubProject builds.  In this case, we now display a link to such Notes at the top of the page, alongside other bits of information that are common among the children.
=> Display link to parent notes on index.php

include/index_functions.php, models/subproject.php, public/api/v1/index.php, public/upgrade.php, public/views/index.html, public/views/partials/build.html, sql/mysql/cdash.sql, sql/pgsql/cdash.sql, tests/data/MultipleSubprojects/Project_2.xml, tests/test_multiplesubprojects.php, xml_handlers/project_handler.php
Now that we are building SubProjects all at once we can no longer rely on build start time to sort them in dependency order.  Instead, we keep track of the order that the SubProjects are listed in Project.xml and add this as a new sort column on index.php.
=> Add SubProject position column

models/build.php, models/subproject.php, tests/data/MultipleSubprojects/Coverage.xml, tests/data/MultipleSubprojects/CoverageLog.xml, tests/data/MultipleSubprojects/Project.xml, tests/test_multiplesubprojects.php, xml_handlers/GcovTar_handler.php, xml_handlers/coverage_handler.php, xml_handlers/coverage_log_handler.php
Teach our coverage XML parsers about the SubProject PATH property.  This allows them to correctly assign coverage on a per-SubProject basis by identifying which source files belong to each SubProject.
=> Update coverage parsers for all-at-once SubProject builds

tests/test_issuecreation.php, xml_handlers/project_handler.php
We noticed a bug where users were being stripped of their administrative
access to a project.  This was tracked down to the Project.xml parser.
If a user was listed as a contact for a SubProject (via an `<Email>` element)
then their subscription to the project would be replaced with a default
(non-administrative) role.
We now check for a previously existing subscription before saving one
with default permissions.
=> Prevent Project handler from overwriting user permissions

public/api/v1/buildSummary.php, public/api/v1/viewBuildError.php, public/api/v1/viewDynamicAnalysis.php, public/api/v1/viewNotes.php, public/api/v1/viewTest.php, public/views/buildSummary.html, public/views/partials/header.html, tests/test_multiplesubprojects.php
When reviewing build results for a particular SubProject, the 'Back' link should take you back to the parent build.  Previously it took you back to the results for the current testing day, which is one step further up.
=> Link back to parent build

models/project.php, tests/test_projectmodel.php
- This is a workaround for get_object_vars not adhering to output only public member properties
- In reference to: http://public.kitware.com/pipermail/cdash/2017-August/001791.html
bryon.bean@kitware.com
=> fix -- fixes Private members being output from get_object_vars

models/build.php, models/buildinformation.php, public/api/v1/buildSummary.php, public/api/v1/index.php, public/js/controllers/index.js, public/views/index.html, public/views/partials/build.html, tests/data/MultipleSubprojects/Build.xml, tests/data/MultipleSubprojects/Test.xml, tests/data/MultipleSubprojects/Upload.xml, tests/js/e2e_tests/done_build.js, tests/test_multiplesubprojects.php, xml_handlers/build_handler.php, xml_handlers/configure_handler.php, xml_handlers/testing_handler.php
Show more information that is common to all children at the top of the page.  This includes removing the configure/build/test timing columns for "all at once" SubProject builds.
=> Improve "advanced view" for parent builds

include/common.php
Before this change, a CDash-wide admin would still need to be subscribed to
an individual private project in order to be able to view it.
=> Allow global admins to access all private projects

public/api/v1/index.php, public/api/v1/testSummary.php, public/api/v1/viewTest.php, public/js/controllers/index.js, public/views/index.html, public/views/partials/build.html, public/views/testSummary.html, public/views/viewTest.html, tests/data/TestMeasurements/Test_subproj.xml, tests/test_managemeasurements.php
For tests with the optional extra measurement 'Processors', we now show an additional column: Proc Time.  This shows how long a test took to run multiplied by the number of processors it used.
=> New optional column: Proc Time

tests/ConfigTest.php
- PHPUnit is not trapping the Error thrown when a protected constructor is called.
bryon.bean@kitware.com
=> Fix -- Removes test calling protected constructor

public/api/v1/manageBuildGroup.php
- This change prevents PDO/PostgreSQL from complaining about a column not being included in the GROUP BY clause
bryon.bean@kitware.com
=> Fix -- Uses DISTINCT vs GROUP BY to prevent postgresql error output

public/views/partials/buildError.html
buildErrors were only showing the first label in the
list due to an '=' that should have been '=='.
=> buildError.html: correct assignment operator that should be a comparison

include/sendemail.php, models/build.php, tests/CMakeLists.txt, tests/test_subprojectemail.php
Defer to the children to report on their status instead
=> Don't send emails for SubProject parent builds

public/api/v1/buildgroup.php, public/js/controllers/manageBuildGroup.js, tests/js/e2e_tests/manageBuildGroup.js
Fix a bug that prevented project admins from deleting  a dynamic build rule if the "build name contains" field was left empty upon creation.
Also update this file to use common API functions and PDO.
=> Clean up buildgroup API endpoint

tests/data/UpdateAppend/Update_1.xml, tests/data/UpdateAppend/Update_2.xml, tests/data/UpdateAppend/Update_3.xml, xml_handlers/configure_handler.php, xml_handlers/coverage_handler.php, xml_handlers/coverage_log_handler.php, xml_handlers/testing_handler.php, xml_handlers/update_handler.php
Since v2.6, CTest has included in its XML files numeric timestamps that indicate
when each step started and ended.  It is safe to assume that any submissions to a
up-to-date CDash server will include these fields.
=> Assume timestamps will be present in XML files

models/project.php, models/user.php, public/api/v1/project.php, tests/test_updateonlyuserstats.php
Instead of defining $User, we take a simpler approach and call Save() on the UserProject model.
=> Fix undefined variable $User in project API

include/api_common.php, public/api/v1/queryTests.php, public/api/v1/timeline.php, public/views/queryTests.html, tests/test_managemeasurements.php
* Clean up the queryTests.php API endpoint
* Show Processors & Proc Time on this page when appropriate
* Better display of test timing on this page
=> Show proc time on queryTests.php

include/sendemail.php, tests/data/MultipleSubprojects/EmailOutput.log
- This fix addresses a subproject name appearing in the subject of a configure error email
- https://gitlab.kitware.com/snl/project-1/issues/41
=> Fix for Trillinos-ATDM issue #41

include/sendemail.php
While using PHP 7.1 and trying to submit a build results in: 
```
Fatal error:  Cannot use variable $maxitems twice in /var/www/CDash/include/sendemail.php on line 485.
```
=> Fix $maxitems used twice with PHP 7.1+

public/views/partials/buildError.html
This is meant to fix issue #637. Seems to work in local testing.
=> Add terminal colors to ctest launcher captured output as well

include/common.php
This should fix the timeline test that started failing once DST began.
=> Look up nightly start time relative to the requested date

models/coveragesummary.php
This decreases the likelihood of a race condition when doing
parallel processing of coverage. It doesn't get rid of the race
condition altogether (we would need some kind of locking or improved
upsert to do this), but it does significantly decrease the window of
time in which it can happen. We will need to figure out a better
long term solution.
=> Insert coverages one at a time to improve race condition

include/common.php
Prevent PHP from interpreting strings containing 'e' or 'E' as a number.
=> Make e-notation disabling check case insensitive

app/Controller/Auth/Session.php, include/CDash/System.php
Change how session_set_cookie_params() is called so that we only pass in
first parameter (lifetime).  This is how the function was called in CDash
before the recent addition of the Session class.  We were concerned that
restricting the cookie to a certain domain may cause login to fail on some
CDash installations.
=> session_set_cookie_params: only set lifetime

public/views/partials/build.html
When you click on the folder icon, the resulting dialog is only shown
if you are an administrator of this project.
=> Only show folder icon to admins

app/Model/Build.php, app/Model/BuildConfigure.php
These errors need to be retrieved from the prepared statement,
not from the database handle.
=> Fix how we capture SQL errors in our models

public/views/index.html
The background to this chart was displayed in the wrong color
because we were missing a CSS file.
=> Fix appearance of timeline on index.php

public/ajax/buildinfogroup.php, public/ajax/buildnote.php, public/ajax/expectedbuildgroup.php, public/ajax/expectedinfo.php, public/ajax/finduserproject.php, public/ajax/findusers.php
These AJAX endpoints should not echo <html> tags.
=> Don't emit any output before starting the session

public/api/v1/build.php, tests/js/e2e_tests/viewBuildError.js, tests/kwtest/kw_web_tester.php, tests/test_buildgrouprule.php, tests/test_managemeasurements.php, tests/test_timeline.php
Fix a bug involving cross-talk between projects that contain similarly named builds.
Also clean up the build.php API endpoint a bit.
=> Only expire build rules from the same project

gulpfile.js, package.json, public/js/controllers/head.js, public/js/controllers/index.js, public/views/buildProperties.html, public/views/buildSummary.html, public/views/compareCoverage.html, public/views/createProject.html, public/views/index.html, public/views/manageBuildGroup.html, public/views/manageMeasurements.html, public/views/manageOverview.html, public/views/manageSubProject.html, public/views/overview.html, public/views/queryTests.html, public/views/testDetails.html, public/views/testOverview.html, public/views/testSummary.html, public/views/user.html, public/views/userStatistics.html, public/views/viewBuildError.html, public/views/viewConfigure.html, public/views/viewDynamicAnalysis.html, public/views/viewDynamicAnalysisFile.html, public/views/viewNotes.html, public/views/viewProjects.html, public/views/viewSubProjects.html, public/views/viewTest.html, public/views/viewUpdate.html
CDash users will no longer have to delete their caches to get the latest
version of our CSS rules. This is similar to what we already do for our
Javascript files and HTML views.
=> Cache invalidation for CSS

app/Middleware/OAuth2.php, app/Middleware/OAuth2/GitHub.php, app/Middleware/OAuth2/GitLab.php, app/Middleware/OAuth2/Google.php, app/Middleware/OAuth2/OAuth2Interface.php, tests/case/CDash/Middleware/OAuth2/GitHubTest.php, tests/case/CDash/Middleware/OAuth2/GitLabTest.php, tests/case/CDash/Middleware/OAuth2/GoogleTest.php
Check private email addresses associated with a GitHub account when attempting to authenticate against CDash
=> make GitHub authentication more robust

public/js/controllers/filters.js, tests/js/e2e_tests/filterLabels.js
When the user clicks the '+' button to add a new filter search term,
the new blank row was getting added at the bottom of the list.
This commit improves this behavior by adding this new row below
the '+' button that the user clicked.
=> Add new filter where + was clicked

.env, Dockerfile, docker-compose.yml, docker-entrypoint.sh, docker.md
Adds a Dockerfile that builds a complete image for running CDash.
Also includes an entrypoint script for the image, with some logic to maintain a statically-defined set of initial users, and a docker-compose.yml file demonstrating how to run the CDash image alongside another image running mysql.
If merged, it would then be pretty easy to point a docker hub account at this repo and automatically deliver new builds with every subsequent merge.
=> add docker build and supporting files

config/queue.php
SQS being enabled by default could potentially trip up users of other message queue services.
=> Make all queues disabled by default

app/Model/BuildError.php, tests/case/CDash/Model/BuildErrorTest.php
When CTest collapses source paths, `/.../` represents the path up to - but not including - the actual root of the source directory.
For example, if we we encountered an error while building CMake, we would expect to see a path containing `/.../CMake/` in our Build.xml file.
=> Fix behavior of linkifying BuildErrors

include/repository.php
When generating links from build errors, make sure that they aren't interpreted as relative paths.
=> Fix links to source code viewers

app/Model/Build.php, app/Model/BuildConfigure.php, app/Model/Coverage.php, app/Model/CoverageFileLog.php, app/Model/DynamicAnalysis.php, app/Model/ModelType.php, app/Model/Test.php, app/Model/UserProject.php
This fixes CDash with PHP 7.2 as Object is a language type and shouldn't
be used for variable names!
Fixes #709
=> Rename Object to ModelType

public/views/testOverview.html
This chart had a black background (instead of transparent) because we forgot to include a CSS file.
=> Fix display of timeline chart on testOverview.php

include/log.php
We're seeing lots of entries like these in our logs:
Fatal error:Uncaught Exception: unlink returned non-success
Presumably this is due to cdash_unlink attempting to delete a file
that's already been removed.  This is a fairly benign problem that's
undeserving of an uncaught exception.
=> Teach cdash_unlink to throw fewer Exceptions

app/Middleware/Queue/SubmissionService.php, app/Model/Build.php, include/ctestparser.php, include/ctestparserutils.php, include/do_submit.php, include/fnProcessFile.php, package-lock.json, public/submit.php, tests/CMakeLists.txt, tests/case/CDash/Middleware/Queue/SubmissionServiceTest.php, tests/data/AssignBuildId/Configure.xml, tests/kwtest/kw_web_tester.php, tests/test_submission_assign_buildid.php
Assign a buildid upon submit time (rather than parse time) if CTest provides us with enough information to do so.
=> Assign buildids at submission time

app/Middleware/Queue.php, app/Middleware/Queue/DriverFactory.php, app/Middleware/Queue/SubmissionService.php, composer.json, composer.lock, include/ctestparser.php, include/do_submit.php, public/submissionConsumer.php, public/submit.php, tests/case/CDash/Middleware/Queue/SubmissionServiceTest.php, tests/case/CDash/Middleware/QueueTest.php
Currently, if a `submissionConsumer.php` process loses its connection to the SQL server, it will still attempt (and fail) to process submissions.
This PR takes the following steps to fix this behavior:
* configure PDO to throw an exception upon SQL errors
* configure Bernard to terminate a consumer when an exception is thrown
These changes will allow us to use `systemd` to automatically restart consumers when such an error occurs.
=> Terminate submissionConsumer upon SQL error

app/Model/Site.php, tests/test_sitemodel.php
We have a unique key in the site table on (name, ip).  Take better care to ensure that this constraint does not cause SQL errors to be logged unnecessarily.
* Search for existing sites by name AND ip address.
* If a unique key violation would occur during an UPDATE statement, return the existing record instead.
=> More gracefully handle unique key violations on the site table

include/ctestparser.php
Make it easier to filter out warnings emitted by PHP and CDash that occur when we attempt to parse a submission file that has already been deleted.
=> Lower log level for nonexistent submission file

Dockerfile
We had a hardcoded checksum for Composer which is now out-of-date. Instead we now download the latest checksum for more automatic verification of our Composer installer.
=> Fix installation of CDash via Dockerfile

app/Model/Site.php, include/upgrade_functions.php, public/upgrade.php, sql/mysql/cdash.sql, sql/pgsql/cdash.sql, tests/test_sitemodel.php, tests/test_upgrade.php
Force each separate site record to have a unique name. Previously we enforced a unique combination of name and ip address. The motivation to change this constraint was the fact that cloud services often change their ip addresses. This was causing us to accumulate many records that differed only by ip address, not by name.
Because such builds were considered to come from different sites, we lost the ability to easily track how build & test results changed from one build to the next.
=> Change unique constraint on site table

app/Model/Build.php, public/api/v1/addBuild.php, public/submit.php, tests/test_submission_assign_buildid.php
We recently updated submit.php to assign a buildid if a few extra
parameters are passed (2a27b4e).
This commit fixes a bug where such builds never had their submit time
properly set. It also updates the related addBuild.php endpoint to
make sure start time and submit time are properly set.
=> Set submit time when submit.php initializes the build

include/repository.php, tests/test_issuecreation.php
It does not make sense to display the "Create an issue for this build"
link when the build in question doesn't have any errors / warnings /
test failures / etc.
This change also silences a warning that was showing up in our PHP logs:
`Warning: Invalid argument supplied for foreach() in include/sendemail.php`
=> Do not show the issue creation link for clean builds

public/api/v1/user.php, public/views/user.html
We used to only show this section when the user belonged to a project
that requires authentication for submissions.  But authorization tokens
are generally useful for communicating with our API, so we should
make this section visible to all users.
=> Always show the authorization token section on user.php

include/CDash/Config.php, include/common.php, include/do_submit.php, include/sendemail.php
This fixes a bug in `get_server_URI()` that caused runaway requests to `submit.php` when `$CDASH_BASE_NAME` was not set.
See https://github.com/Kitware/CDash/issues/750#issuecomment-434422851 for context.
=> Fix bug in get_server_URI

public/views/partials/header.html
Some users of our Docker images are reporting that the Calendar link is getting rendered by AngularJS as `href="unsafe:javascript:;"`. Convert it to a blank href instead to keep web browsers happy.
=> Fix unsafe:javascript Calendar link

Dockerfile, docker-entrypoint.sh, scripts/bash/cdash.bash, scripts/bash/debug.bash, scripts/bash/misc.bash, scripts/bash/on_exit.bash, scripts/bash/tmp_dir.bash, scripts/bash/web.bash
Reworks the docker entrypoint so that its various operations are now separated.
The container can now be run with any number of the following operations as command-line arguments (where `N` stands for "number of days"):
```
install
upgrade
configure
fix-build-groups
check-builds-for-wrong-date
delete-builds-with-wrong-date
compute-timing:N
update-stats:N
compress
serve
```
The above list is also the order in which the operations are performed, if specified on the command line.
Build and run main services.  `docker-compose up -d --build`
Browse to `localhost:8080`, notice that the `install` procedure has not yet been performed.  By default, the container only serves traffic, now (`docker run ... serve`).
Run a one-shot container that runs the install process, sets up the predefined users, …
=> refactor docker shell scripts

app/Middleware/Queue/SubmissionService.php, app/Model/PendingSubmissions.php, include/do_submit.php
Use the same code path for XML and non-XML submissions.
Also more gracefully handle the (hopefully rare) situation where we attempt to decrement a `pending_submissions` record below zero.
=> Encapsulate where the queue name gets set for Bernard

app/Model/Build.php
We were locking a single row but then attempt to update potentially
more than one. So if two different process obtained locks on different
rows and then tried to update each other it would result in an SQL deadlock.
=> Fix potential deadlock when updating userstatistics table

tests/case/CDash/DatabaseTest.php, tests/test_timestatus.php
'use PDO' outside of a namespace doesn't do anything.
Removing it silences the following warning:
PHP Warning:  The use statement with non-compound name 'PDO' has no effect
=> Remove 'use' statements that don't do anything

tests/test_bazeljson.php, xml_handlers/BazelJSON_handler.php
This information needs to be computed after the tests are inserted into
the database.
=> Fix testdiff subscripts for Bazel results

app/Model/Build.php, tests/data/ConfigureWarnings/1.xml, tests/data/ConfigureWarnings/2.xml, tests/test_configurewarnings.php
The difference was getting associated with the previous build when it should be associated with the current build.
=> Bug fix for configureerrordiff

public/api/v1/buildgroup.php, public/api/v1/manageBuildGroup.php, public/views/manageBuildGroup.html, tests/js/e2e_tests/manageBuildGroup.js
When defining build groups, allow users to use wildcards to match one or more
characters in the build name.
=> Improve support for wildcards in buildgroups

tests/test_configurewarnings.php
Do not rely on database order for this test to pass
=> Make configurewarnings test less flaky

app/Model/Build.php, tests/data/BatchmakeNightlyExample/BatchMake_Nightly_Update.xml, tests/data/GithubPR/UpdateBug_Test.xml, tests/test_changeid.php
The build is initially created without a generator and is updated
later to include this information.
=> Fix bug where builds were not being assigned their generator

xml_handlers/GcovTar_handler.php
CDash with enabled branch coverage produces multiple versions of output for some lines(e.g.destructors).
**For example:**
```
392*:   37:Something::~Something()
-:   38:{
392*:   39:}
------------------
_ZN12SomethingD0Ev:
#####:   37:Something::~Something()
-:   38:{
#####:   39:}
------------------
_ZN12SomethingD2Ev:
392:   37:Something::~Something()
-:   38:{      
392:   39:}
```
**Shown as:**
Fix this by ensuring that duplicate lines in per-instance gcov output are
correctly ignored. Only the initial occurrence of each line will be processed.
=> Fix duplicate line output

public/api/v1/getPreviousBuilds.php, public/js/controllers/buildSummary.js
It was mistakenly showing the 50 oldest builds in the series, not
the 50 most recent ones.
=> Fix Build History table on buildSummary.php

.circleci/config.yml
Fix 404 for jessie-updates when running `apt-get update`.
=> Fix setup on CircleCI builds

public/views/partials/buildgroup.html
This cell is only conditionally displayed when we have labels enabled, so we must not have caught it as part of our UI refresh.
=> Remove extra table cell on buildgroup header

Dockerfile, include/login_functions.php
ldap over TLS is not supported by default, with this PR can be set from config file (or docker-compose file) using the variable CDASH_LDAP_STARTTLS
=> Added support for ldap over TLS

app/Model/Build.php, include/common.php, public/api/v1/addBuild.php, public/submit.php, tests/data/AssignBuildId/Configure.xml, tests/test_submission_assign_buildid.php
Our changes to assign buildids up front inadvertently caused us to lose some information about builds (OS name and version).
This PR also avoids an SQL exception when removing a build that does not have any tests.
=> Restore missing build information

app/Controller/Api/Index.php, app/Controller/Api/ResultsApi.php, app/Controller/Api/TestOverview.php, app/Model/Build.php, app/Model/Project.php, public/api/v1/buildSummary.php, public/api/v1/compareCoverage.php, public/api/v1/index.php, public/api/v1/manageMeasurements.php, public/api/v1/queryTests.php, public/api/v1/testDetails.php, public/api/v1/testSummary.php, public/api/v1/viewBuildError.php, public/api/v1/viewConfigure.php, public/api/v1/viewDynamicAnalysis.php, public/api/v1/viewDynamicAnalysisFile.php, public/api/v1/viewNotes.php, public/api/v1/viewSubProjects.php, public/api/v1/viewTest.php, public/api/v1/viewUpdate.php, public/views/partials/header.html, tests/CMakeLists.txt, tests/data/BuildDetails/InsightExperimentalExample_Expected.json, tests/test_expectedandmissing.php, tests/test_indexnextprevious.php, tests/test_projectwebpage.php
Avoid generating links to "blank pages" -- pages for dates when no results occurred.
When a user navigates to index.php with no date specified, display the most recent date with results (rather than unconditionally linking to the current day).
Also update next/previous links on index.php so they always point to dates with results (skipping over empty dates).
=> Skip over dates with no results

app/Lib/Repository/GitHub.php, composer.json, composer.lock, tests/case/CDash/Lib/Repository/GitHubTest.php, xml_handlers/done_handler.php
* Use newly upstreamed php-github-api Checks class
* Only show the most recent result (per build name) in the check
* Display build's in alphabetical order
* Display the "ship it" squirrel on successful checks
=> Improvements to CDash's GitHub Checks

app/Controller/Api/Index.php, app/Model/Build.php, include/common.php, include/filterdataFunctions.php, include/upgrade_functions.php, public/api/v1/index.php, public/upgrade.php, sql/mysql/cdash.sql, sql/pgsql/cdash.sql, tests/test_excludesubprojects.php, tests/test_managemeasurements.php, tests/test_multiplesubprojects.php, tests/test_upgrade.php, xml_handlers/testing_handler.php, xml_handlers/testing_junit_handler.php, xml_handlers/testing_nunit_handler.php
We now record two separate test time values per build.
* Wall clock time. This is how long was spent running all tests for a given build. This is stored in build.testduration.
* Execution time (aka proc time). This is multiplied by the number of processors used on a per-test basis. This is stored in buildtesttime.time.
=> Implement "proc time" for parent builds

app/Controller/Api/Index.php, tests/test_multiplesubprojects.php
We only need to modify the number of build errors, passing tests, etc for parent builds. When viewing the list of child builds, each individual build will either be presented whole or completely removed from the list by these filters.
=> Fix behavior of SubProjects include filter in child view

.circleci/config.yml
This will help our GitHub check pass when a flaky build gets re-run.
=> Remove CircleCI number from build name

app/Controller/Api/Index.php, tests/test_multiplesubprojects.php
The following fields should not have their values modified when excluding SubProjects from all-at-once parent build results:
* configure errors
* configure warnings
* configure duration
* build duration
=> Fix behavior of SubProjects filter for all-at-once builds

app/Controller/Api/Timeline.php
* More gracefully handle missing data in the buildgroup timeline
* Put the green ("clean") series on the bottom of the timeline. Previously it rested at the top instead.
=> Timeline improvements

app/Controller/Api/Index.php, tests/test_multiplesubprojects.php
When using the "SubProjects include" filter, do not add up the
build durations of the selected children for "all-at-once" parent builds.
=> Do not sum child build durations for all-at-once builds

public/api/v1/createProject.php
Depending on your SQL server settings, this value being undefined
could cause errors upon project creation.
=> Expicitly define 'Public' field for new projects

app/Http/Controllers/CDash.php
This page was inadvertently broken during our move to Laravel because
the name of its AngularJS controller (index) does not match the name
of the page (viewBuildGroup).
=> Fix display of viewBuildGroup.php

app/cdash/app/Controller/Api/Index.php, app/cdash/app/Controller/Api/QueryTests.php, app/cdash/app/Controller/Api/ResultsApi.php, app/cdash/app/Model/Test.php, app/cdash/include/filterdataFunctions.php, app/cdash/public/api/v1/filterdata.php, app/cdash/public/api/v1/testDetails.php, app/cdash/public/js/controllers/filters.js, app/cdash/public/js/controllers/queryTests.js, app/cdash/public/views/queryTests.html, app/cdash/tests/test_querytests.php
Allow users to search for tests based on their output. We also add an option to show what test output matched the specified search criteria.
=> add "Test Output" filter to queryTests.php

app/Http/Kernel.php
This Middleware check breaks submissions larger than post_max_size.
=> Remove ValidatePostSize check from CDash

app/cdash/app/Model/Project.php, app/cdash/tests/case/CDash/NightlyTimeTest.php, app/cdash/tests/test_buildgetdate.php
The input to this function is always a timestamp from the database,
which is stored in UTC format. So we need to explicitly tell PHP
what timezone this date string is from so that it can convert it
to the correct UNIX timestamp value. This is a bug fix for servers
that are configured to locally use a non-UTC timezone.
=> Append 'UTC' to input of Project::GetTestingDay()

app/cdash/include/upgrade_functions.php, app/cdash/tests/CMakeLists.txt, app/cdash/tests/js/e2e_tests/viewBuildError.js, app/cdash/tests/test_upgrade.php
The format of these rules has changed slightly over time, so we add
an automatic upgrade converter to make them consistent.
This commit also re-enables the upgrade test, fixes it for postgres
builds, and makes the corresponding changes to hardcoded buildids
further down the testing dependency line.
=> Upgrade path for older dynamic build group rules

.circleci/config.yml, docker/commands.bash
Speed up CircleCI builds for PRs that are not modifying our Dockerfile.
=> cache CDash Docker image built on Circle

app/cdash/include/Messaging/Topic/TestFailureTopic.php, app/cdash/tests/case/CDash/Messaging/Topic/TestFailureTopicTest.php, app/cdash/tests/case/CDash/MultipleSubprojectsEmailTest.php, app/cdash/tests/data/DisabledTests/Test.xml, app/cdash/tests/test_disabledtests.php, app/cdash/tests/test_timeoutsandmissingtests.php
Redefine the notification topic to strictly deal with failing tests.
=> Do not send out email notifications for notrun tests

app/cdash/app/Model/Build.php, app/cdash/app/Model/BuildConfigure.php, app/cdash/app/Model/Test.php, app/cdash/app/Model/User.php, app/cdash/include/Messaging/Topic/BuildErrorTopic.php, app/cdash/include/Messaging/Topic/ConfigureTopic.php, app/cdash/include/Messaging/Topic/LabeledTopic.php, app/cdash/include/Messaging/Topic/TestFailureTopic.php, app/cdash/tests/case/CDash/Messaging/Topic/ConfigureTopicTest.php, app/cdash/tests/case/CDash/Messaging/Topic/TestFailureTopicTest.php
This restores the ability to use has() to check if a label is in a collection or not.
=> Populate LabelCollections with key = Text

docker/cdash.docker
We were seeing angularjs errors due to production minification.
For now, run npm dev instead of npm prod.
=> Always do npm "dev" builds

app/cdash/tests/test_bazeljson.php, app/cdash/xml_handlers/BazelJSON_handler.php
Otherwise, compiler errors that caused the Bazel error are incorrectly
broken out separate errors.
=> Improve parsing of Bazel build errors and warnings

app/cdash/public/manageUsers.xsl
Make it so pressing enter on manageUsers.php doesn't submit the "promote to user" form.
=> Prevent accidental promotion to admin

app/cdash/app/Controller/Api/Index.php, app/cdash/tests/CMakeLists.txt, app/cdash/tests/test_subprojectorder.php
De-duplicate subproject order on index.php when no explicit order was previously submitted to the database.
=> Prevent multiple subprojects from being listed with the same order

app/cdash/sql/mysql/cdash.sql, database/migrations/2020_06_22_085012_increase__test_measurement_value_size.php
This fixes an issue where we could only support ATTACHED_FILES
up to size 64 kb.
=> Increase size of testmeasurement::value

app/cdash/app/Model/DynamicAnalysis.php, app/cdash/tests/test_multiplesubprojects.php
Avoid memory exhaustion errors when decompressing lots of data.
Also clear the Log member variable after it's been inserted into the database.
Otherwise we can also run out of memory when inserting lots of dynamic analysis
results for a single build.
=> Use buffers when decompressing dynamic analysis logs

docs/install.md
Hi there, I stumbled across this dead link in the installation documentation.
=> Fix dead link in installation documentation

app/cdash/public/api/v1/testGraph.php, app/cdash/tests/data/TestMeasurements/Test.xml, app/cdash/tests/data/TestMeasurements/Test_subproj.xml, app/cdash/tests/test_managemeasurements.php
All of a test's extra measurements were inadvertently getting shown on the same chart, rather than being displayed individually.
=> Fix extra measurement graphs on test details page

app/Models/BuildTest.php
This bug would occur when loading viewTest.php for a build with missing tests that belongs to a project with timestatus checking enabled.
=> Fix Undefined Index on viewTest.php

app/Http/Controllers/CDash.php, webpack.mix.js
Only attempt to use `git describe` if this is a git clone of CDash.
=> Make the Javascript dependency on git optional

app/Models/BuildTest.php, app/Models/TestLabel.php, app/cdash/include/common.php, app/cdash/public/api/v1/testDetails.php, app/cdash/public/css/common.css, app/cdash/tests/CMakeLists.txt, app/cdash/tests/data/MultipleLabelsForTests/Test.xml, app/cdash/tests/data/OutputColor/Test_2.xml, app/cdash/tests/test_multiplelabelsfortests.php, app/cdash/tests/test_outputcolor.php, app/cdash/xml_handlers/testing_handler.php, resources/js/components/TestDetails.vue, tests/Spec/test-details.spec.js
* Show more than the first label for a test on viewTest.php
* Show test labels on testDetails.php
* Extra padding between measurement name & value on testDetails.php
* Add support for 'preformatted' test measurements. These get rendered in a `<pre>` tag like test output does.
=> Various fixes & improvements to test displays

database/migrations/2021_07_20_093407_email_verified.php
This column was missing from some older installations of CDash,
causing HTTP 500 errors when a new user attempted to register.
=> Add migration to add user::email_verified_at column

app/Console/Commands/MigrateConfig.php, config/oauth2.php, tests/Feature/MigrateConfigCommand.php
This PR adds environment variables to control whether an oauth2 provider is enabled.  See https://github.com/Kitware/CDash/issues/958#issuecomment-682574753
=> Enable and disable oauth2 providers with environment variables

tests/Feature/MigrateConfigCommand.php
This was caused by explicitly searching for 'true' when PHP (at least sometimes)
writes out a '1' instead. Loosely typed languages are fun.
=> Fix failing test case in MigrateConfigCommand

app/cdash/app/Controller/Api/Index.php, app/cdash/tests/test_subprojecttestfilters.php
In 2a58314 we added a feature to automatically propagate SubProject filters
from index.php to viewTest.php.
But this initial implementation did not work properly when using
'SubProject include' filters. This commit fixes that behavior and adds testing
for this case.
=> Fix SubProject filter propagation for the 'include' case

app/cdash/include/ctestparserutils.php, app/cdash/tests/CMakeLists.txt, app/cdash/tests/data/StartTimeFromNotes/Notes.xml, app/cdash/tests/test_starttimefromnotes.php, app/cdash/xml_handlers/note_handler.php
Since CTest v3.11, the `<Time>` XML element in Notes.xml contains an
unambiguous UNIX timestamp. If found, we now prefer this value over
the human-readable date/time string found in `<DateTime>`.
This commit also moves/renames
`ctestparserutils::str_to_time()`
to
`notes_handler::getTimestampFromDateTimeElement()`
since this is the last place this function is being used.
=> Selectively prefer <Time> XML element in Notes.xml

app/cdash/app/Controller/Api/TestDetails.php, app/cdash/tests/CMakeLists.txt, app/cdash/tests/data/RedundantTests/Test.xml, app/cdash/tests/test_redundanttests.php
This commit fixes a bug on the 'test details' page.
It would occur when a build had two separate tests with the same name.
In that case, 'test details' would show the output from the 1st test, even
if you were attempting to look at the results from the second one.
=> Improve support for redundant tests

app/Models/BuildTest.php, app/cdash/app/Controller/Api/ViewTest.php, app/cdash/tests/data/RedundantTests/Test.xml, app/cdash/tests/test_redundanttests.php
This commit fixes a bug where incorrect measurements would sometimes
be displayed on `viewTest.php` when a build contains more than one test
with the same name.
=> Show correct measurements for redundant tests

.env.example, app/cdash/app/Lib/Repository/GitHub.php, app/cdash/include/repository.php, config/cdash.php
Allow CDash instance administrators to control whether or not their installation of CDash will attempt to communicate with Version Control API endpoints (eg. api.github.com).
=> New config option: USE_VCS_API

app/cdash/include/common.php, app/cdash/public/js/controllers/index.js, app/cdash/public/js/controllers/queryTests.js, app/cdash/public/js/controllers/viewTest.js, app/cdash/public/views/partials/header.html, app/cdash/tests/js/e2e_tests/queryTests.js, app/cdash/tests/js/e2e_tests/viewTest.js, resources/js/components/page-header/HeaderMenu.vue, tests/Spec/page-header/header-menu.spec.js
Some projects have lots of tests, loading them all by default is expensive and unnecessary.
=> Filter out passed tests from queryTests.php by default

docker/bash/misc.bash, docker/cdash.docker, docker/commands.bash
Copy files and execute commands as www-data as much as possible, rather than using chown, chgrp, or chmod after the fact.
This makes it so we no longer have to explicitly configure the CDash clone as a safe directory for git.
=> Improve permissions in Docker image

app/Console/Commands/UpdateDependencies.php, app/cdash/public/upgrade.php, app/cdash/public/upgrade.xsl, docker/cdash.docker
Add a new Artisan command which executes composer and npm updates and installations.  This command should take an argument which toggles whether the development set of libraries is installed or not.
Add a button on the maintanence page which executes this call and updates a message when it finishes.
=> Add dependency update command for Artisan

app/cdash/public/js/je_compare.js
Without touching the package versions listed in package.json, the image comparison is broken in CDash.  
The issue seems to come from a bad use of the jQuery method load in the je_compare plugin.  
http://api.jquery.com/load-event/
=> Fix image comparison

app/Console/Commands/UpdateDependencies.php
Expand the flags used for the composer update/install process by adding arguments to the update.  It should add a "no-dev" flag to the default list and ensure that the versions are instructed to prefer the lowest version of dependencies.
Fixes: #1294
=> Expand flags for composer process

app/cdash/public/css/common.css, app/cdash/public/footer.xsl, app/cdash/public/views/partials/footer.html, resources/views/build/page-footer.blade.php
For pages with a minimal amount of content, the page footer is displayed in the middle of the page.  This contributes to a low quality user experience across the platform as a whole.  This PR moves the footer to the bottom of the page such that the footer can be pushed down the page if the page has a lot of content, but the footer can never be placed higher than the bottom of the user's browser window.
Before:
After:
=> Move footer to bottom of page

app/cdash/public/views/partials/header.html
When viewing a project, a number of configurable menu items are added to the menu bar.  If these values aren't set, the menu item is still displayed, with a blank destination URL.
For example, the documentation menu item (Project > Documentation in the menu bar) is not set for the CDash project [here](https://open.cdash.org/index.php?project=CDash), and a blank entry is displayed.  This PR changes the behavior to hide menu items whose value hasn't been set configured, so the user only ever sees menu items which lead somewhere useful.
=> Don't show links to blank URLs in menu

app/cdash/tests/kwtest/simpletest/exceptions.php, app/cdash/tests/test_multiplesubprojects.php
Our current testing infrastructure tries to catch `Exception`s, which means that the tests continue to run even if some types of errors occur.  For example, [this](https://app.circleci.com/pipelines/github/Kitware/CDash/969/workflows/bb608c10-25bb-4384-b46a-efe7958ca409/jobs/4464?invite=true#step-104-3253) type error has gone unseen for some time, giving developers a false sense of security.  A real world example: https://github.com/Kitware/CDash/pull/1296 passed the tests, despite failing all of the tests in `test_authtoken.php`.  If I hadn't scrolled through the test log in detail, this PR could have easily been merged with the failing tests.
This PR changes the testing behavior to catch anything `Throwable`, not just the various types of `Exception`.  `Error`s such as the type error …
=> Fail tests when errors occur

docs/docker.md
Add instructions on the proper way to pull or build the needed images before attemping to start the docker-compose system.
=> Update docker start documentation

.php-cs-fixer.dist.php, CMakeLists.txt
We currently run the PHP style fixer during the CMake configure step, which fixes most of the code before we re-run the fixer again during the testing process to catch style issues.  This means that there are potentially style issues in the codebase which are not caught by our test suite because they are automatically fixed before the test suite is run.
This PR removes the "fix" step from the CMake configure process.  To automatically fix changes locally, it is now necessary to run `vendor/bin/php-cs-fixer fix` manually.
In the future, we may want to investigate using [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) instead of [PHP-CS-Fixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer) since the former provides more helpful errors.
I believe that this fixes …
=> Don't run PHP style fixer before running test suite

app/cdash/public/viewSite.xsl, app/cdash/public/views/viewProjects.html
The main page content of most CDash pages is wrapped in a `<div>` with the ID `#main_content`, which is styled to provide a small amount of padding around the edges of the page.
This PR adds a wrapper `<div>` around the main content of the `viewSite` page to make it match the rest of the CDash interface.
The same changes have been made to the `viewProjects` page as well.
Before:
After:
=> Add padding around viewSite page content

app/cdash/public/css/common.css
Most CDash pages have a header with an image on the left and a small amount of text on the right.  Some pages have this flipped, such that the image is on the right and the text is on the left.  This visual inconsistency is poor UI design.
To resolve this issue, I removed the `order` CSS property.  Since this property was set to 1, it is possible that a developer set it to 1 sometime in the past under the assumption that 1 is the leftmost value possible.  In fact, 0 is the leftmost value for this property, which is why the image was displayed out of order.
Before:
After:
=> Move header image to left side

app/cdash/public/js/controllers/index.js
The auto-reload functionality on `index.php` is currently broken.  It is possible to turn it on, but impossible to turn it off without deleting the relevant cookies manually.  This error is due to Javascript's type inference rules.  Cookie values are returned as strings and the current code attempts to treat them as boolean integer values.  This is problematic because both `!'0'` and `!'1'` evaluate to false.
The code has been refactored and the auto-reload can be turned on and off properly.
=> Fix auto-reload functionality

docker/bash/misc.bash
In the event that an older system moves to the latest CDash docker-compose framework, try to replace the characters that were expected when the text was sent to `config.local.php` file with blanks to closer match the formatting used in the .env file that it now is a part of.
Fixes issue #1336
=> Account for formatting issues in CDASH_CONFIG

docker/common.docker
The [base image](https://hub.docker.com/layers/library/php/8.1-apache-buster/images/sha256-8af25037ef2d776145f18fcfe4fc76627ce80793d300cf49334307475ce30a5a?context=explore) we currently use for Docker installs is not based on the latest version of Debian and has a large number of security vulnerabilities listed.  The [latest version](https://hub.docker.com/layers/library/php/8.1-apache-bullseye/images/sha256-2723799df278efb7c49a134e278c5e6c9549b3a2c7bdcecc442974509eb57380?context=explore) of Debian has significantly fewer vulnerabilities.
This PR serves as a temporary patch while we investigate potentially switching away from Debian altogether.
=> Update Docker base image to latest Debian

app/Services/AuthTokenService.php, app/cdash/public/api/v1/user.php, app/cdash/public/js/controllers/user.js, app/cdash/public/js/services/apiLoader.js, app/cdash/public/views/user.html, config/cdash.php
This PR adds two new configuration settings which allow system administrators to allow or disallow full-access and submit-only authentication tokens which may be used to submit to any project.
=> Allow configuration of allowable token scopes

app/cdash/include/CDash/Log.php, app/cdash/include/log.php, phpstan-baseline.neon
The `add_log()` function, and the `\CDash\Log` class are superseded by Laravel's logging feature.  To prevent future usages of these older logging methods, they have been marked with the `@deprecated` annotation, which will cause PHPStan to throw errors if new usages are added.
=> Deprecate `add_log()` function

phpstan-baseline.neon
Removal of old code caused the removal of an "add_log" call. Decrease the expected value in the phpstan-baseline file.
=> Fix error count for BuildGroup.php

app/cdash/public/viewCoverage.xsl
The formatting of the page `viewCoverage.php` is currently broken.  I was unable to trace the source of the issue, but the formatting issue has been present since at least January 2023.  I have wrapped the main content of the page in a div with the id `main_content`, similar to the changes in https://github.com/Kitware/CDash/pull/1317.
=> Fix `viewCoverage.php` formatting

docker/bash/misc.bash
When the setup_local_service function is called, like in a
`docker-compose run --rm cdash install configure`
run, CDash still writes a ";"  to the .env file which throws the parsing off.
See: #1348
=> Remove more php config syntax

app/cdash/public/css/common.css
The menu on some administrative pages is left-aligned, while it is supposed to be right-aligned.  This is due to the CSS `order` property being poorly used, similar to https://github.com/Kitware/CDash/pull/1318.
=> Fix ordering of header menu items

app/Console/Commands/AuditDependencies.php, app/Console/Kernel.php, app/cdash/public/upgrade.php, app/cdash/public/upgrade.xsl, docker/docker-entrypoint.sh
Add a command which echoes the reports of `composer audit` and `npm audit` to the console.
Use Laravel's scheduler to run the task and pipe the output to a known file where the maintenance page will read it in for display. The task should run once a day at midnight and also be available for manual run.
=> Add dependency audit command

app/Console/Commands/QueueSubmissions.php, app/Jobs/ProcessSubmission.php, app/Services/UnparsedSubmissionProcessor.php, app/cdash/app/Model/Project.php, app/cdash/public/api/v1/project.php, app/cdash/public/submit.php, database/migrations/2023_04_16_204249_project_name_regex.php
The current regex we use to validate project names allows project names which may break CDash to be created.  This PR restricts the allowable characters in a project name to the upper- and lower-case letters, numbers, `-`, `+`, `_`, `.`, and the space character.  Filesystem paths have also been sanitized when submitting files to ensure that a handful of edge cases don't lead to CDash errors.
Explanation of regex changes:
1. `\s` -> `\ ` (accept only regular spaces; prohibit tabs, newlines,  and other forms of whitespace)
2. `-` -> `\-` (accept the `-` character instead of any character between `+` and `_`)
If any CDash instance currently has a project with a disallowed character in its name and attempts to run the migration in this PR, the disallowed characters will be converted to the …
=> Change how project names are validated

app/cdash/public/css/common.css
Various components of the top menu are currently misaligned.  In particular, the menu item background overflows the menu bar when the hover action is triggered.  The items are also not horizontally aligned with the edges of the remaining page content.
This PR is a quick patch to improve the top menu UI.  It would be good to fully refactor the underlying CSS to be more robust at some point.
=> Align top menu items with page content

app/Providers/OAuthServiceProvider.php, app/cdash/app/Model/Build.php, app/cdash/app/Model/Project.php, app/cdash/app/Model/Repository.php, app/cdash/app/Test/OAuthTestHelper.php, app/cdash/include/CDash/ServiceContainer.php, app/cdash/include/api_common.php, app/cdash/tests/case/CDash/Middleware/OAuth2/GitHubTest.php, app/cdash/tests/case/CDash/Middleware/OAuth2Test.php, app/cdash/xml_handlers/build_handler.php, app/cdash/xml_handlers/configure_handler.php, app/cdash/xml_handlers/dynamic_analysis_handler.php, app/cdash/xml_handlers/testing_handler.php, app/cdash/xml_handlers/update_handler.php, phpstan.neon
PHPStan supports exception checking, and this PR is the first of several PRs to gradually turn on PHPStan's exception checking features.  The configuration option being enabled in this PR flags all incorrect PHPDoc `@throws` tags.
=> Remove all incorrect `@throws` annotations

phpstan-baseline.neon, phpstan.neon
This PR enables PHPStan's `@throws` annotation checking functionality.  Any `Exception` or `RuntimeException` is assumed to be an "unchecked" exception which is supposed to crash the application.  Any other exception is a "checked" exception, and must be specified in an `@throws` annotation.
It is probable that many of our current usages of `RuntimeException` are not meant to be unchecked, and should be converted to checked exceptions eventually.
=> Enforce correct `@throws` tag on all functions

app/Models/User.php, app/cdash/app/Model/User.php, phpstan-baseline.neon
We currently have two separate `User` classes, with the members of one being accessible through the other via reflection.  PHPStan doesn't understand this, and is unaware of the fact that the `IsAdmin()` method is in fact valid for both classes.
=> Help PHPStan understand our user model setup

app/cdash/public/ajax/buildinfogroup.php, app/cdash/public/ajax/expectedinfo.php, app/cdash/public/ajax/finduserproject.php, app/cdash/public/ajax/getsubprojectdependencies.php, app/cdash/public/ajax/getviewcoverage.php, app/cdash/public/ajax/showcoveragegraph.php, app/cdash/public/ajax/showtestfailuregraph.php, app/cdash/public/api/v1/buildSummary.php, app/cdash/public/api/v1/createProject.php, app/cdash/public/api/v1/getbuildid.php, app/cdash/public/api/v1/getuserid.php, app/cdash/public/api/v1/manageOverview.php, app/cdash/public/api/v1/manageSubProject.php, app/cdash/public/api/v1/viewBuildError.php, app/cdash/public/api/v1/viewConfigure.php, app/cdash/public/api/v1/viewDynamicAnalysis.php, app/cdash/public/api/v1/viewDynamicAnalysisFile.php
Fixes a problem where unauthorized users could access data about projects they could not view.
=> Ensure user has access to project before sending project data

app/cdash/include/CDash/Database.php, app/cdash/include/common.php, app/cdash/include/pdo.php, phpstan-baseline.neon
We should eventually move away from raw PDO access, to run all of our database queries through Laravel's database features.  Amongst other things, one benefit of doing so is the ability to run individual tests against the database as part of one database transaction which then gets rolled back once the test completes.
Switching all of our current code to use the Laravel database API is impractical due to the sheer volume of code changes necessary, so the relevant functions have been marked as deprecated to prevent future usages of them.  As parts of the codebase are refactored, the number of ignored errors should hopefully be reduced to the point that we may be able to remove these functions entirely.
=> Deprecate all raw PDO access

app/cdash/public/manageBanner.xsl, app/cdash/public/subscribeProject.xsl, resources/js/components/EditProject.vue
Currently, if you navigate to the edit project page and select the default "Choose..." option in the project selector, a 404 error will result because there is no project with an ID of -1.  Given that this option currently does nothing productive, I have removed it entirely.  If there are no projects available, there will simply be no projects to be selected.
=> Remove "Choose" option from admin dropdowns

app/cdash/public/css/common.css
`viewBuildError.php` currently applies custom styles which conflict with the standard Bootstrap `<pre>` tag styling.  This results in ugly (and inconsistent) black borders around prepared text.
Before:
After:
=> Standardize prepared text UI

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
The settings page for the issue templates reports that "About can't be blank".
Add a description field to each template.
=> Add descriptions to issue templates.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Follows #1408.  GitHub requires several more fields for issue templates.
=> Fix issue template descriptions

app/cdash/include/common.php, phpstan-baseline.neon
#1351 removed the last remaining reference to the function `redirect_to_https()`, and it is now possible to remove the function itself.
=> Delete `redirect_to_https()` function

app/Http/Controllers/ManageProjectRolesController.php
Add a missing `=` sign where a project ID is checked to prevent a syntax error.
Fixes: #1414
=> Fix query for ManageProjectRole

app/cdash/public/views/manageBuildGroup.html, app/cdash/public/views/manageSubProject.html
Fixes a UI issue introduced by #1351 where the tabs were offset from the tab content on some pages.
Before:
After:
=> Fix AngularJS tab UI

.env.example, app/Http/Controllers/Auth/RegisterController.php, app/cdash/app/Controller/Api/ViewProjects.php, config/auth.php, resources/views/components/header.blade.php, routes/web.php, tests/Feature/LoginAndRegistration.php
Add an environment variable which will disable the showing of the registration link, form, and acceptance of the JSON in the API.
The `manageUsers` and `manageProjectRoles` pages will still allow an administrator to register a user.
=> Add environment flag for disabling registration

app/Http/Controllers/BuildController.php
#1351 failed to properly handle links to the corresponding project on the `/build/<id>`, `/build/<id>/notes`, and `/build/<id>/configure` pages.
=> Fix missing `/build/<id>` project URL

resources/views/components/header.blade.php
Fixes an issue introduced by #1351 where the page header might improperly show as "- <title>" with a leading dash when an invalid project is specified.  This issue primarily occurred on pages with a project selector containing an "all projects" option, such as the banner management page.
=> Fix page header formatting when invalid project provided

app/Http/Controllers/SiteController.php
`editSite.php` is currently broken due to an oversight when creating https://github.com/Kitware/CDash/pull/1332.
Instead of counting the number of rows queried in PHP, https://github.com/Kitware/CDash/pull/1332 used SQL to count the number of rows instead.
This PR will create merge conflicts with https://github.com/Kitware/CDash/pull/1351, which should be resolved by simply re-copying this file into the new controller.
=> Fix `editSite.php` DB query typo

app/cdash/public/ajax/buildnote.php, app/cdash/public/views/partials/build.html, phpstan-baseline.neon
The AJAX endpoint which allows access to build note data is currently completely broken.  The primary way this page is accessed is the icon on the administrative dashboard boxed in red below:
In addition to fixing the broken functionality, access controls which only allow administrators to access this endpoint were implemented.  It was not clear what the intended access level was, but the only (legitimate) way to access this page is through the administrator UI.
=> Fix broken `buildnote.php`

app/cdash/app/Controller/Api/Timeline.php, app/cdash/app/Model/Build.php, app/cdash/include/dailyupdates.php, app/cdash/public/api/v1/overview.php, app/cdash/tests/case/CDash/Model/BuildRelationshipTest.php, app/cdash/tests/test_builddetails.php, app/cdash/tests/test_longbuildname.php, app/cdash/tests/test_multiplelabelsfortests.php, phpstan-baseline.neon
This PR fixes most of the undefined variables flagged by PHPStan.  Most of these are on code paths which are not frequently travelled, or in places where errors may go unnoticed.
The one remaining undefined variable (excluding false positives) flagged by PHPStan will be resolved once https://github.com/Kitware/CDash/pull/1351 is merged.
=> Fix undefined variables

app/cdash/app/Model/SubProject.php
One of the possible cases when querying a subproject was overlooked in #1332, due to a lack of test coverage.  This change is similar to #1402.
=> Fix subproject DB queries

resources/views/auth/login.blade.php
Fixes a regression introduced by #1386 where the login page HTML contained an unclosed `<div>` element.
=> Fix unclosed HTML on login page

app/cdash/public/ajax/getviewcoverage.php
Fixes an issue introduced by #1379 by adding a missing import.
=> Fix missing import in `getviewcoverage.php`

resources/js/components/BuildConfigure.vue, resources/js/components/BuildSummary.vue
The configure output is currently displayed as prepared text in multiple locations, but the configure command itself is not.  The configure command can get quite lengthy at times, and is certainly technical, so it seems reasonable to also display it as prepared text.
Before:
After:
=> Display configure command as prepared text

app/cdash/app/Controller/Api/ViewProjects.php, phpstan-baseline.neon
`viewProject.php` currently executes multiple queries in a loop, one for each project displayed on the page.  This results in hundreds of unnecessary queries being executed during a single page load.  The queries have been simplified such that a constant number of larger queries are executed.  In my relatively small development environment, this resulted in a roughly 50% page load speedup.  This speedup is likely even larger on production systems with a large number of projects and builds.
=> Optimize `viewProject.php` database queries

resources/js/components/BuildSummary.vue
Add a leading slash to the API URL string to avoid keeping the "/build/" part of the URL from being added to the API call. If it was included, the Laravel routing wouldn't recognize it as an API call and return a 404.
Add an icon to show that the content is clickable, like other examples later on in the page
Fixes: #1429
=> Fix buildSummary page notes API call

app/cdash/include/common.php, phpstan-baseline.neon
The `remove_build()` currently does a significant amount of unnecessary work, passing data back and forth between the database and web server, when it could be done entirely on the database side.  This PR simplifies a handful of locations where it was possible to execute the entire operation in SQL.  I also converted all of the database functions to Laravel's DB system along the way.
Ultimately it would be good to replace most of this logic with the database's build-in foreign-key relationships.  Doing so requires a significant amount of effort, so I have deferred that to a future time.  I plan to come back and look at setting up such foreign-key relationships for as many of the simple tables as possible in the near future, once this PR is merged.
=> Remove unnecessary `remove_build()` data handling

app/cdash/app/Controller/Api/QueryTests.php, app/cdash/app/Model/Build.php
The build `type` has been added to the API endpoints `api/v1/viewTest.php` and `api/v1/queryTests.php`.  The `type` field is not used in the UI, but is present in case users want to write their own scripts which query the CDash API.
=> Add `type` to build metadata API response

app/cdash/public/css/common.css, resources/views/components/header.blade.php
#1351 introduced an issue where the project nav displayed left of center.
Before:
After:
=> Center project nav

app/cdash/app/Model/Image.php, app/cdash/include/CDash/Database.php, app/cdash/tests/test_email.php, app/cdash/tests/test_pdoexecutelogserrors.php, phpstan-baseline.neon
This PR removes a handful of database functions which only had a few usages.  I also increased the type coverage by fixing missing and incorrect types in `Database.php`.
=> Remove low-usage database functions

app/cdash/app/Model/Project.php, app/cdash/app/Model/SubProject.php, app/cdash/include/common.php, app/cdash/public/api/v1/index.php, app/cdash/public/api/v1/viewSubProjects.php, app/cdash/public/css/common.css, app/cdash/public/views/partials/subProjectTable.html, app/cdash/public/views/viewSubProjects.html, app/cdash/tests/test_viewsubprojects.php, phpstan-baseline.neon
`viewSubProjects.php` currently shows data for the beginning of time by default if no date parameter is specified.  Most CDash pages show results from the most recent testing day by default.  This PR changes the behavior of `viewSubProjects.php` such that it now shows results for the latest testing day.
The original issue was likely a regression due to an improperly-placed negation in the relevant test.  PHPStan caught the issue, but the error was ignored as one of the pre-existing issues ignored when PHPStan was initially set up.
It is worth noting that this page creates an extraordinary number of database queries and the underlying subproject logic should be refactored to simplify these queries into a handful of larger queries.
=> Fix display of data on subprojects page

app/cdash/app/Controller/Api/QueryTests.php, app/cdash/app/Model/Build.php, app/cdash/tests/test_querytests.php
Follows https://github.com/Kitware/CDash/pull/1439.  CDash prefers the "build group" language instead of "build type". 
This PR also adds a small test to verify that the data appears in the `api/v1/queryTests.php` API response.  A similar test needs to be added to `app/cdash/tests/test_builddetails.php` eventually, but a pre-existing issue with that test needs to be resolved first.
=> Change `type` to `group` in API response

resources/js/components/EditProject.vue
The edit project page currently displays a dropdown which is offset from the rest of the page content.  The dropdown has been moved to the left to match other pages with this layout.
Before:
After:
=> Align edit project dropdown with page content

app/Http/Controllers/CoverageController.php, app/Http/Controllers/EditProjectController.php, app/Http/Controllers/ManageBannerController.php, app/Http/Controllers/ManageMeasurementsController.php, app/Http/Controllers/ProjectController.php, app/Http/Controllers/SiteController.php, app/Providers/AuthServiceProvider.php, app/Services/AuthTokenService.php, app/Services/ProjectPermissions.php, app/cdash/include/api_common.php, app/cdash/include/common.php, app/cdash/public/ajax/showtestfailuregraph.php, app/cdash/public/api/v1/createProject.php, app/cdash/public/api/v1/expectedbuild.php, app/cdash/public/api/v1/project.php, app/cdash/public/api/v1/subproject.php, app/cdash/tests/kwtest/kw_web_tester.php, phpstan-baseline.neon
This PR serves as a first step towards using Laravel gates for all authorization tasks throughout the codebase.  Having all of our gates in a centrally-located place will make it easier to determine what actions a given user can perform.
=> Use Laravel gates for project permissions checking

app/cdash/app/Model/Project.php, app/cdash/docs/NOTIFICATIONS.md, app/cdash/include/Messaging/Notification/NotificationDirector.php, app/cdash/include/Messaging/Subscription/Subscription.php, phpstan-baseline.neon, resources/views/email/fix.blade.php, resources/views/email/issue.blade.php, resources/views/email/issue/configure_errors.blade.php, resources/views/email/issue/subject.blade.php
Cleans up a bit of dead code in `Subscription.php` and adds annotations to a few other files so IDEs and static analysis tools don't mark other functions as unused.
=> Remove dead code from `Subscription.php`

app/Http/Controllers/AbstractController.php, app/Http/Controllers/BuildController.php, app/Http/Controllers/EditProjectController.php, app/Http/Controllers/ManageMeasurementsController.php, app/Http/Controllers/ProjectController.php, app/Http/Controllers/TestController.php, phpstan-baseline.neon
#1351 eliminated all usages of the `id` and `cdashCss` properties in the abstract controller, but failed to remove the properties themselves.
=> Remove unused controller properties

app/Http/Controllers/AbstractController.php, app/Http/Controllers/BuildController.php, app/Http/Controllers/EditProjectController.php, app/Http/Controllers/ManageBannerController.php, app/Http/Controllers/ManageMeasurementsController.php, app/Http/Controllers/MapController.php, app/Http/Controllers/ProjectController.php, app/Http/Controllers/TestController.php, app/Providers/AuthServiceProvider.php, phpstan-baseline.neon, resources/views/admin/measurements.blade.php, resources/views/admin/project.blade.php
We currently perform project access control checks at the top of many controller functions.  Laravel's Gate library supports authorization checking which allows us to move the duplicate access control checks to a central location.  We were also previously abusing several OOP design principles in our controller class hierarchy, which I have cleaned up as part of this refactor.  There is still a considerable amount of work left to be done to fully utilize the controller class hierarchy, but this work is a starting place from which future work can be done.
This PR directly depends upon the changes in #1419, and should be merged after #1447, #1446, and #1441 in the interest of resolving potential merge conflicts easily.
=> Refactor project controller

app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/CDash.php, app/Providers/RouteServiceProvider.php, phpstan-baseline.neon, phpstan.neon, resources/views/errors/401.blade.php, resources/views/errors/403.blade.php, resources/views/errors/404.blade.php, resources/views/errors/4xx.blade.php
We currently use Laravel's default error handlers for 4xx errors.  The default handlers do not display the exception message, so it is impossible to determine the cause of a given error.
This PR adds custom templates for 4xx HTTP errors.  5xx-category errors are logged, and there is nothing an end user can do to resolve a 5xx-category error so there is no need to display an error message.
=> Add custom error templates for 4xx errors

app/Http/Controllers/MonitorController.php, resources/js/components/Monitor.vue
#1436 revamped the system monitor page, with a new visualization of submission processing over time.  This PR adds a small snippet of text at the bottom of the page indicating where administrators can find logs so submission failures can be debugged.
=> Add help text to system monitor page

app/Services/PageTimer.php, app/cdash/tests/kwtest/kw_web_tester.php, phpstan-baseline.neon, resources/views/components/footer.blade.php, tests/TestCase.php
The `PageTimer` class is currently used in a variety of API routes to provide insight into the amount of time needed to complete a given response.  The current start time is based upon the time when the `PageTimer` class is instantiated.  This approach provides an inaccurate measure of the overall time, since the `PageTimer` object is often created after much of the request has already been completed.  In fact, some parts of the codebase execute multiple database queries before the timer gets started.  Laravel's `LARAVEL_START` constant is defined at the start of each request, and provides a more accurate request start time.
In the future, I hope to get rid of the `PageTimer` class entirely and incorporate the timing logic into a standardized API response.
=> Time entire request

app/Http/Controllers/ViewProjectsController.php, phpstan-baseline.neon, tests/Feature/CDashTest.php
The default `viewProjects.php` landing page may be confusing for some users if there are not signed in and no public projects exist.  Since the only thing the user can do anyway is navigate to the login page, this PR causes a redirect to the login page for users who are not signed in and cannot see any public projects.
=> Redirect `viewProjects.php` to login if no public projects

phpstan-baseline.neon
PHPStan is currently failing on master due to a conflict between two recently-merged PRs.  In the future, we may want to take a look at GitHub's new "Merge Queue" feature.
=> Fix failing PHPStan test

app/Http/Controllers/MapController.php, app/Http/Controllers/SubProjectController.php, app/Http/Controllers/SubscribeProjectController.php, app/Http/Middleware/Admin.php, phpstan-baseline.neon, tests/Feature/RouteAccessTest.php, tests/Traits/CreatesProjects.php
#1449 refactored a significant amount of project access control code, but a couple controllers were missed.  `MapController`, `SubProjectController`, and `SubscribeProjectController` now extend `ProjectController` and are able to take advantage of a common access control check.
=> Simplify project access control logic

resources/views/cdash.blade.php
Fixes #1467 by redirecting the user to the login page instead of including it via AngularJS.  This change will benefit from the error response standardization introduced in #1479.
=> Fix duplicate login page when rendering via AngularJS

webpack.mix.js
Laravel recommends [caching routes](https://laravel.com/docs/10.x/routing#route-caching) and [precompiling views](https://laravel.com/docs/10.x/views#optimizing-views) on production systems to maximize performance.  This PR adds route caching and view precompilation during the `mix` build. In my local testing, I observed a 3-5% speedup due to these optimizations.
=> Cache routes and views during build

app/Http/Controllers/CTestConfigurationController.php, app/cdash/tests/test_pubproject.php, resources/js/components/EditProject.vue, routes/web.php
This PR is part of an ongoing effort to refactor our routes to eliminate *.php routes and create a coherent route structure.
=> Re-route CTest configuration page

app/Http/Middleware/PasswordExpired.php, app/cdash/tests/test_edituser.php, routes/web.php, tests/Feature/PasswordRotation.php, tests/Feature/RouteAccessTest.php
This PR is part of an ongoing effort to refactor our routes to eliminate `*.php` routes and create a coherent route structure.
=> Redirect `/editUser.php` to `/profile`

app/cdash/public/views/partials/updatedfiles.html
`viewUpdate.php` currently shows update messages in plain text.  This PR changes the text formatting to the default monospaced "prepared text" styling used elsewhere for similar kinds of text.  Monospaced text is easier to read, and it's easier to differentiate between user-specified text and CDash text by styling user-specified text differently.
=> Display update messages as prepared text

app/Http/Controllers/AuthTokenController.php, routes/web.php
#1447 simplified our administrator access control code but the auth token controller was missed.
=> Clean up `AuthTokenController` access control logic

app/Http/Controllers/AbstractBuildController.php, app/Http/Controllers/AbstractProjectController.php, app/Http/Controllers/BuildController.php, app/Http/Controllers/CTestConfigurationController.php, app/Http/Controllers/EditProjectController.php, app/Http/Controllers/ManageMeasurementsController.php, app/Http/Controllers/ManageProjectRolesController.php, app/Http/Controllers/MapController.php, app/Http/Controllers/SubProjectController.php, app/Http/Controllers/SubscribeProjectController.php, app/Http/Controllers/TestController.php, app/Http/Controllers/UserStatisticsController.php
#1449 introduced a new inheritance hierarchy which allows more code to be shared between controllers.  As originally written, `BuildController` performs the role of both a regular controller with "business logic" and an abstract controller which is meant to be extended.  The issue with this approach is that extending `BuildController` drags all of the business logic into subclasses when it should be there.
This PR splits the original `BuildController` class into a new `AbstractBuildController` which is meant to be extended, and `BuildController`, which contains the business logic from the original class.  To maintain consistency with this approach, I also renamed `ProjectController` to `AbstractProjectController`.  This also groups all of the abstract controllers together when sorted …
=> Rename abstract controllers

app/cdash/app/Controller/Api/TestGraph.php, app/cdash/app/Controller/Api/Timeline.php, app/cdash/include/CDash/System.php, app/cdash/include/api_common.php, app/cdash/public/api/v1/addBuild.php, app/cdash/public/api/v1/buildProperties.php, app/cdash/public/api/v1/buildgroup.php, app/cdash/public/api/v1/computeClassifier.php, app/cdash/public/api/v1/expectedbuild.php, app/cdash/public/api/v1/manageMeasurements.php, app/cdash/public/api/v1/relateBuilds.php, app/cdash/public/api/v1/subproject.php, app/cdash/public/api/v1/testDetails.php, app/cdash/public/api/v1/testGraph.php, app/cdash/public/api/v1/viewDynamicAnalysisFile.php, phpstan-baseline.neon
#1479 introduced a centralized error-handling system which returns a JSON error message for API routes and an HTML error page for pages with content which is meant to be consumed by humans.  The recommended way to trigger the new error handling system is through Laravel's `abort()` function which throws and then catches an exception, rather than using the current `json_error_response()` function which simply returns a JSON response and then exits.  Exiting is problematic for our simpletest-based tests, because they won't catch the fact that the program exited prematurely with an error without running the remainder of the test suite.
This PR replaces most of the existing usages of `json_error_response()` with an equivalent `abort()`.  The remaining usages of `json_error_response()` are …
=> Replace `json_error_response()` with `abort()`

app/Http/Controllers/Auth/LoginController.php, app/Http/Controllers/OAuthController.php, app/cdash/public/compareCoverage.php, app/cdash/public/index.php, config/saml2.php, resources/views/components/header.blade.php, resources/views/project/view-all-projects.blade.php, routes/web.php, tests/Feature/CDashTest.php
This PR is part of an ongoing effort to refactor our routes to eliminate `*.php` routes and create a coherent route structure.
As the "front page" of CDash, this is a high traffic route so I'm open to opinions on whether this change is desired or not.
=> Redirect `/viewProjects.php` to `/projects`

app/cdash/app/Model/BuildUpdate.php, app/cdash/include/Messaging/Notification/Email/EmailBuilder.php, app/cdash/include/sendemail.php, app/cdash/tests/data/EmailProjectExample/update_error.xml, app/cdash/tests/js/e2e_tests/viewBuildError.js, app/cdash/tests/kwtest/kw_web_tester.php, app/cdash/tests/test_email.php, app/cdash/tests/test_projectwebpage.php, phpstan-baseline.neon, resources/views/email/issue.blade.php
CDash currently throws an HTTP 500 response when attempting to send an email
about errors in a submitted Update.xml file.
This PR fixes the 500 error and cleans up a variety of other small issues in the notification code.  In the future, it would be good to give the notification code a more thorough cleanup, since the current code is difficult to debug due to the lack of correct type annotations, complex inheritance hierarchy, and large amounts of dead code.
Fixes https://github.com/Kitware/CDash/issues/1498
=> Fix email sent for errors in Update.xml

app/cdash/tests/kwtest/kw_web_tester.php, resources/js/components/page-header/HeaderNav.vue, resources/views/components/header.blade.php
#1351 refactored the top nav bar but failed to cover all the possible cases, meaning that the menu on the right side could show up on the left side if the center nav was not visible.  This PR simplifies the code significantly to reduce the number of cases which have to be covered.
Before:
After:
=> Push menu to right side on all pages

routes/web.php
Re-create the POST route for the getCoverage file which will re-enable the filtering of the coverage files.
Fixes: #1518
=> Fix 404 when filtering coverage display

app/cdash/include/repository.php, resources/views/build/update.blade.php
When a project does not have a repository URL specified, various places on the UI display the url `http(s)://&<hash>`.  One particular place this is displayed is at the top of `viewUpdate.php`.  The current "URL" is totally meaningless of course, and it would be better to not attempt to provide a URL at all unless one is set for the project.
=> Improve revision URL handling when no repository specified

app/cdash/include/common.php, phpstan-baseline.neon
#1510 removed the last reference to the `checkUserPolicy()` function.  Gates are now the preferred access control method, so `checkUserPolicy()` has been eliminated.
=> Delete unused `checkUserPolicy()` function

app/cdash/public/api/v1/addBuild.php
The endpoint `/api/v1/addBuild.php` was first added in #694, but is no longer used in the CDash codebase.  Since this endpoint may be used by external scripts, it has been deprecated temporarily and will be removed entirely in a future release.
It would also be good to provide a notice about this deprecation in the CDash 3.2 release notes.
=> Deprecate `addBuild.php` API endpoint

app/cdash/public/api/v1/testSummary.php, phpstan-baseline.neon
The API endpoint for `testSummary.php` currently returns a 500 error when there are no rows to be displayed.  This endpoint has other significant issues and desperately needs a complete refactor, but this PR should at least make it return a sensible response given a realistic input.
=> Fix test summary error when no results

app/cdash/public/views/viewDynamicAnalysis.html
The dynamic analysis UI was apparently missed during the most recent UI refactor and now sticks out like a sore thumb compared to the rest of the CDash interface.  This PR applies the same styling other CDash tables use for greater UI consistency.
Before:
After:
=> Refactor dynamic analysis UI

app/cdash/include/common.php
#1432 added a suboptimal query which is too slow on production systems.  This PR works around the slow part of the query by using far more restrictive conditions, which should improve performance significantly.
=> Improve build deletion query performance

app/Console/Commands/PurgeUnusedProjects.php, app/cdash/tests/CMakeLists.txt, tests/Feature/PurgeUnusedProjectsCommand.php
CDash instances such as [my.cdash.org](https://my.cdash.org) which allow any user to create a project can accumulate a large number of stale projects which have no recent builds or activity and are otherwise just taking up space.
This PR introduces a new `projects:clean` Artisan command which automatically deletes any projects which have no builds associated with them.
=> Add stale project cleanup Artisan command

routes/web.php
This PR fixes a bug on `buildOverview.php` where the group selection dropdown was unusable since the corresponding POST request was not being accepted.
=> Accept POST route for `buildOverview.php`

resources/js/components/TestDetails.vue
The test details command line is currently displayed in regular text, which can be difficult to read when it consists of a long string of symbols.  This PR changes the UI to match other parts of the codebase in which text of this nature is displayed as prepared text in a monospace font.
=> Display test details command line in monospace font

app/Http/Controllers/CoverageController.php, app/Models/Coverage.php, app/cdash/app/Model/Coverage.php, app/cdash/app/Model/CoverageFile.php, app/cdash/app/Model/CoverageSummary.php, app/cdash/public/viewCoverage.xsl, database/migrations/2023_06_29_210505_coverage_primary_key.php, phpstan-baseline.neon
This PR serves as a trial run of my new approach regarding the modernization of large models for which is is infeasible to replace the model entirely.  Rather than taking the reflection approach used for the `User` classes, I have instead taken an "adapter" approach, such that the public-facing interface of the original `Coverage` class has not changed, but all of the database interactions happen through the public-facing interface of the new eloquent-based `Coverage` class.
=> Refactor `Coverage` model

app/cdash/app/Controller/Api/QueryTests.php, app/cdash/app/Controller/Api/TestDetails.php, app/cdash/app/Controller/Api/ViewNotes.php, app/cdash/app/Controller/Api/ViewTest.php, app/cdash/public/api/v1/buildSummary.php, app/cdash/public/api/v1/overview.php, app/cdash/public/api/v1/testSummary.php, app/cdash/tests/data/BuildDetails/InsightExperimentalExample_Expected.json
#1351 created a standardized page title system, but failed to update a handful of the page titles which are set via an API response instead of a Blade template.  The ultimate goal of course is to set the page title in some sort of centralized location, but that work will occur at a later point.  In the meantime, this PR fixes all of the issues for the moment so the 3.2 release at least ships with something reasonable.
=> Standardize page titles

app/cdash/public/css/common.css, resources/views/test/view-test.blade.php
The build information table on `viewTests.php` currently has poor formatting.  This PR applies the table styling used elsewhere throughout CDash to this table to make it more readable.  In the future, it would be a good idea to more thoughtfully design this page as a whole.
Before:
After:
=> Revamp `viewTest.php` build information table

app/Http/Controllers/SiteController.php
Fixes #1560.
It's worth noting that the edit site page as a whole is in desperate need of an overhaul and I plan to refactor it sometime soon.  This PR only attempts to fix the error noted in #1560, and does not make an attempt to fix all outstanding issues with this page.
=> Fix `editSite.php` error when no sites claimed

app/Rules/LdapFilterRules.php
As of PHP 8.1.0, the return value of ldap_search() is no longer a resource.
=> Fix broken `LDAP_FILTERS_ON` functionality

resources/js/components/BuildSummary.vue
The build history table on `/build/<buildid>` currently lacks padding which makes it look unpolished.  This PR applies the same styling used for the "current build" table to the build history table.  The header of the table and the "History" banner are now the same color though, which could probably be cleaned up in the future.  In fact, a light UI refresh for the entire page should probably happen eventually since there is a lot of wasted space and confusing UI elements.
Before:
After:
=> Reformat build history table

app/cdash/public/views/overview.html
`overview.php` is currently unusable due to various UI components overlapping with one another.  This PR reformats the page so all of the available information is visible.  There are still a number of other issues with generating the data for this page on the server side, but they don't directly relate to the UI issues fixed here and will be addressed in separate PRs.
Before:
After:
=> Refactor `overview.php` UI

docker/docker-compose.mysql.yml
We currently have MySQL 5.7 listed as the default version of MySQL when deploying via Docker.  MySQL 5.7 will no longer be supported beyond October 2023, and our flagship [open.cdash.org](https://open.cdash.org) instance has been running MySQL 8.x for some time.  
Fixes #1409.
=> Bump default MySQL version to 8.0

app/cdash/public/css/common.css, resources/views/coverage/ajax-coverage-graph.blade.php
To eliminate an error where the Lines Of Code data attempted to access a non-existant yaxis object, remove the plots for LOC from the coverage over time display.
With an update to the design, they may be reintroduced by switching to `yaxes` in the plot's `options` object and then reintroducing the data.
Previous State:
Current State:
=> Remove LOC displays from coverage graph

database/migrations/2023_07_14_151406_build2test_index.php
The `build2test` table is a pivot table which is used to relate builds and tests.  The most common use case involves joining the `build2test` table with the `build` and `test` tables via its `testid` and `buildid` columns.  Each individual column in the `build2test` table is indexed, but using any relation between testids and buildids requires the database to load the entire `build2test` row.  This is the primary cause of the widespread slowness on the test summary page, amongst other things.
I have added indices on `(buildid,testid)` and `(testid,buildid)`.  During a trial run on a large development database, I observed a significant speedup on `testSummary.php`, going from 60+ seconds to less than one for an average page load.  Due to the size of the `build2test` table, CDash …
=> Index `(testid,buildid)` pairs in `build2test` table

app/cdash/app/Model/BuildError.php, app/cdash/app/Model/BuildFailure.php, app/cdash/app/Model/BuildGroup.php, app/cdash/app/Model/BuildUpdate.php, app/cdash/app/Model/BuildUpdateFile.php, app/cdash/app/Model/Coverage.php, app/cdash/app/Model/CoverageFile.php, app/cdash/app/Model/CoverageFile2User.php, app/cdash/app/Model/CoverageSummary.php, app/cdash/app/Model/DailyUpdate.php, app/cdash/app/Model/DynamicAnalysis.php, app/cdash/app/Model/DynamicAnalysisDefect.php, app/cdash/app/Model/LabelEmail.php, app/cdash/app/Model/SubProjectGroup.php, app/cdash/app/Model/UserProject.php, phpstan-baseline.neon
As we gradually move the codebase to Laravel, we want to control all output through Laravel alone.  A common pattern throughout the CDash codebase is the usage of the echo command to output error messages, which unintentionally conflicts with other output such as JSON output in an API response.  Furthermore, these error cases are not logged, so CDash administrators are not automatically alerted if users are repeatedly experiencing an error.
In this PR, I have switched all of the echoed error messages to thrown exceptions via Laravel's `abort()` helper.  These exceptions will show up in the logs (if configured), and the exceptions will be forced through the same centralized error handling system for greater consistency across pages.
=> Convert echoed error messages to thrown exceptions in models

app/Http/Controllers/BuildController.php
This PR fixes an issue on `viewBuildError.php` where the negative delta case was broken.
=> Fix `onlydeltan` case on build error page

app/Http/Controllers/CDash.php, phpstan-baseline.neon
`CDash.php` was originally created as a compatibility layer between Laravel and pre-Laravel routes.  Now that I have moved all of the non-API routes to Laravel's routing scheme, much of `CDash.php` is no longer necessary, and has been deleted in this PR.  This PR also eliminates several avenues for potential security vulnerabilities.
=> Remove obsolete request handling logic

app/cdash/public/js/controllers/index.js, app/cdash/public/views/index.html, app/cdash/public/views/partials/build.html
The index page is currently unacceptably slow for large projects due to a large rendering delay.  On large dashboards such as the VTK dashboard, AngularJS takes in excess of 5 seconds to render once it receives a response from the API.
The render delay itself is an unavoidable limitation of AngularJS, but it's possible to hide some of it by prioritizing content at the top of the page.  By rendering one build group at a time, we can put content in front of the user's eyes faster than if it was all rendered at once.
Although the total render time is still roughly the same, this PR drops the time before a user sees the first build group from 5 seconds to 1.5 seconds on the VTK dashboard.  Since the user is unlikely to begin navigating the page before the other build groups render, the page …
=> Render build groups one at a time on index page

app/cdash/public/css/common.css, resources/js/components/BuildSummary.vue
This UI-only change updates the build summary UI to the latest table style and improves the readability of the build information which was previously unformatted.
Before:
After:
=> Update build summary table UI

app/cdash/public/viewSubProjectDependenciesGraph.xsl
This PR fixes a small UI issue on the subproject dependency graph page when a project is not assigned a group.  This page needs a significant overhaul eventually, but I will defer that until sometime in the future.
Example of error:
=> Don't attempt to display group if no group defined

app/cdash/public/api/v1/buildgroup.php, app/cdash/tests/js/e2e_tests/manageBuildGroup.js
When creating a new buildgroup using the manageBuildGroup.php page, CDash would reply:
A group named '\<new group name\>' already exists for this project.
This error message was displayed despite the fact that the new group actually was created successfully.
=> Fix erroneous message upon creating new buildgroup

app/Http/Controllers/ProjectController.php, app/Providers/AuthServiceProvider.php, app/cdash/tests/test_createprojectpermissions.php, config/cdash.php
Use the config singleton to properly query the value of USER_CREATE_PROJECTS when checking for permission at the creation of projects.
Fixes: #1602
=> Properly query the USER_CREATE_PROJECTS variable

app/cdash/public/views/partials/subProjectTable.html
The link to each subproject in the subprojects table when viewing one of the subprojects is currently missing a date parameter.  This PR fixes the date parameter, using the same data source used on `viewSubProjects.php`.
=> Fix links to subprojects in subprojects table

app/Http/Controllers/MonitorController.php, resources/js/components/Monitor.vue
Instead show stats for all successful & failed jobs within CDash's backup timeframe.
=> Remove hardcoded 24 hour contraint for /monitor

.env.example, app/Jobs/ProcessSubmission.php, app/Models/Site.php, app/cdash/app/Model/Build.php, app/cdash/public/api/v1/requeueSubmissionFile.php, app/cdash/tests/test_donehandler.php, app/cdash/xml_handlers/retry_handler.php, config/cdash.php, config/queue.php, phpstan-baseline.neon
After the recent upgrade of open.cdash.org, we noticed many builds were no longer marked as "Done". This was due to the Done.xml handler exhausting its 5 retries while a single large Test.xml file was in the process of being parsed.
We solve this problem by exponentially backing off the requeueing of Done.xml files to give CDash more time to finish parsing any such large XML files for a given build.
Fixes #1603
This PR also contains a couple other semi-related fixes dealing with parallel parsing of submission files.
=> Use exponential backoff when requeueing Done.xml files

app/Services/TestCreator.php, app/cdash/tests/test_buildproperties.php, app/cdash/tests/test_removebuilds.php, app/cdash/xml_handlers/BazelJSON_handler.php, app/cdash/xml_handlers/testing_handler.php, app/cdash/xml_handlers/testing_junit_handler.php
This fixes unique key constraint violations we were noticing on open.cdash.org for tests whose names are longer than this limit.
=> Truncate test names to 255 characters

app/Http/Controllers/CoverageController.php, app/cdash/app/Model/CoverageFile2User.php, phpstan-baseline.neon
When there are no users linked to a project coverage file, the GetUsersFromProject function returns false, assuming that an empty query_result means an error.  Returning false created a 500 error when the caller function attempted to loop over the return.
Change the function to use Laravel's query system and eliminate the places where boolean values were returned.
=> Change GetUsersFromProject to only return arrays

app/cdash/xml_handlers/note_handler.php
We've noticed tons of entries for this log message on open.cdash.org. They stem from projects that choose to upload lots of logs for their builds, some of which happen to be empty.
Since this is ultimately a client-side issue, demote the severity of this log entry from 'error' to 'info' so as to make them easier to filter out on the server side.
=> Demote severity of 'No note text' to info

app/Console/Commands/AutoRemoveBuilds.php, app/Http/Controllers/UserController.php, app/cdash/app/Model/Project.php, app/cdash/include/autoremove.php, phpstan-baseline.neon
The query parameter for the limit clause in one of the build autoremoval scripts is currently being passed to the database as a string.  This is problematic, and prints the following message to the logs:
`production.ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''500'' at line 9`
MySQL does a limited amount of type conversion, but does not extend the type conversion to limit clauses.  By passing the query parameter as an integer, the problem will be resolved.
I also addressed the only other case of this type of bug, even though it's not directly related to the bug report per se.
This PR is a good example of why passing numeric strings around is a bad idea...
=> Treat autoremove builds query parameter as integer

app/Http/Controllers/AdminController.php
This table was removed in #1258, but we accidentally retained a reference to it in the admin-only "Cleanup database" functionality.
=> Remove lingering reference to defunct submission table

app/Http/Controllers/AbstractController.php, app/Providers/AppServiceProvider.php
#1621 reduced the number of repetitive `require_once` commands, but made the faulty assumption that the global functions being included were not necessary in any of the middleware.  A more appropriate spot for these includes is Laravel's `AppServiceProvider`, which runs before the middleware does, and is generally the place to change global settings.
Fixes #1630.
=> Move include of global functions to `AppServiceProvider`

routes/web.php
Using the proper HTTP code helps browsers preload the correct destination after the first request, which improves page load times slightly on most browsers.
=> Use 301 HTTP code for permanent redirects

docker/cdash.docker
On systems where the user is not the default `www-data` user, the installation process may fail with the message `fatal: detected dubious ownership in repository`.
As a workaround, this PR simply disables the `safe.directory` Git configuration setting globally.
=> Disable git repo ownership check

app/Http/Controllers/AbstractBuildController.php, app/Http/Controllers/FilterController.php
The `FilterController` class was created before https://github.com/Kitware/CDash/pull/1587 was merged, and is thus missing the `final` designation.
`AbstractBuildController ` was missed amidst some logical conflicts when previous PRs were merged and has been designated as `abstract`.
In the future, it might be interesting to create a PHPStan plugin which ensures that all future controllers follow our naming and designation conventions.
=> Add missing final/abstract keywords

app/Http/Controllers/MapController.php, app/cdash/public/viewMap.xsl
`viewMap.php` currently handles missing data poorly, displaying nonsensical values whenever the expected data is not present.
Before:
After:
=> Improve site map handling of missing data

.circleci/config.yml
This commit updates our CircleCI configuration to build git tags. When doing so, it will push a correspondingly tagged image to Docker Hub.
=> Update CircleCI to push more tags to Docker Hub

app/Http/Controllers/AbstractBuildController.php, app/Http/Controllers/AbstractController.php, app/Http/Controllers/AbstractProjectController.php, app/Http/Controllers/AdminController.php, app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/BuildController.php, app/Http/Controllers/CTestConfigurationController.php, app/Http/Controllers/EditProjectController.php, app/Http/Controllers/ManageBannerController.php, app/Http/Controllers/ManageMeasurementsController.php, app/Http/Controllers/ManageProjectRolesController.php, app/Http/Controllers/MapController.php, app/Http/Controllers/SiteController.php, app/Http/Controllers/SubscribeProjectController.php, app/Http/Controllers/UserController.php, app/Http/Controllers/ViewProjectsController.php, app/Http/Controllers/ViewTestController.php, phpstan-baseline.neon
We currently have a handful of things which get added to almost every view.  By adding a custom `view()` function in this PR, we can share more code and reduce the number of locations which have to get updated if the need for more "common" data arises.
I skipped over a few controllers which need more extensive work when making these changes, and will fix those in a separate PR.
=> Add `view()` function to controllers

app/Models/Ldap/User.php, app/cdash/include/Messaging/Notification/Email/EmailBuilder.php, app/cdash/include/Messaging/Topic/FixedTopic.php, phpstan-baseline.neon, phpstan.neon
PHPStan offers a set of "bleeding edge" rules which are the stable rules which will be added in the next major release.  We already use many of these rules through our usage of various optional packages, but there's no reason to not turn on additional static analysis rules.  The only major difference between bleeding edge and our current setup is that bleeding edge mandates usage of the strict equality (`===` and `!==`) operators.  We already use the optional exception-checking rules which are included in bleeding edge.
In addition to adding the bleeding edge rules, I have also enabled two more optional rules which are not included in any of our optional packages.
=> Turn on PHPStan "bleeding edge"
