Kitware/CDash

app/Http/Controllers/AdminController.php
app/Http/Controllers/CoverageController.php
app/Http/Controllers/ManageProjectRolesController.php
app/Http/Controllers/ProjectController.php
app/Http/Controllers/ProjectOverviewController.php
app/Http/Controllers/SubProjectController.php
app/Models/Project.php
app/cdash/app/Model/BuildUpdateFile.php
app/cdash/app/Model/Project.php
app/cdash/include/ctestparser.php
app/cdash/include/dailyupdates.php
app/cdash/public/api/v1/project.php
app/cdash/tests/test_compressedtest.php
app/cdash/tests/test_projectmodel.php
database/migrations/2023_07_07_143440_delete_projectrobot_table.php
phpstan-baseline.neon
resources/js/components/EditProject.vue

The `Project` model is one of the largest models in the CDash codebase, and it would be completely impractical to convert the entire thing to Eloquent at one time.  Instead, I have taken an "adapter" approach similar to the approach taken in #1539, in which the public-facing interface of the old project class remains (mostly) the same, while the business logic of most methods is outsourced to the new Eloquent-based project model.
In addition to switching the code to use the Eloquent-based project when possible, I have also undertaken a general refactor of the model, deleting unused code, simplifying parameters and return types, converting all database queries to Laravel's query system, and other general maintenance tasks.
I have also completely eliminated the `projectrobot` table and …

Migrate backend of `Project` model to Eloquent

---

.rsyncignore
docker/cdash.docker
docker/docker-compose.dev.yml

The developer experience is currently rather poor for developers using our Docker environment.  Without custom patches, the only way to test new code changes is to rebuild the image and start a new container.
Given that we now have separate production and development configurations, I thought it might be helpful to upstream an installation patch I have been using locally for some time.  The source code directory is mounted as a read-only volume in `/cdash_src`, and the `cdash_install` alias runs a script which copies new code changes into the `/cdash` directory.  This is particularly useful when paired with a separate terminal session running `npm run watch-poll`, which automatically compiles all of our static assets with mix whenever new changes are made.
The alternative to this approach …

Add install step for developers

---

app/cdash/include/Test/UseCase/TestUseCase.php
app/cdash/tests/case/CDash/MultipleSubprojectsEmailTest.php
app/cdash/tests/case/CDash/TestUseCaseTest.php
app/cdash/tests/test_buildmodel.php
app/cdash/tests/test_upgrade.php
app/cdash/xml_handlers/testing_handler.php
database/migrations/2023_07_20_185727_project_foreign_keys.php
phpstan-baseline.neon
tests/Feature/MeasurementPositionMigration.php

Our database schema is currently a mess.  With no foreign keys defined, it is easy to accidentally forget to update a relationship field properly when an entity is created or deleted.  Virtually all modern relational databases support foreign key constraints, and there is no reason for us to not add them.
In a first step towards #1442, this PR adds foreign key constraints to all of the table columns which reference a project's ID.  This should be a relatively low risk operation for production systems, but it creates a bit of a headache when writing tests, because creating any model which references a project necessarily requires a project model to be created as well.

Add foreign key constraints for all projectids

---

app/cdash/include/Collection/Collection.php
phpstan-baseline.neon
phpstan.neon

The `Collection` class was ignored when I first set up PHPStan.  By specifying a few function return types, I was able to get PHPStan to successfully analyze the `Collection` class.

Enable PHPStan analysis of `Collection.php`

---

app/cdash/tests/case/CDash/MultipleSubprojectsEmailTest.php
app/cdash/tests/case/CDash/TestUseCaseTest.php
app/cdash/tests/test_uniquediffs.php
database/migrations/2023_08_14_205552_build_foreign_keys.php
phpstan-baseline.neon

This PR builds upon the work in #1655, and adds foreign key constraints to all buildid columns.  Like #1655, a handful of changes to our test suite were required to ensure that the constraints were fully met during the testing process.
This is related to issue #1442.

Add foreign key constraints for all buildids

---

.env.example
app/Http/Controllers/UserController.php
app/cdash/app/Model/Project.php
app/cdash/config/config.php

Finish the replacement of the query for CDASH_USER_CREATE_PROJECTS environment variable with the checking of the config singleton.
With the UserController transition, the link for project creation will appear for each user when the variable is set.
All project creation by users is controlled by the `.env` variable USER_CREATE_PROJECTS.
Finishes work started in  #1604

Finish transition from CDASH_USER_CREATE_PROJECTS

---

app/Http/Controllers/BuildController.php
app/cdash/public/views/viewBuildError.html
resources/js/components/BuildConfigure.vue
resources/views/test/view-test.blade.php
tests/Spec/build-configure.spec.js

The build start time has been added to the info table at the top of `viewConfigure.php` and `viewTest.php`.
I will add Cypress tests for the angular-based pages once I get Cypress set up.

Display build start time on `viewConfigure.php` and `viewTest.php`

---

app/Http/Controllers/BuildController.php
app/Models/BuildError.php
app/cdash/app/Model/BuildError.php
app/cdash/tests/case/CDash/Model/BuildErrorTest.php
database/migrations/2023_08_22_125134_builderror_primary_key.php
phpstan-baseline.neon

All database queries in the legacy `BuildError` model are handled by a new Eloquent `BuildError` model.  Since the eloquent isn't a 1:1 swap for the legacy model, I have turned the legacy model into an adapter for the new Eloquent model.  Future usages of the `BuildError` model should use the new Eloquent model if possible.

Migrate backend of `BuildError` model to Eloquent

---

docker/cdash.docker

The latest "stable" Debian version is Debian bookworm, [released](https://www.debian.org/News/2023/20230722) on July 22, 2023.  I have bumped our base Docker image to a bookworm-based image.

Bump default Debian version from bullseye to bookworm in Docker

---

app/cdash/app/Model/Build.php
app/cdash/app/Model/BuildError.php
app/cdash/include/ctestparserutils.php
app/cdash/include/pdo.php
app/cdash/tests/test_buildmodel.php
app/cdash/tests/test_donehandler.php
app/cdash/tests/test_removebuilds.php
app/cdash/xml_handlers/BazelJSON_handler.php
app/cdash/xml_handlers/build_handler.php
app/cdash/xml_handlers/configure_handler.php
app/cdash/xml_handlers/testing_handler.php
phpstan-baseline.neon

We eventually want to convert all of the models to Eloquent.  The `Build` model is the largest, and most complicated, model in the CDash codebase, and it is not feasible to simply swap it out for an Eloquent-based model.  In preparation for a gradual conversion to an Eloquent backend via the adapter pattern used in #1556, I have tightened the parameter and return type constraints on the legacy Build model wherever possible.  By ensuring that all of the parameter and return types are known, the process of converting individual methods to Eloquent equivalents will be easier and less bug prone.
While the automated test suite passes, and I didn't see any issues during some manual testing, it is quite possible that bugs associated with this PR will pop up.  By opening this PR early in the …

Clean up `Build` model

---

app/Http/Controllers/BuildController.php

I forgot to wrap a query parameter in an array in https://github.com/Kitware/CDash/pull/1550.
Thanks to @sbelsk for spotting this bug!

Fix typo in `getPreviousBuilds.php` API endpoint

---

docker/cdash.docker

The nodejs installation script we currently use is [deprecated](https://github.com/nodesource/distributions?tab=readme-ov-file#new-update-%EF%B8%8F), and results in a warning message when building our docker image.  The install process has been updated to reflect the current nodesource recommendations.
I also bumped nodejs to version 20.x.  This change should not affect our codebase.

Change nodejs install command

---

app/cdash/public/api/v1/buildgroup.php
phpstan-baseline.neon

The GET method for the endpoint `/api/v1/buildgroup.php` is currently broken, and is not used anywhere in the codebase.  I plan to refactor this entire file eventually, but I'm waiting for #1666 to be fixed and merged before doing so.

Delete unused `buildgroup.php` GET endpoint

---

phpstan-baseline.neon
phpstan.neon

In many cases, we deliberately want a request to crash and trigger the error handler when an unexpected unrecoverable situation occurs.  When PHPStan was first set up, the list of unchecked exceptions was kept to a minimum to allow us to decide which exceptions should be checked and which should be unchecked.  After working with it for a few months, it's clear that a few more exception types need to be added.
It is possible that more exception types will need to be added to this list in the future.  The goal is for PHPStan to be a useful tool which flags problems like division by zero exceptions, so they can be dealt with without crashing an entire request.

PHPStan: Add additional unchecked exceptions

---

app/Models/BuildProperties.php
app/cdash/app/Model/BuildProperties.php
app/cdash/xml_handlers/BuildPropertiesJSON_handler.php
phpstan-baseline.neon

This PR is part of our ongoing effort to migrate our models to Laravel's Eloquent ORM library.
As noted in a comment, we should eventually consider whether the `buildproperties` table should simply be a column on the `build` table , given that it has a one-to-one relationship with a corresponding build.  Performing such a refactor should be relatively straightforward.

Migrate `BuildProperties` model backend to Eloquent

---

composer.json
composer.lock

The `random_compat` polyfill is used to port a handful of functions introduced in PHP 7 to PHP 5.  Since we do not support PHP 5, we don't need this dependency.
I have removed `random_compat` from our `composer.json`, but it is still a required dependency for `league/oauth2-client` and is still in our lock file.

Drop unused `random_compat` polyfill

---

app/Jobs/ProcessSubmission.php

We only log the filename for failing submissions currently, and information about *why* a submission failed is lost.
This PR adds the specific error message to the logging statement.

Add additional information to failed submission log message

---

app/Http/Controllers/AbstractController.php
app/cdash/include/CDash/Config.php
app/cdash/include/common.php
phpstan-baseline.neon
resources/views/cdash.blade.php
resources/views/components/footer.blade.php

Everything the legacy `Config` class does can be done by an equivalent Laravel helper function.  As such, there is no longer a need for the `Config` class, and it has been marked as deprecated.  I tried to simply replace each of the deprecated functions with laravel equivalents, but a few quirks with our testing suite make it a nontrivial task.
I created a new function for getting the current CDash version in the base controller class.  This is now the preferred method to use for getting the version.  I intend to make a separate PR once this is merged to simplify our versioning logic.

Deprecate legacy `Config` class

---

app/Models/Project.php
app/Models/SubProject.php
app/cdash/app/Model/SubProject.php
app/cdash/public/api/v1/index.php
app/cdash/public/api/v1/subproject.php
app/cdash/xml_handlers/BazelJSON_handler.php
phpstan-baseline.neon

This PR is part of our ongoing effort to switch all of our models to Laravel's Eloquent ORM library.  The legacy `SubProject` model has been turned into an adapter for the Eloquent-based model, using the same approach taken in #1556.

Convert backend of `SubProject` model to Eloquent

---

app/Models/Build.php
app/cdash/app/Model/Build.php
app/cdash/include/pdo.php
app/cdash/public/api/v1/build.php
app/cdash/tests/test_donehandler.php
app/cdash/xml_handlers/done_handler.php
phpstan-baseline.neon

This PR follows #1674 and converts the parts of the `Build` model which interact directly with the `build` table to Eloquent wherever feasible.  I intend to slowly switch more parts of the codebase to the Eloquent-based model, but that work will happen in separate PRs.  By simply having an Eloquent `Build` model present, we can do significantly more in other Eloquent models.

Convert backend of `Build` model to Eloquent

---

app/Http/Controllers/ManageMeasurementsController.php
app/Models/Measurement.php
app/Models/Project.php
app/cdash/app/Controller/Api/QueryTests.php
app/cdash/app/Controller/Api/TestDetails.php
app/cdash/app/Controller/Api/ViewTest.php
app/cdash/public/api/v1/index.php
app/cdash/tests/test_managemeasurements.php
phpstan-baseline.neon

This PR adds Eloquent relationship information to the existing `Measurement` model, and converts a number of raw database queries to Eloquent queries.

Access `Measurement` model through relationship with `Project`

---

app/Models/Project.php
app/cdash/app/Model/Project.php
database/migrations/2023_09_18_190517_drop_webapikey_column.php
phpstan-baseline.neon
resources/js/components/EditProject.vue

The project web API key feature has not been used for some time, and there is no longer a way to access data in the database if it is added during the project creation process.
All remaining references to the web API key feature have been eliminated.

Remove unused project webapikey field

---

resources/views/project/ctest-configuration.blade.php

Recreate the variables used in the older method of building the submit site for a CDash submission.  Hide these variables behind a proper version check, as the new style of "CTEST_SUBMIT_URL" was introduced in version 3.14
Fixes #1714

Re-enable CTEST_DROP_* information for older CTests

---

app/Models/TestMeasurement.php
app/cdash/app/Controller/Api/QueryTests.php
phpstan-baseline.neon

`queryTests.php` currently executes a query to check for test measurements for each row in the table.  This contributes to the slowness observed on this page for bigger projects.
The offensive query has been moved outside the loop and now only runs a larger aggregate query once.

`queryTests.php`: Optimize testmeasurement query

---

app/Services/AuthTokenService.php

Authentication tokens currently only contain 128 bits of entropy.  This PR increases the entropy to 512 bits, which is the maximum value we can use without changing the hashing algorithm.  If we limit the available character set to the 62 upper- and lower-case alphanumeric characters, 86 characters are necessary to exceed 512 bits of entropy, assuming my calculations are correct.

Increase token length from 128 bits to 512 bits

---

phpstan-baseline.neon
phpstan.neon

PHPStan provides a set of [rule levels](https://phpstan.org/user-guide/rule-levels) which provide increasingly strict code analysis.  We currently use level 6.
PHPStan level 8 checks nullable types in greater detail, which will prevent a few common types of bugs, including the one fixed in #1725.  I was forced to also turn on level 7.  Level 7 checks union types, which will significantly improve our error detection abilities, but comes with the caveat that checking for all of the error cases for functions which return false instead of throwing an exception will cause additional developer overhead.
Eventually, we should turn on level 9, but it would be pointless to do so without turning on `treatPhpDocTypesAsCertain`.  PHPStan cannot currently understand Laravel's type casting system, …

Bump PHPStan to level 8

---

app/cdash/xml_handlers/abstract_handler.php
app/cdash/xml_handlers/update_handler.php
phpstan-baseline.neon

The update handler currently fails when a submission with a blank `<site>` tag is present.
If a blank site tag is included in an update XML file, CDash will now ignore it gracefully.

Update handler: Ignore empty site field

---

app/Http/Controllers/AdminController.php
app/Http/Controllers/ManageProjectRolesController.php
app/Http/Controllers/SiteController.php
app/cdash/app/Controller/Api/QueryTests.php
app/cdash/app/Controller/Api/ViewTest.php
app/cdash/include/filterdataFunctions.php
app/cdash/include/pdo.php
app/cdash/public/api/v1/buildgroup.php
app/cdash/public/api/v1/expectedbuild.php
app/cdash/public/api/v1/manageOverview.php
app/cdash/public/api/v1/subproject.php
app/cdash/public/api/v1/testGraph.php
phpstan-baseline.neon

Integers are always safe to insert in SQL queries.  Thus, we can eliminate the `pdo_real_escape_numeric()` function and replace all of the existing usages with integer casts.  In the vast majority of cases, this function was no longer being used to sanitize values for SQL queries anyway.

Eliminate `pdo_real_escape_numeric()` function

---

app/cdash/public/css/d3.dependencyedgebundling.css
resources/views/project/subproject-dependencies.blade.php

Currently, when loading the SubProject Dependencies page for a given project, depending on the number of subprojects and the length of their names, the rendering of the graph may overlap the text on the page. 
Additionally, when hovering on top of nodes in the graph, the following error is printed to the console:
The graph will never overlap the text on the page anymore, and it set to be rendered on the center of the page. The console error is fixed and the tooltip now displays properly (the tiny white triangle connected to the textbox that pops up on hover).

Fix subproject dependency graph rendering

---

app/Http/Controllers/BuildController.php

Fixes https://github.com/Kitware/CDash/issues/1748
This resolves a bug that was introduced in https://github.com/Kitware/CDash/pull/1561, and also adds a missing check for the `CURRENT` navigation button.

Fix broken navigation links on `Build Files Updated` page

---

resources/js/components/page-header/HeaderNav.vue
resources/views/components/header.blade.php

The navigation menu in the middle of the header menu is confusing, because the "current" option takes the user to the most recent change, while the "prev" and "next" options allow the user to navigate through items one at a time.  I changed the text from "current" to "latest" to better reflect the action being performed, but I decided not to update the underlying code to avoid breaking the API.  I would like to hear any feedback reviewers have regarding this decision.
After the change:

Rename central menu item from "current" to "latest"

---

routes/web.php

Prior to this commit, when CDash is deployed in a subdirectory like so:
http://mydomain.com/cdash
Navigating to this base-level URL would cause CDash to respond with "The requested page does not exist".

Fix base-level redirect for CDash-in-a-subdir 

---

phpstan-baseline.neon
phpstan.neon

This option extends the rules added in #1726 to be more strict about reporting potential type incompatibilities.  Form more information, please refer to the [documentation](https://phpstan.org/config-reference#checkbenevolentuniontypes).

Enable PHPStan `checkBenevolentUnionTypes` rule

---

app/Http/Controllers/UserController.php
app/Models/Build.php
app/Models/Project.php
app/cdash/app/Model/Project.php
phpstan-baseline.neon

This PR introduces Eloquent relationships between the `Project` model and the `Build` model.
I used the new relationships to replace a few existing SQL queries in the legacy project model as examples, but by no means did I attempt to locate and refactor every possible place where the relationships can be used.  I expect to gradually use them more through my work in other PRs.

Set up Project<->Build Eloquent relationship

---

resources/js/components/ViewDynamicAnalysis.vue

Add in a `/` to properly form the URL for a link to a specific dynamic analysis file from the listing page.
Fixes: #1759

Add missing slash for URL in Dynamic Analysis

---

app/Http/Controllers/AbstractController.php
app/Providers/AppServiceProvider.php

Pages rendered by AngularJS which require authentication currently redirect to the index page after login.  This is inconsistent with the behavior elsewhere, where the user is redirected back to the page they attempted to access prior to being redirected to the login page.
This PR is a temporary patch to make the login redirect behavior more consistent.  The ultimate goal is to remove AngularJS entirely.

Fix Angular routing behavior after login

---

app/Models/User.php

The User model now has type annotations which allow IDEs to infer which properties are available.
This PR was originally a portion of #1742, and has been split into a separate PR to get the changes merged more quickly.

Add type annotations to user model

---

docs/submissions.md

Recommend that we specify `Restart=always` so that the queue worker restarts automatically even if it exits "cleanly".
Also recommend max-time=3600 to periodically restart the queue worker.

Update example systemd unit

---

README.md

The testing information in our `README.md` is no longer relevant and directs users to a page which was last updated in 2017.

Delete outdated testing info from README

---

app/cdash/public/js/controllers/viewProjects.js
resources/js/app.js
resources/js/components/AllProjects.vue
resources/views/project/view-all-projects.blade.php
tests/Feature/CDashTest.php

The client-side rendering engine has been changed from AngularJS to Vue for the `/projects` route.  In the future, it would be good to refactor this page to be more dynamic.

Switch frontend of `/projects` to Vue

---

docker/cdash.docker
php.ini

Our PHP configuration file is currently located inside the old part of the codebase.  This PR moves it to the top level directory where it is more noticeable.  I also eliminated outdated Google App Engine settings.

Move `php.ini` to outer directory

---

.env.example
config/cdash.php

The last reference to `CURL_REQUEST_LOCALHOST` was removed in #1341, but the configuration setting itself was missed.  This PR removes the last remnants of this configuration setting.

Delete `CURL_REQUEST_LOCALHOST` configuration option

---

database/migrations/2023_07_20_185727_project_foreign_keys.php
database/migrations/2023_08_14_200318_user_foreign_keys.php
database/migrations/2023_08_14_205552_build_foreign_keys.php
phpstan-baseline.neon

The CDash 3.3 release will include foreign-key constraints for the first time.  CDash does a poor job of cleaning up after itself when deleting rows, so the new constraints will fail during the migration for many existing CDash systems.  The only way to add these constraints is delete any data which violates them.  This should not be problematic, because there should be no way to access invalid data in the first place.
I also simplified the existing migrations due to an egregious violation of the DRY principle...

Delete invalid rows prior to creating FK constraint

---

app/Http/Controllers/TestController.php

PHP's `array_unique()` function does not re-index the array when duplicates are removed.  PDO expects an array with sequential numeric keys, and fails if any duplicates were removed from the array.  I fixed the issue by re-indexing the array with `array_values()`.
This problem does not exist on master because the offending code was refactored since the 3.2 release branch was cut.

Re-index array after removing duplicates

---

app/cdash/app/Controller/Api/QueryTests.php
database/migrations/2023_11_09_182206_test_labels_index.php

`queryTests.php` is currently slow on some large production systems due to the changes introduced in #1455.  Adding this index improved the query time by two orders of magnitude on a large production system.  This PR also fixes a small bug introduced by #1455, in which labels associated with the same test run, but not the same build could appear in the results for the wrong build.
I will backport this to the 3.2 release branch once it's merged into master.

Improve test label query performance

---

app/Http/Controllers/CoverageController.php
app/cdash/app/Model/CoverageFile2User.php
phpstan-baseline.neon

The `CoverageFile2User` model contained two functions which differed by only a single parameter on one function call.  This rather trivial PR simply eliminates one of the functions, and adds an extra argument to the other.

Simplify copied code in coverage file pivot model

---

.gitignore

A few auto-generated files are not being ignored by Git.  This is particularly annoying on Docker systems where these files are generated during the image build process.  I also ignored all of the cache directories entirely.

Add additional files to `.gitignore`

---

app/cdash/app/Controller/Api/Index.php

The curly braces around the date filter for the index page were not properly placed, leading to the filter being disabled for most common cases.  This bugfix will be backported to CDash 3.2.

Fix date filter bug when subproject specified

---

package-lock.json
package.json

[`cross-env`](https://www.npmjs.com/package/cross-env) is listed in our `package.json`, but is not used in CDash, and is no longer receiving new updates.

Remove unused `cross-env` dependency

---

resources/js/components/BuildSummary.vue
resources/js/components/BuildUpdate.vue
resources/js/components/TestDetails.vue
resources/views/test/ajax-test-failure-graph.blade.php

Some graphs with timestamps on the x-axis do not render the timestamps properly.  This PR adds a format string to each of those plots to force a standardized date format.  This serves as a temporary patch until the upcoming graph library refactor is ready to merge.
| Before | After |
|---|---|
| ![image](https://github.com/Kitware/CDash/assets/16820599/87511c51-cbaa-4b2f-8fce-b1df984f9b35) | ![image](https://github.com/Kitware/CDash/assets/16820599/b97416f3-ae23-449a-8733-fd78f9bbe277) |

Specify format string for graphs with timestamps

---

app/Http/Controllers/BuildController.php
app/Models/Build.php
app/Models/BuildConfigure.php
app/Models/Configure.php
app/cdash/app/Model/BuildConfigure.php
app/cdash/include/sendemail.php
app/cdash/tests/test_buildconfigure.php
app/cdash/tests/test_configureappend.php
app/cdash/tests/test_longbuildname.php
phpstan-baseline.neon

This PR continues our ongoing effort to use Eloquent for all database interactions.  I created two new Eloquent models, and refactored some portions of the legacy BuildConfigure model to use them.  The legacy model in this case is difficult to work with, and I intend to return to it at a future point for a more significant refactor.

Convert backend of `Configure` model to Eloquent

---

docker/cdash.docker
install.sh
resources/views/maintenance.blade.php
webpack.mix.js

CDash administrators must run several commands to update a CDash system.  For administrators who are unfamiliar with CDash, this creates an unnecessary burden.
This PR introduces a new global `cdash_install` script which runs all of the necessary installation steps.  It's worth noting that Laravel's "maintenance mode" will be activated for the duration of the installation.  That will prevent users from accessing the system, and will block submissions.  In the future, I plan to update this script to allow submissions to be accepted while the system is in maintenance mode, but that is a significant undertaking which is beyond the scope of this PR.
#1492 added a `cdash_install` script for developers to sync files between the host and Docker container.  That script has been renamed …

Create new CDash installation script

---

docker/cdash.docker

Our Docker image currently ships with a .env file which contains values which differ from our default configuration values. This can be incredibly confusing for CDash administrators who are trying to set configuration values via environment variables.
There is no good reason for us to ship an Image with values which essentially override our default values. Thus, I have removed it.

Remove default `.env` from Docker image

---

.github/dependabot.yml

Dependabot only opens 5 PRs by [default](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit).  This potentially interferes with some of our monthly dependency upgrades.  After discussing the issue with GitHub support, I have bumped the allowable number of consecutive PRs to 100.  I will manually trigger Dependabot after this is merged to test the changes.

Explicitly set maximum number of Dependabot PRs

---

app/cdash/tests/data/TestingDay/Upload.xml
app/cdash/tests/test_consistenttestingday.php
app/cdash/xml_handlers/abstract_handler.php
app/cdash/xml_handlers/upload_handler.php
phpstan-baseline.neon

This removes duplicated logic and fixes a bug that sometimes caused builds to be assigned to the wrong testing day.
This commit also cleans up some code in abstract_handler.

Use Project::ComputeTestingDayBounds in upload_handler

---

resources/js/components/BuildSummary.vue
resources/js/components/BuildUpdate.vue
resources/js/components/TestDetails.vue
resources/views/test/ajax-test-failure-graph.blade.php

Cherry-picks #1816 to the 3.2 release branch.

Backport graph timestamp formatting

---

app/cdash/public/robots.txt
public/robots.txt

We currently have two `robots.txt` files.  One is unused, so I have deleted it.  The other disallows nothing, and is thus effectively useless, so it has been deleted as well.

Delete unnecessary robots.txt files

---

app/Console/Commands/MakeStorageDirectories.php
docker/bash/cdash.bash

When using a separate volume for CDash's storage directory, we need to ensure the existence of certain directories that Laravel expects.
We solve this problem by creating a new artisan command and running it from our Docker entrypoint.

Make sure Laravel storage directories exist

---

resources/js/components/TestDetails.vue

This functionality was broken with the following error message in the console:
Cannot read properties of undefined (reading 'highlight')
This was due to the fact that the 'plot' variable was undefined.
Highlighting this data point before we navigate to another page seems unnecessary, so this commit fixes the bug by removing the offending line of code.

Fix navigation when clicking on test details graph

---

.eslintrc.js

These rule changes make object and array formatting more consistent throughout our javascript code.  The goal of these changes is to make diffs easier to read when developers add new entries to objects or arrays.
As with most of the eslint style rules, these rules are officially deprecated, because the style rules have been moved to another repository.  I plan to make a separate PR to address that in the future.

Add new eslint rules for array and object formatting

---

app/cdash/tests/case/CDash/LinkifyCompilerOutputTest.php
app/cdash/tests/case/CDash/TestUseCaseTest.php
tests/Feature/MeasurementPositionMigration.php
tests/Feature/TestSchemaMigration.php

According to [the PHPUnit docs for `assertEquals()`](https://docs.phpunit.de/en/9.6/assertions.html#assertequals), the first argument to the function should be the expected output, and the second argument should be the actual value as produced by the test. Currently,  we have multiple places in the codebase where this ordering of the arguments is not respected. Calling this function with the arguments swapped can lead to confusion when debugging failed tests, as PHPUnit's error messages present failed comparisons in terms of an "expected" and an "actual" value.
The changes in this PR correct the instances where we use the wrong ordering (except for the file `tests/Feature/Monitor.php` which is being improved in PR https://github.com/Kitware/CDash/pull/1826). 
There are many other PHPUnit …

Standardize usages of PHPUnit's `assertEquals()`

---

.eslintrc.js

Reverts Kitware/CDash#1869 due to unintended formatting side effects.  I will investigate further, and find a better set of eslint rules in the future.

Revert "Add new eslint rules for array and object formatting"

---

app/Http/Controllers/CoverageController.php
app/Http/Controllers/ManageProjectRolesController.php
app/Http/Controllers/ManageUsersController.php

The user search feature currently leaves errors in the logs if the search only contains whitespace on postgres, or if the search parameter is not specified.  The UI experience is not affected.  This PR eliminates the errors previously generated by a somewhat reasonable search.

Handle missing search parameter more gracefully

---

app/cdash/config/config.php

Our legacy `config.php` file contains a handful of settings which are no longer used.  This PR removes those config options for better clarity about what options are and aren't supported.

Delete unused config settings

---

.eslintignore
jest.config.js
resources/js/app.js
resources/js/components/shared/ApiLoader.js
resources/js/components/shared/QueryParams.js
resources/js/components/shared/TextMutator.js
tests/Spec/build-configure.spec.js
tests/Spec/build-notes.spec.js
tests/Spec/build-summary.spec.js
tests/Spec/edit-project.spec.js
tests/Spec/manage-measurements.spec.js
tests/Spec/page-header/header-menu.spec.js
tests/Spec/test-details.spec.js
webpack.mix.js

This PR is the first of several incremental PRs which will gradually enable eslint linting for all of our JavaScript files.  To prevent merge conflicts with current and upcoming PRs, I have initially listed just the Jest tests, and a handful of configuration files.

Lint JS tests and JS helper files

---

.eslintignore
resources/js/components/Monitor.vue

A follow up PR to https://github.com/Kitware/CDash/pull/1827 and https://github.com/Kitware/CDash/pull/1826 that were merged around the same time, which resulted in this file not being linted.

Restore eslinting in `Monitor.vue`

---

.env.dev

Fixes https://github.com/Kitware/CDash/issues/1451 by using a single log file for all logging.

Use single log file by default in testing environment

---

.env.dev

The slow page warning log messages sometimes interfere with CDash tests which run slowly in our CI pipeline, or on slow computers.  This PR disables the warning in the dev/testing environment by setting the configuration value to a large number.  This PR should resolve some of the flaky tests which have been observed in the last few weeks, and eliminate the need for manual configuration settings on some developer machines.

Disable slow page warnings by default in dev/testing environment

---

.github/ISSUE_TEMPLATE/bug_report.md

Logging information is often the most useful way to debug issues, and I frequently have to request the logs when responding to issues.  This PR adds a reminder to the issue template in the hope that we will have to post comments requesting the logs less frequently.

Suggest including logging information in bug report

---

app/cdash/app/Model/BuildError.php

#1332 failed to handle null values, which resulted in errors when no logline was provided.  This code was refactored again after the 3.2 release branch was cut, and this problem does not exist on master.

Handle null logline condition

---

app/cdash/xml_handlers/build_handler.php

CDash currently fails during the submission process if a label is applied to something other than a build failure.  This PR adds additional checking, which allows the submission process to continue when labels are applied to invalid elements.

Add additional error checking to label handling

---

database/migrations/2023_12_19_211314_user_unique_email.php

The email address column of the user table is considered to be unique for login purposes, but the database allows multiple users to have the same email address.  This could potentially allow some users to be locked out of their account.  This PR adds a unique constraint to the email column, so it is impossible to have multiple users with the same email.

Add unique constraint to email column of users table

---

routes/web.php
tests/Feature/CDashTest.php

It is traditional for "index" routes which display a list of subitems which can be navigated to via unique IDs to be pluralized.  For example, a page showing the questions available should be under the route `/questions`, while a specific question should be available at `/questions/<id>`.  Examples of major websites which follow this convention:
- https://stackoverflow.com/questions
- https://github.com/orgs/Kitware/repositories
- https://gitlab.kitware.com/cmake/cmake/-/merge_requests
CDash currently has an inconsistent mix of route styles.  As we work to modernize the codebase, we should also modernize our routing structure while maintaining backwards compatibility wherever possible.
This PR standardizes the plurality of our routes which do not end with `.php`.  Updating every link …

Pluralize index routes

---

resources/js/components/AllProjects.vue
resources/js/components/UserHomepage.vue
resources/js/components/shared/LoadingIndicator.vue

We currently provide no information about the state of the page for pages with API endpoints which take a long time to return.  This PR adds a Vue template which accepts a slot for content to be rendered when the page is loaded, and a boolean prop which indicates whether the loading indicator should be shown.  I have initially used this template to add loading indicators to two pages as an example for future use.  I plan to switch the loading indicator icon to a Font Awesome icon instead of a grainy GIF once #1895 is merged.

Add loading indicator Vue template

---

tests/CMakeLists.txt

Currently, `eslint` warnings don't cause the `ctest` test to fail, which can easily be missed when testing locally or on the CI. This change forces the test to fail if any lines are flagged with a warning. Any `eslint` errors will make the test fail as before.

Enforce `eslint` warnings

---

.eslintignore
tests/CMakeLists.txt

This PR adds a simple check to ensure all items in `.eslintignore` are still valid paths. With our work on getting rid of technical debt, we end up moving/deleting files quite a lot, and it's easy to forget to edit the `eslint` ignore list as well. This new test will help us keep this file up to date.

Enforce a minimal `eslint` ignore list

---

tests/cypress/e2e/test-summary.cy.js

Fixes a minor issue with a Date object timezone introduced in https://github.com/Kitware/CDash/pull/1933.

Fix date generation in test-summary cypress test

---

package-lock.json
package.json
resources/js/app.js
resources/js/components/UserHomepage.vue

Most of the icons throughout the CDash UI are low resolution PNGs.  User expectations have changed since those icons were introduced, and pixelated icons are no longer considered acceptable, given that most users have high-resolution screens.  Font Awesome is a well known icon provider which provides a vast number of free SVG icons.
I've opened this PR up to get some feedback.  As an initial demonstration, I have changed the action buttons on the user homepage to font awesome icons.  CDash is in dire need of a substantial UI overhaul, and I'm by no means a UI/UX designer, so I'm open to any feedback anyone might have about the specific icons I've chosen, as well as general feedback about this idea as a whole.
| Before | After |
|---|--- | …

Add Font Awesome free icons

---

package-lock.json
package.json
tests/Spec/page-header/header-menu.spec.js

`moment` is only used once, for a basic task raw Javascript is more than capable of handling.  This PR removes our unnecessary dependency on the `moment` library.  This PR will render https://github.com/Kitware/CDash/pull/1916 unnecessary.

Remove `moment` dependency

---

app/cdash/app/Model/Build.php
app/cdash/tests/CMakeLists.txt
app/cdash/tests/data/MultipleSubprojects/Configure_bad.xml
app/cdash/tests/test_misassignedconfigure.php

We encountered a situation where a parent build had a configure record associated directly to it (and not to one of its children builds). In this case, CDash would throw a 500 error when attempting to view the configure output for this build.
While the cause was ultimately determined to be a non-standard XML format, we should also prevent CDash from throwing an error in this case, especially since the XML file in question was parsed "successfully".

More gracefully handle misassigned configure records

---

app/Utils/AuthTokenUtil.php
phpstan-baseline.neon

While looking through the documentation, I discovered that Laravel provides a `Request::bearerToken()` helper function.

Use Laravel for bearer token access

---

app/Http/Controllers/SiteController.php
app/cdash/public/viewSite.xsl

Fix the controller to accept that the site page can be accessed without specifying a project.
Ensure that the links back to the projects of a site have the leading `/` to not be relative to the `sites/` of the page.

Fix links to and from site page

---

app/Http/Controllers/UserController.php
app/cdash/public/editUser.xsl

#1640 fixed a slew of issues with the profile page, and completely overhauled the underlying code.  This PR is a minimal patch to restore password-change functionality for CDash 3.2.

Fix missing CSRF tokens for profile page

---

app/Jobs/ProcessSubmission.php
app/cdash/public/api/v1/getSubmissionFile.php
phpstan-baseline.neon

When using remote workers, the GuzzleHttp client isn't found in the namespace, add a `\` to use the global namespace
Files waiting on remote workers are copied into the `inprogress` directory, but the remote api looks for them in the `inbox` directory

Fix remote worker job processing

---

docker/docker-entrypoint.sh
install.sh
package.json

#1893 accidentally started installing dev dependencies in production containers via the `cdash_install` command.  This PR adds a `--dev` flag to `cdash_install` to control whether dev dependencies are installed or not.
Fixes #1951

Add production/development flag to `cdash_install`

---

config/cdash.php
package-lock.json
package.json

This PR should be the last thing merged before the CDash 3.3 branch is created, so that it is the most recent commit on the 3.3 branch.
By merging this into master before creating a release branch for 3.3, there will be less confusion about what the current version of master is derived from.  During the previous release cycle, master showed a version of 3.1, while in reality it was dozens commits ahead of 3.2, which confused the authors of multiple bug reports.

Bump CDash to v3.3

---

app/cdash/public/js/controllers/user.js

Prior to this commit, when attempting to create (or delete) an auth token, CDash would erroneously strip the subpath from the URL that it is making a POST request to. ie it would POST to:
https://mydomain.com/api/authtokens/create
instead of:
https://mydomain.com/cdash/api/authtokens/create

Fix authtoken generation for CDash in a subpath

---

app/cdash/public/css/common.css
resources/js/app.js
resources/js/components/AllProjects.vue
resources/js/components/UserHomepage.vue
resources/js/components/shared/DataTable.vue
tests/cypress/component/data-table.cy.js

This PR introduces a single standardized Vue component which can be used for all tables across the site.  This sortable table supports table cells with text, links, and custom components.  Column headers can be grouped.
As an example for developers to copy in the future, I have converted the main table on the projects page to the new template.

Add Vue component for standard tables

---

app/Http/Controllers/AdminController.php
app/cdash/public/upgrade.xsl
app/cdash/tests/test_upgrade.php
phpstan-baseline.neon

The "Compress Test Output" button on the CDash maintenance page is currently broken.  The functionality is no longer necessary because all test output is compressed upon upload by default.  This PR simply removes the button and associated logic.
Fixes #1970.

Remove broken "Compress Test Output" button

---

resources/js/components/shared/GraphqlLoader.vue
tests/cypress/component/graphql-loader.cy.js

#1772 added a brand new GraphQL API.  Moving forward, we plan to gradually convert the entire CDash UI to use this new API.
This PR introduces a new Vue component which executes a GraphQL query, and provides the resulting data to a child component.  An example usage might look like this:
```vue
<graphql-loader
query="
query {
projects {
id
name
builds {
id
name
}
}
}
"
>
<template v-slot="{ data }">
Plain text or component here...  Use data like this: {{ data }}
</template>
</graphql-loader>
```

Add GraphQL data loader Vue component

---

database/seeds/DatabaseSeeder.php

#1469 discusses the need for a development environment in which the DB is seeded with realistic data for testing purposes.  This PR adds some basic data to a development environment created by running `php artisan migrate:fresh --seed`.  Future e2e tests should be written against the data generated here, and the development should grow as more tests are needed.

Add basic DB seeding to dev environment

---

app/Models/Build.php
app/Models/Project.php
app/cdash/tests/CMakeLists.txt
graphql/schema.graphql
phpstan-baseline.neon
tests/Feature/GraphQL/SiteTest.php
tests/Traits/CreatesSites.php

This PR adds GraphQL fields which expose site data for individual builds, as well as aggregate site data for entire projects.  In the future, I will expand upon this by adding "site information", as well as a top-level site field.

Expose site information via GraphQL

---

routes/web.php

This change fixes to a typo in the pluralization rerouting logic (introduced in https://github.com/Kitware/CDash/pull/1900) that broke all existing references to the url: `build/<buildid>/configure`.

Bugfix reroute for the build configure page

---

.env.example
app/Http/Controllers/ManageProjectRolesController.php
app/cdash/public/manageProjectRoles.xsl
config/auth.php

Add a new environment variable that will disable the registration form that is found on the manageProjectRoles page.  If the current user is a site administrator, the form will always be shown.
Issue: #2007

Add config to disable Project Administrator user registration

---

routes/web.php

Change the controller for the old OAuth routes to be the new Socialite functions.  This should prevent already existing Apps from needing to change the redirect URL to match the current framework.

Redirect old OAuth routes to Socialite

---

install.sh

Storage directories are not created by default when running `cdash_install` currently.  Requiring users to run the `storage:mkdirs` artisan command manually creates unnecessary busywork.  This PR changes the behavior to create the required directories automatically on install.

Create storage directories automatically

---

.env.example
app/Http/Controllers/ManageProjectRolesController.php
app/cdash/public/manageProjectRoles.xsl
config/auth.php

Originally was: 3003562cb032b7517d6a97e56fbaad32382b2f06
Add config to disable Project Administrator user registration (#2019)
Add a new environment variable that will disable the registration form that is found on the manageProjectRoles page. If the current user is a site administrator, the form will always be shown.
Issue: #2007

Backport Project Administration disabling

---

app/cdash/app/Model/Build.php

updateOrCreate is apparently not atomic
https://github.com/laravel/framework/issues/19372
...but upsert is???
https://stackoverflow.com/a/70978095
https://stackoverflow.com/a/70209143

Store BuildInformation using upsert instead of updateOrCreate

---

app/cdash/include/dailyupdates.php

Automatically delete old files out of the `inprogress/` directory in case they get stuck here for some reason.

Add 'inprogress' to the list of directories to clean

---

app/cdash/include/common.php

Follow-up to #1657
Remove DELETE statements that are now handled by cascading foreign keys instead.

Remove redundant DELETE statements from `remove_build()`

---

CMakeLists.txt
app/cdash/tests/CMakeLists.txt
app/cdash/tests/autoremovebuilds/CMakeLists.txt
app/cdash/tests/ctest/CMakeLists.txt
tests/CMakeLists.txt
tests/cypress/e2e/CMakeLists.txt

This change aims to make a first pass at setting up proper test dependencies for our test suite. Currently, many tests implicitly depend on data produced by other tests, and many require exclusive access to resources (like writing to the database and/or to shared log files). As a result, CTest could so far be run only serially, and we have been relying on the execution order to match the order in which tests are defined in the CMake files. 
The addition of dependencies in this PR maintains the old test execution order, with the exception of tests we know to be independent like the linters, static analysis, and a few unit and component tests. CTest can now be safely run in parallel, and a small speedup can be observed due to these independent tests. Future PRs will go in to establish the …

Add CTest test dependencies

---

app/cdash/app/Controller/Api/ResultsApi.php
phpstan-baseline.neon

As specified [here](https://www.php.net/manual/en/datetimeimmutable.getlasterrors.php), before PHP 8.2.0, `DateTime::getLastErrors()` did not return `false` when there were no warnings or errors. Instead, it would always return the documented array structure. But on PHP 8.2.0 and newer, it actually may be `false`, and using `array_sum()` on it shall cause an error like:
```
[2024-02-13 19:47:40] production.ERROR: array_sum(): Argument #1 ($array) must be of type array, false given {"userId":1,"exception":"[object] (TypeError(code: 0): array_sum(): Argument #1 ($array) must be of type array, false given at /opt/CDash/app/cdash/app/Controller/Api/ResultsApi.php:84)
[stacktrace]
#0 /opt/CDash/app/cdash/app/Controller/Api/ResultsApi.php(84): array_sum()
#1 …
```

Don't fail date validation on PHP >= 8.2

---

app/cdash/include/Test/BuildDiffForTesting.php
app/cdash/include/Test/CDashUseCaseTestCase.php
app/cdash/tests/case/CDash/Api/GitHubWebhookTest.php
app/cdash/tests/case/CDash/Lib/Repository/GitHubTest.php
app/cdash/tests/case/CDash/Messaging/Subscription/CommitAuthorSubscriptionBuilderTest.php
app/cdash/tests/case/CDash/Messaging/Subscription/UserSubscriptionBuilderTest.php
app/cdash/tests/case/CDash/Messaging/Topic/AuthoredTopicTest.php
app/cdash/tests/case/CDash/Messaging/Topic/BuildErrorTopicTest.php
app/cdash/tests/case/CDash/Messaging/Topic/MissingTestTopicTest.php
app/cdash/tests/case/CDash/Messaging/Topic/TestFailureTopicTest.php
app/cdash/tests/case/CDash/Model/BuildFailureTest.php
app/cdash/tests/case/CDash/Model/BuildRelationshipTest.php
app/cdash/tests/case/CDash/Model/BuildTest.php
app/cdash/tests/case/CDash/Model/PendingSubmissionsTest.php
app/cdash/tests/case/CDash/Model/RepositoryTest.php
app/cdash/tests/case/CDash/ServiceContainerTest.php
app/cdash/tests/case/CDash/Submission/CommitAuthorHandlerTraitTest.php
app/cdash/tests/case/CDash/XmlHandler/UpdateHandlerTest.php
phpstan-baseline.neon
tests/Feature/ProjectPermissions.php

This PR is the second in the series for addressing changes that will need to be made before https://github.com/Kitware/CDash/pull/1866 can be merged. The PHPUnit function `setMethods()` is [deprecated](https://github.com/sebastianbergmann/phpunit/blob/9.6/DEPRECATIONS.md#test-double-api), so our usages of it were switched to `onlyMethods()` instead. The only locations that weren't updated and still being suppressed in `phpstan-baseline.neon` are:
* `app/cdash/include/Test/CDashTestCase.php`
* `app/cdash/include/Test/CDashUseCaseTestCase.php`
* `app/cdash/tests/case/CDash/Lib/Repository/GitHubTest.php`
* `app/cdash/tests/case/CDash/Model/BuildErrorTest.php`
* `tests/Unit/app/Validators/PasswordTest.php`
since a simple replacement of `setMethods()` by `onlyMethods()` does not work for these …

Replace most usages of deprecated PHPUnit `setMethods()` function 

---

app/cdash/include/Test/CDashTestCase.php
phpstan-baseline.neon

This PR is meant to serve as a first step for addressing changes that will need to be made before https://github.com/Kitware/CDash/pull/1866 can be merged. The PHPUnit function `returnCallback()` is [deprecated](https://github.com/sebastianbergmann/phpunit/issues/5423), so our usage of it was switched to its shorthand syntax, as recommended by the docs.

Replace usage of deprecated PHPUnit `returnCallback()` function

---

.circleci/commands.bash
.circleci/config.yml

This PR serves as a follow up to PR https://github.com/Kitware/CDash/pull/2077 to take advantage of the new ability to run some of the tests in parallel. Also, as per @williamjallen's request in https://github.com/Kitware/CDash/pull/2078#pullrequestreview-1913036531, the `docker/commands.bash` script was moved to the `.circleci/` directory.

Add parallelism to CTest CI tests

---

.env.example
app/cdash/app/Lib/Repository/GitHub.php
app/cdash/app/Lib/Repository/RepositoryInterface.php
app/cdash/tests/case/CDash/Lib/Repository/GitHubTest.php
config/cdash.php
phpstan-baseline.neon

When this environment variable is set to true, CDash will always report a status of 'success' to any GitHub repositories that have installed this CDash server as a GitHub App.
This is useful in cases where you do not want the CDash GitHub check to prevent a PR from being merged.

Add GITHUB_ALWAYS_PASS configuration option

---

.rsyncignore
app/Http/Kernel.php
config/graphiql.php
config/lighthouse.php
resources/views/vendor/graphiql/index.blade.php

https://github.com/Kitware/CDash/pull/2079 introduced the first GraphQL mutation to our schema, but GraphiQL is currently unable to execute it because the session-handling middleware is out of order.  This PR adds support for authenticated queries via GraphiQL by rearranging the middleware order.  I also added CSRV validation.

Enable GraphiQL execution of protected queries

---

database/migrations/2024_03_22_031040_project_unique_name.php

Project name uniqueness is currently defined implicitly via the controls we provide to create projects.  This PR adds a unique constraint to the project name column to ensure that it is impossible for projects with duplicate names to be created.

Add unique constraint to project name

---

.env.example
docker/docker-compose.production.yml
docs/docker.md

Introduce a new environment variable `NUM_WORKERS` that allows us to specify how many queue workers should be created by docker compose.
Also reconfigure these queue workers to restart automatically upon failure.

Enable horizontal scaling of queue workers from docker compose

---

cypress.config.js
tests/cypress/e2e/sub-project-group-order.cy.js

This is an attempt to improve the flakey behavior seen by the `sub-project-group-order` Cypress test on our CI (see [here](https://open.cdash.org/testSummary.php?project=24&name=cypress%2Fe2e%2Fsub-project-group-order&date=2024-03-01)). We speculate that the flakes have to do with the UI design of the page and how Cypress can interact with it, namely actions like hover, and drag and drop.

Improve flakiness of `sub-project-group-order` test

---

app/Models/Project.php
graphql/schema.graphql
tests/Feature/GraphQL/ProjectTest.php

This PR exposes a new "administrators" field in the Project type.  A subsequent PR will add similar fields for project maintainers.
This PR also fixes an issue which prevented aggregate queries from selecting public and protected projects the user could otherwise query individually.

Expose project administrators via GraphQL API

---

CMakeLists.txt
Dockerfile
app/cdash/tests/CMakeLists.txt
app/cdash/tests/ctest/coveragedriver.ctest.in
app/cdash/tests/ctest/ctestdriver.ctest.in
app/cdash/tests/ctest/sameImage/CMakeLists.txt
app/cdash/tests/ctest/sameImage/test.cmake.in
app/cdash/tests/ctest/simple/CMakeLists.txt
app/cdash/tests/ctest/simple/test.cmake.in
app/cdash/tests/ctest/simple2/CMakeLists.txt
app/cdash/tests/ctest/simple2/simple.ctest.in
app/cdash/tests/ctest/simple2/test.cmake.in
docker/docker-compose.postgres.yml
docker/docker-compose.production.yml
docker/docker-compose.yml
docker/docker-entrypoint.sh
tests/CMakeLists.txt

We currently provide support for a Debian-based CDash image, but some clients require a RedHat UBI-based image.  RedHat does not support libsodium and the corresponding sodium PHP extension, which is required for our GitHub App integration to function.  That means that it is impractical for us to switch to UBI for our general-purpose CDash image.  To support the needs of clients who require a RedHat UBI-based image, this PR introduces a dual-image system in which users can choose their preferred base image, with the caveat that the UBI-based image does not support GitHub App integration.
To create a UBI-based image, simply set the `BASE_IMAGE` build argument to `ubi`.  The `BASE_IMAGE` build argument defaults to `debian`, which results in a build similar to the previous image build.
It is …

Add new UBI-based CDash image

---

app/Models/Project.php
app/cdash/app/Model/Project.php
app/cdash/tests/test_compressedtest.php
app/cdash/tests/test_updateonlyuserstats.php
database/migrations/2024_03_22_233702_drop_bugtrackerfileurl_column.php
phpstan-baseline.neon

The `bugtrackerfileurl` column in the project table is no longer used and no longer serves a purpose.  This PR introduces an irreversible migration to drop the column.

Drop `bugtrackerfileurl` column

---

graphql/schema.graphql
tests/Feature/GraphQL/ProjectTest.php

This PR exposes a visibility field in the project type in the new GraphQL API.
I intend to gradually phase in each of the columns in the project table after carefully considering the name, necessary constraints, and purpose of each one.  This is the first of several planned PRs on this topic.

Add project visibility field to GraphQL schema

---

Dockerfile

The final revision of #2088 only included xdebug in the development image, which led to a failure when attempting to use `composer remove`, as caught by #2095.  This PR addresses that failure, and ensures that both development and production images build properly for Debian and UBI.

Fix xdebug issue in production UBI image

---

database/migrations/2024_03_22_234620_label2buildfailure_index.php

Resolves half of https://github.com/Kitware/CDash/issues/2046 by indexing the `label2buildfailure` pivot table such that it is possible to look up the `labelid` by the `buildfailureid`.

Index `buildfailureid` column in `label2buildfailure` table

---

database/migrations/2024_03_23_001025_label2dynamicanalysis_index.php

Related to #2103.  Adds an index to the `dynamicanalysisid` column of the `label2dynamicanalysis` pivot table to allow efficient lookup of the `labelid` by the `dynamicanalysisid`.  See https://github.com/Kitware/CDash/issues/2046.

Index `label2dynamicanalysis` (`dynamicanalysisid`)

---

database/migrations/2024_03_23_180709_site2user_fk_and_index.php

This PR adds a foreign-key constraint to the siteid column, a unique constraint to prevent inadvertent duplicate rows, and two indexes to allow efficient querying in either direction.
Closes #2109.

Add foreign-key and unique constraints to site2user

---

.github/workflows/ci.yml

As per the [docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions), the `merge_group` trigger is necessary to trigger CI runs when using the merge queue.  This should fix the jobs which are currently stuck in the queue.

Add `merge_group` CI trigger

---

.env.example
app/Http/Controllers/ProjectController.php
app/Rules/ProjectVisibilityAllowed.php
app/cdash/public/api/v1/project.php
config/cdash.php
graphql/schema.graphql
phpstan-baseline.neon
resources/js/components/EditProject.vue
tests/Feature/GraphQL/ProjectTest.php

Some CDash administrators may want users to be able to create projects on their own, but not public or protected projects.  This PR adds a new `MAX_PROJECT_VISIBILITY` environment variable which specifies the most visible setting a project can be configured to use.  Instance administrators can override this setting, to allow some projects to be made public or protected with administrator approval.

Add new `MAX_PROJECT_VISIBILITY` config option

---

graphql/schema.graphql

There is currently no need for a top-level user field in our GraphQL API.  It may be desirable to limit user visibility in the future, so I have removed the top-level user field.  Instead, I plan to offer more limited access to users on a per-project basis in an upcoming PR.  The decision to offer a top-level user field can be reconsidered in the future once the API is more mature.

Remove top-level User GraphQL field

---

Dockerfile
app/cdash/app/Model/BuildConfigure.php
app/cdash/app/Model/BuildErrorFilter.php
app/cdash/tests/test_buildgetdate.php
app/cdash/xml_handlers/done_handler.php
app/cdash/xml_handlers/testing_handler.php
phpstan-baseline.neon

As per the [support schedule](https://www.php.net/supported-versions.php), PHP 8.1 is only receiving security fixes and will become EOL as of December 8, 2024.  Given that many CDash systems go long periods of time between updates, it makes sense to proactively increase the default PHP version in our base images to PHP 8.2.  Unfortunately, RedHat has not released a PHP 8.2 UBI image yet, so only the Debian image has been updated.  The UBI image will be updated to PHP 8.2 once an image becomes available.
Closes https://github.com/Kitware/CDash/issues/2094.

Bump default PHP to 8.2

---

resources/views/auth/login.blade.php

The issue occurs because the css class `invalid-feedback` contains `display: none`. 
I used this feedback to solve the issue: https://stackoverflow.com/a/50522718
The screenshot shows an example for a failed LDAP login:

Fix #2141 - No error message provided to user for failed login attempts

---

.env.example
app/Http/Controllers/ProjectController.php
app/Rules/ProjectAuthenticateSubmissions.php
app/cdash/public/api/v1/project.php
config/cdash.php
graphql/schema.graphql
phpstan-baseline.neon
tests/Feature/GraphQL/ProjectTest.php

This builds on top of the work done in #2115, and adds a new `REQUIRE_AUTHENTICATED_SUBMISSIONS` configuration option which requires regular users to enable authenticated submissions when creating or editing projects.  Instance administrators are able to override this setting.
This should be merged after #2115.

Add new `REQUIRE_AUTHENTICATED_SUBMISSIONS` config option

---

config/cdash.php
package-lock.json
package.json

Bumps the reported version of CDash to 3.4 on master in anticipation of the upcoming 3.4 release, and to prevent confusion when handling bug reports from users running master but claiming that they are running 3.3.

Bump master version to 3.4

---

app/Console/Commands/MakeStorageDirectories.php
app/Http/Controllers/SubmissionController.php
app/cdash/xml_handlers/upload_handler.php
phpstan-baseline.neon
routes/api.php
tests/Feature/RemoteWorkers.php

Use an internal, secured API endpoint to store files parsed from Upload.xml when CDash is configured to use remote workers.
Follow-up to #2143

Fix upload_handler for remote workers

---

.github/dependabot.yml

The automatic release notes generation process uses the "release notes: external dependencies" label to automatically put dependency PRs in the right section of the release notes.  Manually adding the label to all of the dependency PRs is a time consuming process which this PR aims to automate.

Label dependency PRs automatically

---

config/lighthouse.php
graphql/schema.graphql
tests/Feature/GraphQL/BuildTypeTest.php
tests/Feature/GraphQL/ProjectTypeTest.php
tests/Feature/GraphQL/SiteTypeTest.php

Requiring pagination is important for ensuring that queries remain efficient at scale.  GraphQL pagination via the [Relay](https://facebook.github.io/relay/graphql/connections.htm) specification is the best way to implement pagination.  This PR converts all of the relations to paginated relations with a default batch size of 100.

Enable GraphQL pagination

---

app/Http/Controllers/OAuthController.php

Add a try/catch block to the OAuth controller which will catch an exception thrown when trying to get a user from an auth call that was rejected.
Fixes #2189

Add try/catch block to account for OAuth permission denials

---

webpack.mix.js

Our Git Webpack plugin supports lightweight tags, but we don't have the right configuration options set to enable it.  This PR enables support for lightweight tags.

Show proper version for lightweight tags

---

app/Http/Controllers/SiteController.php
app/Models/Site.php
app/Models/SiteInformation.php
app/cdash/tests/case/CDash/TestUseCaseTest.php
app/cdash/tests/test_projectwebpage.php
database/migrations/2024_04_28_215829_site_information_nullable.php
graphql/schema.graphql
phpstan-baseline.neon
tests/Feature/GraphQL/SiteTypeTest.php
tests/cypress/e2e/sites.cy.js

The current network of site-related CDash pages is filled with inconsistencies, and at times, incorrect behavior, and is in dire need of a refactor.  I plan to use an overhaul of these site pages as a testing ground for the new GraphQL API in the near future.  To support that upcoming work, this PR exposes SiteInformation data via the GraphQL API and cleans up a bunch of related logic.

Add SiteInformation type to GraphQL API

---

app/cdash/app/Controller/Api/Index.php

The osname can be `Darwin` on some systems, and should be categorized as macOS.

Fix platform icon for Darwin systems

---

app/Models/Build.php
app/cdash/app/Model/Build.php
app/cdash/xml_handlers/build_handler.php
database/migrations/2024_04_13_161402_drop_build_log_column.php
phpstan-baseline.neon

The log column in the build table appears to be unused.  Information can be written to the column, but there is no way to extract the contents.  Since this appears to be a legacy feature which is obsolete in CDash today, I have removed the log column and all remaining references to it.  Build.xml files containing the LOG element will be ignored.
While I've done a significant amount of digging to try to find additional references to the log column, it is theoretically possible that the column is still referenced in a SQL query or via reflection somewhere.

Drop unused build log column

---

.github/workflows/ci.yml

Items in the merge queue currently get added to the "Master" build group, which leads to false concerns when queued PRs fail our CI checks.  The build group is already present on open.cdash.org.

Display merge queue CDash results in separate build group

---

Dockerfile
docker/docker-entrypoint.sh
install.sh
resources/js/app.js
resources/views/cdash.blade.php

The CDash UI currently needs the `APP_URL` environment variable at build time, which means that our Docker container startup time is limited by the time it takes to build the UI.  It also means that our container is not fully static.
This PR adds a data attribute to the Vue mount point, which means the `APP_URL` is no longer built into the UI.  To take advantage of this, I added commands to build the website during the Docker image build, and added a new `--initial-docker-install` flag to `cdash_install` which skips unnecessary steps if it's the first run of the script.  The CDash container is now able to begin serving requests less than 5 seconds after starting if no migrations are necessary.
Although I have not tested it yet, I believe this change also means that the web service can be …

Inject Vue APP_URL at page load time

---

webpack.mix.js

We currently minify our JS, which makes it very difficult to debug.  As we move towards a more JS-focused web app approach, this will gradually become a nuisance.  [Source maps](https://blog.teamtreehouse.com/introduction-source-maps) are the typical solution to this problem, and Mix [supports](https://laravel.com/docs/8.x/mix#css-source-maps) automatic source map generation.
To test this, simply cause an error on any Vue page and observe the original source code rendered by your browser.

Generate JS and CSS source maps

---

app/cdash/app/Controller/Api/QueryTests.php

#1455 mistakenly used the test ID instead of the test output ID to find labels for the queryTests page.  This issue was separately resolved in the 3.5 release series by the refactor in #2148.
Failures like this are a good motivation for our effort to move to a GraphQL API.  With GraphQL, there is a single source of truth about where labels come from, and there isn't a need to separately query the labels in dozens of different locations.  These types of failures are also a good motivation for more complete testing data, with most tables having at least thousands of rows.  With limited data, this failure went unnoticed because each test ID corresponds to a test output ID in the testing environment.  This limited issue was resolved by the removal of the test table in #2148.

Fix missing labels in queryTests.php table

---

app/Models/BasicBuildAlert.php
app/Models/Build.php
app/Models/BuildError.php
app/cdash/app/Model/Build.php
app/cdash/app/Model/BuildError.php
graphql/schema.graphql
phpstan-baseline.neon
tests/Feature/GraphQL/BuildTypeTest.php

This PR continues our ongoing effort to expose most of the database schema via GraphQL.

Expose build errors and warnings via GraphQL

---

config/cdash.php
package-lock.json
package.json

In accordance with the release process [checklist](https://github.com/Kitware/CDash/blob/master/docs/release_process.md), the version of CDash reported on master should be increased to the next upcoming minor release when a release is made to prevent confusion when handling bug reports.

Bump master version to 3.5

---

.github/workflows/release.yml

We were accidentally pushing cdash webservice images instead of cdash-worker images.

Fix cdash-worker Docker images for release tags

---

.github/workflows/ctest_driver_script.cmake

As of https://github.com/Kitware/CDash/pull/2153, the `APP_URL` environment variable is no longer built into the website code, and it is no longer necessary to run a Mix build after the test suite to restore the original `.env`.  This change will save a few seconds on every CI run.

Remove unnecessary mix build after test

---

app/GraphQL/Directives/FilterDirective.php
app/Models/Project.php
app/cdash/tests/CMakeLists.txt
graphql/schema.graphql
phpstan-baseline.neon
tests/Feature/GraphQL/BuildTypeTest.php
tests/Feature/GraphQL/FilterTest.php
tests/Feature/GraphQL/ProjectTypeTest.php
tests/Feature/GraphQL/SiteTypeTest.php

This PR introduces the ability to add conditions to aggregate queries in the GraphQL API.  This allows users to select only public projects or all the builds submitted after a given timestamp, for example.  This introductory PR adds the =, !=, <, and > operators.  Future PRs will add additional operators to the filter set.
How is this PR different from Lighthouse-PHP's [existing](https://lighthouse-php.com/master/eloquent/complex-where-conditions.html) filtering functionality?  The approach Lighthouse takes is not type safe, which makes the API confusing to use and difficult to maintain.  It also lacks the flexibility CDash needs, and does not support enumeration filtering.  This PR builds upon Lighthouse's existing approach, by introducing type-safe filters.
In the future, these filters …

Add GraphQL query filtering capability

---

.github/workflows/ci.yml

#2178 used the wrong trigger for merge queue builds.

Fix trigger for merge queue build group

---

.github/workflows/submit.sh
app/Http/Controllers/SubmissionController.php
app/Http/Middleware/CheckForMaintenanceMode.php
app/Utils/UnparsedSubmissionProcessor.php
docker/docker-entrypoint.sh

Some database migrations take several hours to complete for large systems.  To prevent unnecessary gaps in submission data during migration periods, this PR expands our existing functionality for accepting submissions while the database is offline to also cache submissions while maintenance mode is enabled.
For users of Docker-based systems, maintenance mode is automatically enabled when the container starts, and is disabled when the setup/update process is complete.  Administrators of bare-metal CDash systems should enable maintenance mode with the command `php artisan down` when upgrading, followed by `php artisan up` when maintenance is complete.

Cache submissions while migrations are running

---

app/cdash/include/common.php
database/migrations/2024_05_27_185853_related_builds_relatedid_fk.php

Closes https://github.com/Kitware/CDash/issues/2220 by adding a foreign key constraint to the `relatedid` column` in the `related_builds` table.  Doing so allowed a small portion of our build removal process to be eliminated.

Add foreign key to `relatedid` column in `related_builds`

---

app/Console/Kernel.php
app/Jobs/PruneAuthTokens.php
app/Jobs/PruneJobs.php
app/Models/AuthToken.php
app/Models/SuccessfulJob.php
app/Utils/AuthTokenUtil.php
app/cdash/include/dailyupdates.php
app/cdash/tests/CMakeLists.txt
docker/docker-entrypoint.sh
phpstan-baseline.neon
tests/Feature/Jobs/PruneAuthTokensTest.php
tests/Feature/Jobs/PruneJobsTest.php

NOTE: This PR moves cleanup logic out of the request-triggered daily update script.  To continue having these cleanup tasks performed automatically, administrators of non-Docker systems must run `php artisan schedule:run` via cron or similar.
The current "daily update" process is clunky, and in dire need of a refactor.  This PR takes the first step towards modernizing the daily update process by separating out a few small portions of the process into independent "tasks" managed by Laravel.  This PR also develops the infrastructure needed to eventually perform LDAP syncing for https://github.com/Kitware/CDash/issues/1983.
Laravel overhauled the task system in Laravel 11, but we can't upgrade to Laravel 11 until Red Hat releases a UBI image with PHP 8.2+.

Schedule periodic tasks with Laravel

---

Dockerfile

Following #2113, Red Hat now offers a UBI image with PHP 8.2.

Bump PHP from 8.1 to 8.2 in UBI-based image

---

app/cdash/xml_handlers/JSCoverTar_handler.php
app/cdash/xml_handlers/JavaJSONTar_handler.php
app/cdash/xml_handlers/project_handler.php
phpstan-baseline.neon

This PR is a small amount of incremental progress towards fully switching from the legacy database connection to Laravel's DB facade, or Eloquent, as appropriate.  This PR specifically converts all legacy database code in the XML handlers.  Changes like this lay the groundwork for the eventual ability to log the queries being executed for every request.

Switch legacy DB to Laravel DB facade in XML handlers

---

tests/Feature/RouteAccessTest.php
tests/Feature/UniqueEmailsMigration.php
tests/Traits/CreatesUsers.php

The tests currently create users with a fixed email address and password, which can cause conflicts if multiple tests are running at the same time.  See [this](https://open.cdash.org/tests/1583834204) failed test, for example.  This PR resolves the issue by creating users with email addresses and passwords containing UUIDs.
<details>
<summary>Output from a test with conflicts for reference</summary>
```
PHPUnit 9.6.4 by Sebastian Bergmann and contributors.
E.                                                                  2 / 2 (100%)
Time: 00:00.206, Memory: 32.00 MB
There was 1 error:
1) Tests\Feature\Jobs\PruneAuthTokensTest::testExpiredAuthTokenDeleted
Illuminate\Database\UniqueConstraintViolationException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry …
```

Randomize testing user emails and passwords

---

.github/dependabot.yml

This PR allows Dependabot to provide dependency updates for our GitHub Actions.

Update GitHub Actions via Dependabot

---

cypress.config.js

One of our Cypress tests has been particularly flaky lately.  This appears to be due to the CI runners executing slowly, with API wait times exceeding the default 4-second timeout Cypress provides.  This PR increases the default command timeout to 30 seconds.
A recent flaky test result: https://open.cdash.org/tests/1583856484
<details>
<summary>Full output:</summary>
```
DevTools listening on ws://127.0.0.1:35925/devtools/browser/54698314-e37e-4b52-ab9b-92bf86d406aa
tput: No value for $TERM and no -T specified
================================================================================
(Run Starting)
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Cypress:        13.7.1 …
```

Increase default Cypress command timeout

---

app/cdash/tests/CMakeLists.txt
app/cdash/tests/test_lotsofsubprojects.php

It is currently possible for exceptions to go unnoticed in our simpletest test cases, because the CTest regex is not strict enough.  For example, this error has been in our test logs for a very long time: [(source)](https://open.cdash.org/tests/1591195781)
```
/cdash/app/cdash/tests/test_lotsofsubprojects.php
All Tests
unlink '/cdash/storage/logs/cdash.log'
In test_lotsofsubprojects.php line 30:
unlink(LotsOfSubprojects_Configure.xml): No such file or directory
```

Require "OK" in simpletest output to pass

---

resources/views/test/view-test.blade.php

`viewTest.php` currently only displays the system information table at the top of the page for child builds.  This PR simplifies the confusion behavior of this page by simply displaying the system information table for all builds, regardless of parent or child status.

Display viewTest.php system info table for all builds

---

app/Ldap/Rules/FilterRules.php
docs/authentication.md
phpstan-baseline.neon
tests/Feature/LdapIntegration.php

While the current LDAP testing setup introduced in #2206 is an improvement over the previous mocking approach, it still lacks the robustness needed to test more complex features.  This PR improves the tests by programmatically creating multiple users and groups, instead of just using a few hardcoded users in a single group.

Test LDAP against more complex group setup

---

app/Http/Controllers/AbstractController.php
app/Http/Controllers/AdminController.php
app/Http/Controllers/Auth/LoginController.php
app/Http/Controllers/AuthTokenController.php
app/Http/Controllers/BuildController.php
app/Http/Controllers/BuildPropertiesController.php
app/Http/Controllers/CoverageController.php
app/Http/Controllers/ManageBannerController.php
app/Http/Controllers/ManageProjectRolesController.php
app/Http/Controllers/ManageUsersController.php
app/Http/Controllers/MonitorController.php
app/Http/Controllers/SiteController.php
app/Http/Controllers/TestController.php
app/Http/Controllers/UserController.php
app/Providers/AppServiceProvider.php
phpstan-baseline.neon

Our current redirect logic is messy, and just happens to work for most CDash systems.  For CDash-in-a-subdirectory systems, the redirect logic is somewhat broken.
This PR refactors the entire system to consistently apply redirects to all web routes.

Refactor URL redirect after login

---

install.sh

As discussed [here](https://github.com/Kitware/CDash/pull/2270#issuecomment-2173717653), Laravel's route cache does not work for CDash-in-a-subpath installations.  Since the route cache provides a negligible speedup, this PR simply removes it for all systems.  This fixes an issue observed on some CDash-in-a-subpath installations where the `/` route does not behave correctly.

Eliminate route cache

---

.php-cs-fixer.dist.php
app/cdash/include/filterdataFunctions.php
composer.json
composer.lock

As per the [release schedule](https://www.php.net/supported-versions.php), PHP 8.1 is only receiving security fixes at this time.  The official end-of-life date has been extended to January 1, 2026.  PRs https://github.com/Kitware/CDash/pull/2113 and https://github.com/Kitware/CDash/pull/2226 increased the version of PHP to 8.2 for each of our Docker images.  This PR bumps the version of PHP to 8.2 for all systems.

Bump required PHP to 8.2 for all systems

---

.github/workflows/build-latest-images.yml
.github/workflows/release.yml

We currently only release `amd64` images.  Some users may want to run on `arm64` platforms provided by various cloud providers, and developers may operate from arm64-based Macs.  This PR adds multi-architecture builds to our automated release process.

Add automatic multi-architecture Docker builds

---

app/Console/Commands/ValidateXml.php
app/Validators/Schemas/Build.xsd

The current error handling and logging for XML files submission parsing is not extensive enough, and it is not easily accessible to users making the submissions. This PR is the first in a series of changes meant to improve this aspect of the user experience.
The changes define an initial schema for valid "Build" XML files, and a tool to validate such files against it. The schema has been tested against all build XML data files in the CDash repo, as well as on production data (generated by CTest).
Future PRs are to expand on this by improving the rigor of the schema, defining schemas for all other upload types CDash accepts (update, configure, test, etc.), and incorporating the validation into our submission handling process.

Add initial support for `Build.xml` submission file validation

---

app/Http/Controllers/SubmissionController.php

CDash currently returns a 503 error if the database is unavailable, which causes CTest to print errors.  This PR changes the behavior to instead return a HTTP 200 status code if the files are successfully received, regardless of whether they can be stored in the database at that particular time.

Return success if files accepted regardless of DB status

---

resources/views/cdash.blade.php

We received a report of some CDash instances failing to load index.php properly. The error in the web console was:
TypeError: $rootScope.queryString is undefined
After further investigation, we discovered that the `<head>` element did not contain the `ng-controller="HeadController"` attribute. We are not sure what caused this behavior, and why it only occurs on some CDash instances and not others, but moving the controller to the top-level `<html>` element seems to fix the problem.

Move HeadController from `<head>` to `<html>`

---

app/Validators/Schemas/Build.xsd
app/Validators/Schemas/common.xsd

As part of our efforts to improve the CDash submission process, we working to introduce XML schematics to help with submission validation. The first of these PRs merged is https://github.com/Kitware/CDash/pull/2277. The changes in this PR refactor some common element types that appear in many of the different XML types, and pull them out to a common file so they can be reused and instead of redefined by the other schema files. For an example where these elements type are used, see https://github.com/Kitware/CDash/pull/2287.

Refactor common element types to resuable schema component

---

docs/release_process.md

A few brief updates to the release process docs in time for the release of CDash 3.5:
- It is no longer necessary to manually create annotated tags: #2152
- Updating the version on master causes unnecessary conflicts.  Instead, it's better to just merge the release branch back into master immediately to keep the version number reported on master up-to-date.
- Removed the line about locking the oldest release branch

Update release process docs

---

tailwind.config.js

DaisyUI injects an unnecessary message into the build log by default.  This PR disables the message.

Suppress spammy DaisyUI build log messages

---

docker/healthcheck.sh

Some users have reported problems using our production docker compose system when behind a proxy server due to the healthcheck failing.
One way to alleviate this problem is by passing the -k (--insecure) option to curl when attempting to ping a CDash site served over https.

Skip peer SSL certificate verification in healthcheck

---

app/Validators/Schemas/Configure.xsd

This PR follows up on https://github.com/Kitware/CDash/pull/2277 and introduces an initial schema for "Configure" XML file types accepted by the CDash submission process. The schema has been tested against all configure XML data files in the CDash repo.
The changes also pull out some common element types into a `common.xsd` file to be reused by the other schema files.

Add schema for `Configure` XML types

---

app/Validators/Schemas/Coverage.xsd

This PR is part of a series meant to improve the submission validation in CDash. The changes introduce an initial schema for "Coverage" XML file types accepted by the CDash submission process. The schema has been tested against all configure XML data files in the CDash repo.

Add schema for the `Coverage` xml submission type

---

app/Validators/Schemas/CoverageLog.xsd

This PR is part of a series meant to improve the submission validation in CDash. The changes introduce an initial schema for "CoverageLog" XML file types accepted by the CDash submission process. The schema has been tested against all ConfigureLog XML data files in the CDash repo.

Add schema for the `CoverageLog` XML submission type

---

app/Validators/Schemas/DynamicAnalysis.xsd

This PR is part of a series meant to improve the submission validation in CDash. The changes introduce an initial schema for "DynamicAnalysis" XML file types accepted by the CDash submission process. The schema has been tested against all such existing XML data files in the CDash repo.

Add schema for the `DynamicAnalysis` XML submissions type

---

app/Validators/Schemas/Project.xsd

This PR is part of a series meant to improve the submission validation in CDash. The changes introduce an initial schema for the "Project" XML file type accepted by the CDash submission process. As in the other PRs, this schema has been tested against all such existing XML data files in the CDash repo.

Add schema for the `Project` XML submission type

---

app/Validators/Schemas/Done.xsd

This PR is part of a series meant to improve the submission validation in CDash. The changes introduce an initial schema for the "Done" XML file type accepted by the CDash submission process. As in the other PRs, this schema has been tested against all such existing XML data files in the CDash repo.

Add schema for the `Done` XML submission type

---

app/Validators/Schemas/Update.xsd

This PR is part of a series meant to improve the submission validation in CDash. The changes introduce an initial schema for the "Update" XML file type accepted by the CDash submission process. As in the other PRs, this schema has been tested against all such existing XML data files in the CDash repo.

Add schema for the `Update` XML submission type

---

app/Validators/Schemas/Upload.xsd

This PR is part of a series meant to improve the submission validation in CDash. The changes introduce an initial schema for the "Upload" XML file type accepted by the CDash submission process. As in the other PRs, this schema has been tested against all such existing XML data files in the CDash repo.

Add schema for the `Upload` XML submission type

---

app/Validators/Schemas/Notes.xsd

This PR is part of a series meant to improve the submission validation in CDash. The changes introduce an initial schema for the "Notes" XML file types accepted by the CDash submission process. As in the other PRs, this schema has been tested against all such existing XML data files in the CDash repo.

Add schema for the `Notes` XML submission type

---

app/Validators/Schemas/Test.xsd

This PR is part of a series meant to improve the submission validation in CDash. The changes introduce an initial schema for the "Test" XML file type accepted by the CDash submission process. As in the other PRs, this schema has been tested against all such existing XML data files in the CDash repo.

Add schema for the `Test` XML submission type

---

app/Console/Commands/ValidateXml.php
app/Utils/SubmissionUtils.php
app/cdash/include/ctestparser.php
phpstan-baseline.neon

This PR expands on the initial implementation of the submission XML validator introduced in https://github.com/Kitware/CDash/pull/2277. The validator now supports parsing bigger XML files, can process multiple files per invocation, and provides better error handling. The logic for determining the submission XML file type has been pulled out to be used by both the submission parsers and the XML validation code.
To use the validator from a CDash container, run:
```
php <cdash_base>/artisan submission:validate <xml_file>...
```
where `<cdash_base>` is the path to the application root directory (e.g., `/cdash`), and `<xml_file>...` are one or more file paths to to be validated.

Improve the submission XML validation script

---

app/Utils/RepositoryUtils.php
phpstan-baseline.neon

GitLab started using a `/-/` component to act as a separator between project paths and project resources.

RepositoryUtils: fix GitLab URL generation

---

app/Models/Build.php
graphql/schema.graphql
tests/Feature/GraphQL/FilterTest.php

This PR adds the first field which allows for cyclic GraphQL queries, by adding a project field to the build type.

GraphQL: Add project field to build type

---

app/Console/Commands/CheckKey.php
app/Http/Controllers/ManageProjectRolesController.php
app/Http/Controllers/UserController.php
app/Utils/AuthTokenUtil.php
app/cdash/include/common.php
phpstan-baseline.neon

We currently use our own homemade password generation function.  This PR removes our homemade password generation function in favor of Laravel's officially supported password generation helper.

Generate passwords with Laravel helper

---

Dockerfile

The CDash UBI-based image currently fails to start with the following error:
```
(13)Permission denied: AH00058: Error retrieving pid file run/httpd.pid
AH00059: Remove it before continuing if it is corrupted.
```
This error is coming from an attempt to set up the prerequisites for Composer to be installed, which is inadvertently breaking httpd.
This PR resolves the issue by installing Composer the preferred way, by downloading it directly from the Composer website.

Change how Composer is installed for UBI-based image

---

resources/views/auth/passwords/email.blade.php
resources/views/auth/passwords/reset.blade.php
resources/views/auth/verify.blade.php

This was removed in #1351
Update these lingering references to use our base 'cdash' view instead.

Remove references to 'layouts.app' view

---

app/Http/Controllers/AdminController.php
app/Http/Controllers/TestController.php
app/Models/BuildTest.php
app/Models/TestMeasurement.php
app/Models/TestOutput.php
app/Utils/TestCreator.php
app/cdash/app/Controller/Api/QueryTests.php
app/cdash/app/Controller/Api/TestDetails.php
app/cdash/app/Controller/Api/TestGraph.php
app/cdash/app/Controller/Api/ViewTest.php
app/cdash/include/common.php
app/cdash/tests/test_namedmeasurements.php
app/cdash/tests/test_removebuilds.php
database/migrations/2024_07_09_025240_find_test_measurements_by_testid.php
tests/Feature/TestSchemaMigration.php

Test measurements are currently related to test outputs under the faulty assumption that the output of a test is directly related to the measurements collected for that test.  This means that if the measurements change but the output doesn't, CDash may report incorrect results.  This is presumably a very rare edge case which hasn't been identified before.  There are also other issues associated with the current form of our test output table, which I plan to fix in upcoming PRs.
This PR changes the relationship of test measurements to instead be related to test results, rather than deduplicated "test outputs".

Relate test measurements to tests instead of test outputs

---

app/Http/Controllers/TestController.php
app/Models/Build.php
app/Models/Test.php
app/Models/TestOutput.php
app/Providers/AuthServiceProvider.php
app/Utils/TestCreator.php
app/cdash/app/Controller/Api/BuildTestApi.php
app/cdash/app/Controller/Api/TestGraph.php
app/cdash/app/Controller/Api/ViewTest.php
app/cdash/app/Model/Build.php
app/cdash/include/Messaging/Topic/MissingTestTopic.php
app/cdash/include/Messaging/Topic/TestFailureTopic.php
app/cdash/tests/CMakeLists.txt
app/cdash/tests/case/CDash/Messaging/Topic/TestFailureTopicTest.php
app/cdash/tests/test_multiplelabelsfortests.php
graphql/schema.graphql
phpstan-baseline.neon
routes/web.php
tests/Feature/GraphQL/TestTypeTest.php

Our current representation of test results is complex, and will take a significant amount of work to expose via the GraphQL API safely.  This PR starts that process by exposing test names and statuses via the GraphQL API.  In addition, this PR renames the `BuildTest` model to `Test`.  The underlying table will be renamed at a future point.

Add basic Test type to GraphQL API

---

app/Models/Build.php

https://github.com/Kitware/CDash/pull/2330 fixed the inverse relationship between the Build and Project models after the 3.5 release branch was created.  The broken relationship breaks image test results in 3.5.  This PR backports the fix in https://github.com/Kitware/CDash/pull/2330 to the 3.5 release branch.

Fix incorrect relationship between Build and Project models

---

config/ldap.php

To use anonymous binding, it is currently necessary to set `LDAP_USERNAME` and `LDAP_PASSWORD` to empty strings.  This PR changes the default values to empty strings, so anonymous binding is the default behavior.

LDAP: Default to anonymous binding

---

app/Jobs/ProcessSubmission.php
app/cdash/tests/test_donehandler.php
phpstan-baseline.neon

Prior to this commit, remote workers would retain a copy of each parsed submission file in their storage/app/inbox/ directory.

Delete submission files from remote workers

---

app/Ldap/Rules/FilterRules.php
app/Utils/LdapUtils.php
config/ldap.php
docs/authentication.md
phpstan-baseline.neon
resources/js/components/EditProject.vue
tests/Feature/LdapIntegration.php

In response to user feedback about the new LDAP-based project membership feature added in https://github.com/Kitware/CDash/pull/2282, this PR changes the project LDAP field to accept a filter instead of a group name for consistency with our existing `LDAP_FILTERS_ON` environment variable.
This PR also addresses an issue with `LDAP_FILTERS_ON` related to the switch from Adldap2 in #2206 and reverts the environment variable rename from `LDAP_HOSTS` to `LDAP_HOST` to maintain backwards compatibility with existing systems.

Use filter-based approach for LDAP project membership

---

app/cdash/tests/kwtest/kw_db.php

The test suite currently prints every MySQL query to the test log.  This PR removes the unnecessary logging statement to bring the MySQL test output in line with the Postgres test output.

Remove MySQL query info from test output

---

app/Ldap/Rules/FilterRules.php
app/Utils/LdapUtils.php
config/auth.php
docs/authentication.md

Our LDAP library, LdapRecord, supports multiple LDAP specs.  This PR adds support for FreeIPA integration for clients wishing to integrate CDash with FreeIPA LDAP servers.

Add FreeIPA LDAP integration

---

app/Models/Build.php
app/Models/BuildGroup.php
app/Models/BuildGroupPosition.php
app/cdash/tests/case/CDash/MultipleSubprojectsEmailTest.php
app/cdash/tests/test_buildmodel.php
database/migrations/2024_08_27_173953_build2group_foreign_key_constraints.php
database/migrations/2024_08_27_191729_buildgroupposition_relationships.php

This PR is incremental progress towards an entirely Eloquent-based query system, and ultimately an introduction of build groups to the GraphQL API.  In addition to setting up Eloquent relationships between build group-related models, this PR also adds additional constraints and indexes for better performance and data integrity.

Set up basic build group Eloquent relationships

---

tests/Feature/GraphQL/BuildTypeTest.php
tests/Feature/GraphQL/FilterTest.php
tests/Feature/GraphQL/ProjectTypeTest.php
tests/Feature/GraphQL/SiteTypeTest.php
tests/Feature/GraphQL/TestTypeTest.php
tests/Feature/LdapIntegration.php
tests/Feature/ProjectPermissions.php
tests/Feature/RouteAccessTest.php
tests/Traits/CreatesProjects.php

The functions used to create projects for much of the test suite currently return legacy project models, even though most tests immediately convert them to Eloquent models.  This make the test-writing process extra painful for most tests, and is completely unnecessary.
This PR changes the project creation functions to instead return Eloquent projects.  This also removes some of the last references to the InitialSetup method in the legacy project model, which paves the way for that method to be completely removed in the follow-up to #2396.

Use Eloquent Project model for test project creation

---

cypress.config.js

https://github.com/Kitware/CDash/pull/2263 bumped the default Cypress timeout, which reduced the test flakiness, but did not eliminate it entirely.  This PR bumps the limit again in an attempt to resolve the issue.  In the future, I plan to rewrite the flaky tests.

Increase default Cypress timeout

---

app/Http/Controllers/OAuthController.php
phpstan-baseline.neon
tests/Feature/LoginAndRegistration.php

Per a bug report, if an OAuth account name doesn't use a real name, CDash will 500 if a space doesn't exist in the name.
Check for the space before trying to separate into first and last names. If no space, use the whole string as the first name.
Fixes: #2435

Stop assuming "full name" in OAuth

---

app/cdash/tests/CMakeLists.txt
graphql/schema.graphql
tests/Feature/GraphQL/TestMeasurementTypeTest.php

This PR exposes the `testMeasurement` relationship on the `Test` type in the GraphQL API in preparation for upcoming UI changes.

Add TestMeasurement type to GraphQL API

---

database/migrations/2024_04_17_183212_remove_test_table.php

#2148 introduced a large migration which has proven to be problematic for CDash instances with many tests.  This PR breaks the single large update statement into a batched update process where updates are performed in groups of 5000 rows at a time.

Use batch updates for test table migration

---

app/Http/Controllers/AbstractController.php
app/Http/Controllers/AdminController.php
app/Http/Controllers/BuildController.php
app/Http/Controllers/CoverageController.php
app/Http/Controllers/DynamicAnalysisController.php
app/Http/Controllers/IndexController.php
app/Http/Controllers/ProjectOverviewController.php
app/Http/Controllers/SubProjectController.php
app/Http/Controllers/TestController.php
app/Providers/AppServiceProvider.php
phpstan-baseline.neon

The `angular_view()` method was previously dynamically attached to the `response()` facade by Laravel.  This PR moves it to the AbstractController class.  This change has two main benefits:
1. PHPStan is able to understand the method better
2. Any project or build information is now passed into the view automatically by building off of the existing `view()` method.

Move angular_view function to AbstractController

---

app/cdash/app/Controller/Api/ViewTest.php
phpstan-baseline.neon

https://github.com/Kitware/CDash/pull/2390 accidentally changed the formatting of the labels attribute in the viewTest.php API response.

Fix viewTest.php labels column display

---

database/migrations/2024_09_18_131622_builderror_indexing.php

The `builderror` table currently only has indexes on individual columns.  Almost all queries search the table by `buildid` and `type` together.  Adding this index resulted in a significant reduction in processing time for submissions to a large production CDash instance.

Add index to builderror(buildid,type,crc32)

---

app/cdash/tests/CMakeLists.txt
graphql/schema.graphql
tests/Feature/GraphQL/NoteTypeTest.php

This PR continues our ongoing effort to build out the new GraphQL API by adding a Note type to the API.

Add Note type to GraphQL schema

---

graphql/schema.graphql
resources/js/components/AllProjects.vue
tests/Feature/GraphQL/ProjectTypeTest.php

`/projects` currently shows a loading indicator briefly on large production instances with many builds.  This PR attempts to address the issue by adding a `buildCount` field to the Project type in the GraphQL API, which allows filtered count queries to be executed more efficiently.  I plan to add similar fields for build errors/warnings, tests, etc in the future.

Improve `/projects` load performance

---

app/Providers/AppServiceProvider.php

CDash currently requires all production sites to operate over HTTPS, even if the `APP_URL` has a HTTP prefix.  There is no technical reason why this requirement is necessary at this point, and some users may desire to forgo setting up certificates for a small internal instance, such as #2457.  This PR removes this requirement and fully respects the `APP_URL` as configured.

Allow production sites to operate over HTTP

---

database/migrations/2024_09_23_133018_dynamic_analysis_foreign_keys.php

This PR adds a foreign-key constraint to the `dynamicanalysisdefect` table, as well as associated indexing, in support of #2093.  Dynamic analysis results are now cleaned up 100% automatically when their associated build results are removed.

Add foreign-key constraints to dynamic analysis tables

---

app/Enums/BuildMeasurementType.php
app/Models/Build.php
app/Models/BuildMeasurement.php
app/Providers/GraphQLServiceProvider.php
app/cdash/tests/CMakeLists.txt
config/app.php
database/migrations/2024_09_24_184156_build_measurements_table.php
graphql/schema.graphql
tests/Feature/GraphQL/BuildMeasurementTypeTest.php

In https://github.com/Kitware/CDash/issues/2395, a user requested for the instrumentation data collected by CMake and CTest in [CMake issue 26099](https://gitlab.kitware.com/cmake/cmake/-/issues/26099)to be stored in CDash.  This PR sets up the infrastructure needed to store and retrieve "build measurements" in CDash.  Our existing "test measurement" functionality will be used to store the test instrumentation data.  A future PR will introduce logic to populate the new build measurements table during the submission parsing process.

Add build measurement backend and API

---

Dockerfile

PHP's OPcache extension is recommended for most PHP systems, but is not currently installed in our official Docker images.  This PR installs OPcache in each of our Docker images.  In a blank development environment, the overhead cost per request was observed to be 70% less with OPcache installed.  This is particularly important for pages powered by our new GraphQL API, because this overhead cost is incurred for each pagination request.  In my human testing, pages felt considerably faster as I clicked around on the site.
Apache Bench results for an empty development environment:
<details>
<summary>Without OPcache:</summary>
```
$ ab -n 1000 http://localhost:8080/projects
This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, …
```

Install OPcache PHP extension in Docker by default

---

docs/install.md

Most of the install steps in `install.md` are no longer necessary since `install.sh` runs all of them.  Additionally, the `/install` route was removed entirely in #2279, in favor of using environment variables exclusively.
Closes #2464

Remove outdated install instructions

---

app/cdash/include/common.php

The `utf8_encode()` function is [deprecated](https://www.php.net/manual/en/function.utf8-encode.php).  PHPStan is currently failing for many of our monthly dependency updates because various dependencies got rid of a PHP 7.2 [polyfill](https://github.com/symfony/polyfill-php72) dependency.  This PR updates our two usages of `utf8_encode()` to use `mb_convert_encoding()` instead, which will address the PHPStan failures in some of our dependencies.

Update usages of deprecated utf8_encode() function

---

app/Http/Controllers/CoverageController.php

Prior to this commit, clicking on the "Manage project coverage" from the /user page for an admin would result in
You don't have the permissions to access this page
With this change, the user is now presented with a drop-down menu where they can select a project to manage.

Fix "Manage project coverage" from /user

---

app/GraphQL/Scalars/NonNegativeSeconds.php
graphql/schema.graphql
resources/js/components/BuildTestsPage.vue
resources/js/components/shared/DataTable.vue
resources/js/components/shared/FilterRow.vue
tests/Feature/GraphQL/TestTypeTest.php
tests/cypress/component/data-table.cy.js

https://github.com/Kitware/CDash/pull/2439 introduced a new tests page which will eventually supersede `viewTest.php`.  This PR adds the time and details columns displayed on viewTest.php to the new tests page.  As part of this work, test details and running time are now available via the GraphQL API.

Add details and time columns to new tests page

---

database/migrations/2024_08_24_160326_label2test_relationship_refactor.php

#2390 added a migration which affects every row in the `label2test` table.  MySQL is very inefficient at bulk updates, and real-world test have shown that the running time can be reduced by using small batches.  This PR updates the migration to use a batching approach for both MySQL and Postgres.

Migrate label2test rows in batches

---

database/migrations/2024_07_01_130230_build2test_id_column.php
database/migrations/2024_07_09_025240_find_test_measurements_by_testid.php
database/migrations/2024_08_24_160326_label2test_relationship_refactor.php

Users have reported issues migrating to post-3.5 commits on master, such as in #2448, due to an inconsistency between database schemas between CDash 2 and 3.  This PR resolves the issue by changing the type of the `build2test` `id` column to an unsigned bigint, in accordance with Laravel tradition.  This also avoids potential overflow concerns.  I plan to make a series of future PRs to change the rest of the ID columns to unsigned bigints.

Change build2test id column type to bigint

---

resources/js/components/shared/FilterRow.vue

The new GraphQL-based filters interface currently shows the raw GraphQL field name as the filter name.  This PR improves the UI by rendering the filter names in Title Case.

Make filter names more user friendly

---

app/Http/Controllers/CoverageController.php
app/cdash/include/common.php
phpstan-baseline.neon

#2396 inadvertently used the incorrect syntax to access values from a pivot table, which led to users being unable to perform admin actions on AngularJS pages.

Fix project role field in standard API response

---

graphql/schema.graphql
tests/Feature/GraphQL/SiteTypeTest.php

Fixes #2502.  The type for the latitude and longitude fields is a string in the database but a float in the API, which causes failures when empty strings are present.  This PR converts the API type to a string to resolve the issue.  In the future, it may be worth creating a custom scalar type for lat/long information.

Fix blank lat/long GraphQL Site fields

---

app/Http/Controllers/ManageProjectRolesController.php
phpstan-baseline.neon

This commit relaxes the constraints used when decided who should receive an email to when a project admin uses the "Email all site maintainers" form.
We will now email all users with the "Site maintainer" role, even if they are not currently marked as maintaining any specific site.

Email all site maintainers

---

app/Providers/AppServiceProvider.php

https://github.com/Kitware/CDash/pull/2458 removed a line which was believed to have no effect.  After deploying a recent version of CDash to a production system based on Kubernetes, it was discovered that Laravel automatically changes the protocol to `http://` if the incoming request is a HTTP request, even if the `APP_URL` starts with `https://`.  This PR addresses the issue by forcing Laravel to respect the protocol specified by the `APP_URL` environment variable.

Force URL to start with HTTPS if APP_URL starts with https://

---

database/migrations/2024_08_24_160326_label2test_relationship_refactor.php
database/migrations/2024_10_13_160937_buildinformation_to_build_table.php

Users have reported compatibility issues with the recent batched update approach used in several migrations, including #2496.  MySQL 8.3 does not support LIMIT clauses on multi-table update statements.
This PR changes the batching approach used for the two migrations affected by these issues to avoid the problematic syntax.

Change migration batching approach to avoid problematic syntax on MySQL

---

app/Models/Build.php
app/Models/Coverage.php
app/cdash/tests/CMakeLists.txt
graphql/schema.graphql
tests/Feature/GraphQL/CoverageTypeTest.php

This PR continues our ongoing effort to expose major components of the CDash database via the GraphQL API.  As of now, these changes are rather useless since the filename is not stored in the Coverage table.  A future PR will migrate the filename to the underlying coverage table, and add a filename field to the Coverage GraphQL type.

Add Coverage type to GraphQL API

---

resources/views/maintenance.blade.php

Given that some migrations may take extended periods of time for large systems, it is likely that many users will be exposed to the CDash maintenance page eventually.  This PR cleans up the maintenance page UI by centering the text, adding a CDash logo, and adding text indicating that the page will reload automatically.
| **Before**  | **After** |
|---|---|
| ![image](https://github.com/user-attachments/assets/866418f9-70a1-44cc-8739-715487637b92) | ![image](https://github.com/user-attachments/assets/8a487acc-9eda-4f22-ab9c-c6017ef86c01) |

Improve maintenance page UI

---

app/Http/Controllers/ManageProjectRolesController.php
phpstan-baseline.neon

Prior to this commit, attempting to email multiple site maintainers from the manageProjectRoles.php page would result in the following error:
```
Email "user1@example.com, user2@example.com" does not comply with addr-spec of RFC 2822.
```
Fixes #2450
Follow-up to #2505

Fix emailing multiple site maintainers

---

app/GraphQL/Directives/FilterDirective.php
phpstan-baseline.neon
tests/Feature/GraphQL/FilterTest.php

This PR adds a basic "contains" filter to the GraphQL API.  Users should note that indexing is not helpful for queries using this filter, potentially leading to slowness for some queries.

Add GraphQL "contains" filter

---

app/Models/Build.php
app/Models/Label.php
app/Models/Test.php
graphql/schema.graphql
phpstan-baseline.neon
tests/Feature/GraphQL/BuildTypeTest.php
tests/Feature/GraphQL/TestTypeTest.php

This PR continues our ongoing effort to expose major parts of the CDash database schema via GraphQL by adding a new `Label` type, as well as label relationships for the `Build` and `Test` types.

Expose Labels via GraphQL API

---

.github/workflows/build-latest-images.yml
.github/workflows/release.yml

This PR attaches [SBOMs](https://docs.docker.com/build/ci/github-actions/attestations/#sbom) to all new images pushed to Docker Hub.

Enable SBOM generation for Docker images

---

database/migrations/2024_04_17_183212_remove_test_table.php
database/migrations/2024_07_09_025240_find_test_measurements_by_testid.php

Boost performance for migrations scripts

Speed up long-running migrations

---

database/migrations/2024_08_24_160326_label2test_relationship_refactor.php

As reported in https://github.com/Kitware/CDash/pull/2552#issuecomment-2461877218, #2496 introduced a divide-by-zero error in the migration `2024_08_24_160326_label2test_relationship_refactor`.  This PR fixes the issue.

Fix divide-by-zero error in label2test migration

---

phpstan-baseline.neon
phpstan.neon

After using PHPStan for a while, our type coverage is now far more complete and most of the worst issues have been fixed.  The codebase is now in a state where many of the errors reported by PHPStan level 9 are useful, instead of being a nuisance.  If this proves to be incorrect after a few weeks or months of testing, we can reduce our rule level back down to level 8.

Bump PHPStan rules to level 9

---

resources/views/cdash.blade.php

CDash currently uses HTML directives to disallow web scraping.  This prevents CDash sites from being indexed by search engines.  This PR removes the web scraper directives, and adds a description directive, as recommended by Google's "Lighthouse" web optimization tool.

Remove unnecessary web scraper directives

---

app/cdash/log/README

It has been a while since the legacy logs directory was last used, so this PR cleans up the last remaining traces of it.

Remove legacy logs directory

---

composer.json
composer.lock

Addresses https://github.com/advisories/GHSA-gv7v-rgg6-548h.

Update Laravel to v10.48.23

---

app/cdash/include/common.php
database/migrations/2024_11_18_113619_configure_error_foreign_key.php

This PR adds a foreign-key constraint to the `configureerror` table in support of #2093.

Add foreign-key constraint to configureerror table

---

app/Utils/DatabaseCleanupUtils.php

Remove DELETE statements for tables that are now handled by cascading deletions.
* build2uploadfile was fixed in #1657
* label2buildfailure was fixed in #2452
* dynamicanalysisdefect and label2dynamicanalysis were fixed in #2455

Eliminate unnecessary DELETE statements in removeBuilds()

---

routes/web.php

The redirect for `testDetails.php` currently throws a 500 error.  This PR resolves the error by querying the correct database column.

Fix `testDetails.php` redirect

---

public/upload/.gitignore

Uploaded files have been stored in the storage directory for some time now, and there is no longer a need to keep the previous uploads directory around.

Delete unused uploads directory

---

database/migrations/2024_11_18_113619_configure_error_foreign_key.php

CDash databases that were initialized in v2.5 or older have a type mismatch between configure.id (int) and configureerror.configureid (bigint). See #506 for more context about where this mismatch occurred.
Update the recent migration so that these types match and we can apply the foreign key successfully.

Ensure configureerror FK types match

---

.env.example
app/Http/Controllers/CoverageController.php
app/Models/Project.php
app/cdash/app/Controller/Api/ViewProjects.php
app/cdash/app/Model/Project.php
app/cdash/include/common.php
config/cdash.php
database/migrations/2024_11_22_160106_drop_googletracker_column.php
phpstan-baseline.neon
resources/js/vue/components/EditProject.vue

CDash historically supported tracking users via a Google Analytics tracking link.  That functionality has been removed for some time now.  This PR removes the last few traces of that functionality.

Remove last traces of google analytics tracker

---

resources/js/vue/components/ProjectSitesPage.vue

This PR fixes an issue introduced in #2583 where sites without any attached site information prevent the entire page from rendering properly.  I plan to add thorough e2e tests for this page once I finish getting Laravel Dusk set up.

Improve handling of sites with no information

---

resources/js/vue/app.js

While writing end-to-end tests for the project sites page overhauled in #2583 as a proof-of-concept for the upcoming addition of Laravel Dusk, I discovered that the project sites page does not paginate correctly.  This PR fixes the issue.

Fix project sites page pagination

---

database/migrations/2024_11_18_113619_configure_error_foreign_key.php
database/migrations/2024_11_20_144306_buildfailure2argument_foreign_key.php
database/migrations/2024_11_20_144307_updatefile_foreign_key.php
database/migrations/2024_11_20_144308_test2image_foreign_key.php
phpstan-baseline.neon

Perform batch deletion of invalid records before applying new foreign keys

Perform batch deletion of invalid records before applying new foreign keys

---

app/cdash/tests/kwtest/kw_web_tester.php
database/seeds/DatabaseSeeder.php
phpstan-baseline.neon
tests/Traits/CreatesSubmissions.php

There is currently no way to create submissions programmatically in the new part of the test suite.  Given that various upcoming features will need test submissions to be made, this PR moves a preexisting database seeder method to a test trait where it can be used more widely.  I also replaced the legacy `submission()` method which was previously the preferred way to make submissions in the old part of the test suite.

Add submission trait to test environment

---

app/Utils/DatabaseCleanupUtils.php
phpstan-baseline.neon

Replace custom SQL with Laravel relationships to identify configure and note rows that are only being used by builds that are about to be deleted.

Use Laravel relationships to remove configure and note rows

---

app/cdash/xml_handlers/note_handler.php

Notes with no text are currently logged at the `info` level, which clutters the logs with unnecessary messages.  This PR demotes that message to the lowest level (`debug`).

Demote "No note text for..." log message to debug level

---

.env.dev
docker/docker-compose.dev.yml

Email testing is currently difficult in the CDash development environment, with developers having to set up their own local email servers for testing purposes.  This PR adds a [mailpit](https://mailpit.axllent.org) container to the Docker development environment so developers can inspect the emails sent by a local CDash server at http://localhost:8025.

Add mock email server to development environment

---

app/Models/BuildUpdate.php
app/Models/CoverageFile.php
app/Models/RichBuildAlert.php
app/Models/RichBuildAlertDetails.php
app/Utils/DatabaseCleanupUtils.php
phpstan-baseline.neon

This commit introduces the use of Eloquent relationships to remove the following types of shared records:
* buildfailure
* buildfailuredetails
* coveragefile

Replace custom SQL in removeBuilds with Eloquent relationships

---

composer.json

The default Laravel starter kit includes Composer hooks which make it easy to get a Laravel project set up.  These hooks are no longer useful for CDash.

Remove unnecessary Composer hooks

---

app/cdash/tests/kwtest/kw_web_tester.php
composer.json
composer.lock

[`laravel/legacy-factories`](https://github.com/laravel/legacy-factories) provides support for the legacy Laravel `factory()` method which was removed in Laravel 8.x.  This PR refactors the last remaining usage of this legacy method and removes the dependency.

Remove `laravel/legacy-factories` dependency

---

app/cdash/include/dailyupdates.php
app/cdash/include/log.php
app/cdash/xml_handlers/upload_handler.php
phpstan-baseline.neon

The `cdash_unlink()` helper function is only used in a handful of locations, and most of those locations do not appear to benefit from its behavior.  This PR removes the `cdash_unlink()` helper and replaces it with either the raw PHP `unlink()` command or Laravel's Storage facade's delete helper.  In the future, I plan to create a dedicated Laravel temporary disk which will allow us to use the storage facade for all file I/O operations.

Remove `cdash_unlink()` helper

---

app/cdash/include/Test/CDashTestCase.php
app/cdash/include/Test/CDashUseCaseTestCase.php
app/cdash/tests/case/CDash/Model/BuildErrorTest.php
app/cdash/tests/case/CDash/NightlyTimeTest.php
phpstan-baseline.neon
tests/Unit/app/Validators/PasswordTest.php

The [upgrade](https://github.com/Kitware/CDash/pull/1866) of PHPUnit to 10 and beyond is currently blocked by our usage of PHPUnit's deprecated `setMethods()` method which was removed in PHPUnit 10.  This PR addresses all of our remaining usages of `setMethods()`, which clears the way for a PHPUnit upgrade in the near future.

Replace usages of deprecated `setMethods()` method

---

composer.json
composer.lock

[`nyholm/psr7`](https://github.com/Nyholm/psr7) appears to be unused.  This PR removes it from our list of dependencies.

Remove `nyholm/psr7` dependency

---

app/Utils/AuthTokenUtil.php

In #2614, the `user` table was renamed to `users`.  Update the SQL query used in the AuthTokenUtil to use the new table instead of the old name.
Fixes: #2655

Fix AuthTokenUtil SQL query

---

composer.json
composer.lock
phpstan-baseline.neon
tests/Feature/GraphQL/ProjectTypeTest.php
tests/Feature/GraphQL/SiteTypeTest.php
tests/Feature/GraphQL/TestTypeTest.php
tests/Feature/RouteAccessTest.php

The upgrade to PHPUnit 10 was previously blocked by a series of issues with deprecated methods which were removed in PHPUnit 10.  Dependabot [closed](https://github.com/Kitware/CDash/pull/1866) the PR because PHPUnit 11 is now available, but can't be updated to because it requires Laravel 11.  This PR manually updates PHPUnit to version 10.

Bump PHPUnit to 10.5.40

---

app/Console/Kernel.php
app/Jobs/NotifyExpiringAuthTokens.php
app/Mail/AuthTokenExpired.php
app/Mail/AuthTokenExpiring.php
app/Models/AuthToken.php
app/Models/User.php
app/cdash/tests/CMakeLists.txt
resources/views/email/auth-token-expired.blade.php
resources/views/email/auth-token-expiring.blade.php
tests/Feature/Jobs/NotifyExpiringAuthTokensTest.php
tests/Feature/Jobs/PruneAuthTokensTest.php
tests/Feature/Mail/AuthTokenExpiredTest.php
tests/Feature/Mail/AuthTokenExpiringTest.php

Authentication tokens currently expire silently, leading users to discover that they need to be updated once things start failing.  This PR improves the feature by sending email notifications to the token owner each day for the 7 days preceding a token's expiration date.

Send email notifications for expiring auth tokens

---

tests/Feature/GraphQL/BuildTypeTest.php

#2664 allowed CTest to have more flexibility regarding the ordering of tests.  That exposed an issue with the `BuildTypeTest` which relied upon more than just data it created.  This PR resolves the issue by restricting the test to use only the data it creates.

Restrict build GraphQL test to only the projects it creates

---

app/Http/Controllers/SubmissionController.php
app/Jobs/ProcessSubmission.php
app/cdash/include/ctestparser.php
phpstan-baseline.neon

When given a non-xml submission file, catch the exception of the bad submission and only reject the submission of the Validate setting is enabled.
Fixes: #2662

Account for non-xml submission objects

---

graphql/schema.graphql
resources/js/vue/app.js
resources/js/vue/components/BuildTestsPage.vue
resources/js/vue/components/shared/BuildSummaryCard.vue
resources/js/vue/components/shared/BuildSummaryCardStepSummary.vue

Most build-specific pages currently display a basic table of information about that build.  For example:
This primitive approach uses a significant amount of vertical space, while wasting most of the horizontal space available at the top of the page.  Additionally, this table does not display site information or build history information, which means that it is often augmented by UI elements which take up additional vertical space.
This PR introduces a new reusable "build information card" Vue component which accepts a build ID and displays a large amount of summary information about a build and associated site in a collapsible format.
Example of the card in its closed form:
Example of the same card in its open form:
This PR implements the basic functionality, but there are a few future …

Add reusable build information card

---

database/migrations/2025_01_28_154916_authtoken_default_scope.php

Fixes https://github.com/Kitware/CDash/issues/2678 by defaulting all pre-3.2 tokens to be full access tokens.

Set default scope for pre-3.2 auth tokens

---

app/GraphQL/Mutations/AbstractMutation.php
app/GraphQL/Mutations/ClaimSite.php
app/GraphQL/Mutations/UnclaimSite.php
app/cdash/tests/CMakeLists.txt
graphql/schema.graphql
phpstan-baseline.neon
resources/js/vue/app.js
resources/js/vue/components/SitesIdPage.vue
resources/views/site/view-site.blade.php
tests/Browser/Pages/SitesIdPageTest.php
tests/Feature/GraphQL/SiteTypeTest.php

As discussed in #2659, the "claim site" feature is currently broken.  This PR supersedes the previous functionality by adding a "claim site" button to the site overview page.  I intend to make a separate PR to add similar buttons to the project sites page.  In addition, I plan to remove `editSite.php` and move the remaining functionality to the site overview page in a separate upcoming PR.  That PR will also remove the broken claim site logic.
Closes #2659.

Add "claim site" functionality to site overview page

---

tests/Browser/Pages/SitesIdPageTest.php

The new browser test `SitesIdPageTest` is somewhat flaky in CI because it does not wait for the elements being checked to be visible.  This is the major downside to using Laravel's Dusk Selenium wrapper instead of Cypress, which automatically waits for elements to be visible before all assertions.  This PR will hopefully resolve the flakiness by waiting for the site history column to be displayed before making assertions.

Wait for items to be displayed in SitesIdPageTest

---

app/Models/BuildGroup.php
app/cdash/app/Model/BuildGroup.php
database/migrations/2025_02_07_140349_nullable_buildgroup_description.php

The `buildgroup` table's `description` column is not-null for systems created since the switch to Laravel, but this column may be nullable for older systems.  Given that the description is not a mandatory field, it makes sense to make this field nullable for all systems.  For older systems, nothing will change.  For newer systems, the buildgroup description will now be nullable.

Make buildgroup description column nullable

---

app/Console/Commands/CleanDatabase.php
app/Http/Controllers/ManageProjectRolesController.php
app/cdash/app/Model/Project.php
app/cdash/include/dailyupdates.php
app/cdash/public/manageProjectRoles.xsl
app/cdash/tests/test_removebuilds.php
database/migrations/2025_02_06_220212_drop_dailyupdatefile_table.php
phpstan-baseline.neon

The `dailyupdatefile` table is currently only used to display a list of users who have committed to the project recently but don't have a CDash account.  As we rethink what it means for CDash to be integrated with version control systems, it seems unlikely that we will want CDash to be responsible for interacting with version control systems directly, instead relying upon CTest to include the necessary information in the Update step.

Remove `dailyupdatefile` table

---

resources/css/common.css

The current site header scrolls with the page content.  This behavior is not ideal because users who have navigated to the bottom of a long list of builds/tests/etc then have to scroll all the way to the top to access the menu options.  This PR sticks the page header to the top of the viewport on scroll, meaning that menu items will be accessible all the time.

Stick header to top of screen on scroll

---

app/Http/Submission/Traits/UpdatesSiteInformation.php
app/Models/SiteInformation.php
app/cdash/tests/CMakeLists.txt
app/cdash/tests/case/CDash/TestUseCaseTest.php
app/cdash/xml_handlers/build_handler.php
app/cdash/xml_handlers/configure_handler.php
app/cdash/xml_handlers/coverage_handler.php
app/cdash/xml_handlers/coverage_junit_handler.php
app/cdash/xml_handlers/dynamic_analysis_handler.php
app/cdash/xml_handlers/note_handler.php
app/cdash/xml_handlers/testing_handler.php
app/cdash/xml_handlers/testing_j_unit_handler.php
app/cdash/xml_handlers/upload_handler.php
phpstan-baseline.neon
tests/Browser/Pages/SitesIdPageTest.php
tests/Feature/GraphQL/Mutations/UpdateSiteDescriptionTest.php
tests/Feature/Traits/UpdatesSiteInformationTest.php

Site information is currently mistakenly saved on every submission, regardless of whether any information actually changed.  This PR fixes the issue and adds tests to prevent it from occurring again.

Fix buggy site information deduplication behavior

---

app/Http/Controllers/BuildController.php
app/Http/Controllers/ManageProjectRolesController.php
app/Http/Controllers/SubscribeProjectController.php
app/Http/Controllers/UserController.php
app/cdash/app/Controller/Api/Index.php
app/cdash/app/Model/Build.php
app/cdash/app/Model/Subscriber.php
app/cdash/app/Model/SubscriberInterface.php
app/cdash/app/Model/User.php
app/cdash/app/Model/UserProject.php
app/cdash/include/dailyupdates.php
app/cdash/public/manageProjectRoles.xsl
app/cdash/public/subscribeProject.xsl
app/cdash/tests/test_email.php
app/cdash/tests/test_manageprojectroles.php
database/migrations/2025_02_12_204506_drop_user2repository_table.php
phpstan-baseline.neon
resources/js/angular/views/partials/build.html
resources/views/admin/ajax-find-user-project.blade.php
resources/views/auth/profile.blade.php

User credentials are no longer used for anything but matching email addresses to themselves through convoluted code paths.  This PR removes all references to user credentials in the UI and deletes the underlying `user2repository` table.

Remove obsolete user credentials feature

---

tests/Browser/Pages/SitesIdPageTest.php

`SitesIdPageTest` is currently flaky because the site history list is sometimes not fully rendered before the assertions begin running.  This PR adds an explicit wait for the history items to be rendered.

Wait for element to be visible in SitesIdPageTest

---

app/Utils/Stack.php
app/cdash/xml_handlers/abstract_xml_handler.php
app/cdash/xml_handlers/build_handler.php
app/cdash/xml_handlers/configure_handler.php
app/cdash/xml_handlers/coverage_handler.php
app/cdash/xml_handlers/coverage_junit_handler.php
app/cdash/xml_handlers/coverage_log_handler.php
app/cdash/xml_handlers/dynamic_analysis_handler.php
app/cdash/xml_handlers/note_handler.php
app/cdash/xml_handlers/testing_handler.php
app/cdash/xml_handlers/testing_j_unit_handler.php
app/cdash/xml_handlers/update_handler.php
app/cdash/xml_handlers/upload_handler.php
phpstan-baseline.neon

This PR pulls out some of the logic in https://github.com/Kitware/CDash/pull/2612 for matching full XML paths into a separate PR in anticipation of several upcoming PRs.  By specifying the full XML path for an element, the exact element being targeted is more clear.  For the sake of example, I used the new path method to locate all of the `<Site>` elements.

Add XML path matching method to XML handlers

---

composer.json
composer.lock

`http-interop/http-factory-guzzle` appears to be unused.  This PR removes it from our requirements list.

Remove unused `http-factory-guzzle` dependency

---

.github/workflows/ci.yml

The "Publish Images" job [recently](https://github.com/Kitware/CDash/actions/runs/12956371942) started failing due to an issue with arm64/amd64 cross-compilation.  This was not caught by the regular "Build Images" CI job because it does not build for both arm64 and amd64.

Build arm64 images in CI

---

config/cdash.php
package-lock.json
package.json

3.8 was never merged back into master, which is why the version was still 3.7.

Bump version to 3.9.0

---

resources/js/angular/views/manageBuildGroup.html

Wildcard buildgroup rules only make sense in the context of "daily" groups.
The rules for dynamic ("latest") buildgroups are defined on a separate tab.

Don't show dynamic buildgroups on the wildcard tab

---

database/migrations/2025_03_21_201854_updatefile_filename_index.php

[This](https://github.com/Kitware/CDash/blob/5de4c0123b89a80c0968d14586f21215f12baeff/app/cdash/app/Lib/Repository/GitHub.php#L563) query was found to be responsible for a large fraction of the database wait time for a production CDash instance.  By indexing `updatefile(filename)`, the aforementioned check is much cheaper and no longer accounts for a disproportionate amount of the overall submission time.

Improve submission times by indexing `updatefile(filename)

---

docker/docker-entrypoint.sh

Several tests have been particularly flaky recently due to scheduled jobs running simultaneously and interfering with the test environment.  I've also run into issues with scheduled jobs deleting carefully constructed data while developing locally.  This PR disables scheduled jobs entirely when not in production mode to resolve these issues.

Disable scheduled jobs when not in production

---

app/Validators/Schemas/common.xsd

Following the MR in CMake found here:
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9860
Add ModelName as a valid attibute in the schema checker. https://github.com/Kitware/CDash/issues/2752 has been created for future work to ensure that the information is properly stored and displayed.

Add ModelName as valid Site attribute

---

app/Http/Controllers/BuildController.php
phpstan-baseline.neon

Coverage results with no lines covered or uncovered currently produces a divide-by-zero error when viewing a build.  This PR fixes the issue by returning zero if the divide-by-zero case would occur.

Fix divide-by-zero error when coverage results have no lines

---

app/Models/SiteInformation.php
app/cdash/tests/case/CDash/TestUseCaseTest.php
database/migrations/2025_03_31_124158_support_model_name_on_site.php
graphql/schema.graphql
phpstan-baseline.neon
resources/js/vue/components/SitesIdPage.vue
resources/js/vue/components/shared/BuildSummaryCard.vue
tests/Browser/Pages/SitesIdPageTest.php
tests/Feature/GraphQL/SiteTypeTest.php

Add the updates which will allow the new information in the CMake XML files for the model name of the processor to be displayed on the CDash page for the site.
Fixes #2752

Handle processor Model Name in Site information

---

resources/js/vue/components/BuildConfigure.vue

The configure page (`/builds/<id>/configure`) currently has an infinite recursion issue which causes browsers to kill the process due to high memory usage when viewing projects with subprojects.  This is due to a vue event handler mistakenly written as a binding.

Fix configure hide/show when subprojects present

---

app/cdash/tests/test_email.php

The `email` test is currently [very flaky](https://open.cdash.org/queryTests.php?project=CDash&begin=2024-04-05&end=2025-04-05&filtercount=2&showfilters=1&filtercombine=and&field1=status&compare1=62&value1=Passed&field2=testname&compare2=61&value2=email), particularly on Postgres due to Postgres not returning rows in the same order each time.  This PR fixes the test by explicitly ordering the builds in the expected order.

Fix flaky email test

---

tests/cypress/e2e/manage-build-group.cy.js

The `manage-build-group` test is [flaky](https://open.cdash.org/queryTests.php?project=CDash&begin=2024-04-07&end=2025-04-07&filtercount=2&showfilters=1&filtercombine=and&field1=status&compare1=61&value1=Failed&field2=testname&compare2=61&value2=cypress%2Fe2e%2Fmanage-build-group).  This PR resolves the flakiness by explicitly clicking two elements rather than relying on Cypress' "click multiple" functionality.

Fix flaky `manage-build-group` test

---

app/cdash/tests/CMakeLists.txt

A large portion of the test suite is a linear chain of legacy tests with confusing and intertwined dependencies.  Every test which can be run in parallel with other tests reduces the total running time by an equivalent amount of time.  This PR leaves a handful of simple tests in place, but changes anything which depends upon them to instead depend upon the prior test, taking them out of the critical path and allowing them to run in parallel with the rest of the test suite.  The goal is to do this to more tests, but doing so is a time consuming process.  I plan make a series of separate PRs to continue this effort in the future.  In total, these changes should reduce the total CI running time by 20-30 seconds.

Move simple legacy tests out of the critical path

---

app/Mail/AuthTokenExpired.php
app/Mail/AuthTokenExpiring.php

#2669 added email notifications for expiring authentication tokens.  Those email notifications are sent as HTML emails when they're meant to be sent as plaintext emails, resulting in poor formatting in most modern email clients.  We'd like to eventually move everything to HTML emails, but that's a future endeavor.  For now, this PR issues the auth token expiration emails as plaintext.

Use text emails for auth token notifications

---

resources/views/test/view-test.blade.php

The filters on `viewTest.php` were broken by #2560, as reported in https://github.com/Kitware/CDash/issues/2721.  I mistakenly thought this was an issue with the filters themselves and failed to attribute it to a recent change.  This PR restores the filters.

Reinstate `viewTest.php` filters

---

database/migrations/2025_04_09_150429_configure_log_medium_text.php

This was inadvertently reduced when we started using Laravel migrations in #904

Increase size of configure.log from text to mediumtext

---

resources/js/vue/components/EditProject.vue

The "bug tracker file URL" field has been unused for some time and https://github.com/Kitware/CDash/pull/2102 removed the column the data was stored in.  The UI was missed in that removal due to a typo in the HTML.  This PR cleans up the rest of the UI.

Remove unused "bug tracker file url" UI

---

tests/Browser/Pages/SitesIdPageTest.php

`SitesIdPageTest` [failed](https://github.com/Kitware/CDash/actions/runs/14404622114/job/40397991509?pr=2798) in CI with because the page didn't render before the assertion was made.  This is unfortunately a common issue with Dusk tests because assertions do not keep trying until a timeout like they do in Cypress.

Fix flaky `SitesIdPageTest`

---

app/cdash/tests/CMakeLists.txt
app/cdash/tests/autoremovebuilds/CMakeLists.txt
tests/CMakeLists.txt
tests/cypress/component/CMakeLists.txt
tests/cypress/e2e/CMakeLists.txt

This PR continues the work in #2698, moving Cypress-specific CTest content to dedicated files.  Additionally, I improved the dependency structure, leading to faster CI runs.  I plan to make a follow-up PR to further improve the dependency structure.

Restructure Cypress e2e tests

---

.env.example
config/cdash.php
docs/config.md

The `ACTIVE_PROJECT_DAYS` environment variable is no longer used by `/projects` to determine what classifies a project as "active".  This PR removes the environment variable.

Remove `ACTIVE_PROJECT_DAYS` env variable

---

config/queue.php

`QUEUE_CONNECTION` is currently set to `sync` by default.  We recommend using asynchronous workers for production systems, which means that CDash administrators have to perform unnecessary configuration right out of the box.  This PR changes the default to `database`, meaning that asynchronous parsing is now the default behavior.

Change `QUEUE_CONNECTION` default to `database`

---

.github/workflows/submit.sh
docker/docker-compose.dev.yml
docker/docker-compose.minio.yml
docker/docker-compose.mysql.yml
docker/docker-compose.postgres.yml
docker/docker-compose.production.yml
docker/docker-compose.yml
tests/BrowserTestCase.php

Our docker compose files currently hardcode each of the container names, making it difficult to run multiple deployments at the same time.  This is particularly annoying when developing locally.  This PR removes the hardcoded container names, letting docker compose give each container a name automatically.

Use auto-generated container names

---

.github/workflows/build-latest-images.yml
.github/workflows/ci.yml
.github/workflows/release.yml
Dockerfile
docker/docker-compose.production.yml

The `cdash-worker` image is the same as the regular website image, except that it uses a separate entrypoint argument.  There's no need to publish and maintain this separate image.  This PR removes all logic pertaining to the `cdash-worker` image.

Stop publishing separate cdash-worker image

---

.github/workflows/submit.sh

GitHub Actions runners have 4 vCPUs and we currently allow CTest to run 4 processes in parallel.  This doesn't leave enough CPU for the database and selenium containers to function efficiently.  This PR reduces the parallelism to 3 processes.

Reduce CI parallelism from 4 to 3 processes

---

app/cdash/tests/CMakeLists.txt
phpstan-baseline.neon
tests/Feature/SlowPageTest.php

This PR continues our ongoing effort to modernize the test suite by removing unnecessary explicit and implicit dependencies between tests, allowing us to make better use of multiprocessor systems.  The entire first "unit test" section of the test suite is now largely independent, leading to a much faster overall running time.  A number of unnecessary dependencies still exist due to broken mocks in some of these legacy unit tests.  I plan to make a separate PR to clean these up and remove all dependencies from this initial set of tests.
On my developer machine, these changes made development iterations much faster.

Remove unnecessary dependencies between mocked unit tests

---

app/cdash/tests/CMakeLists.txt
tests/Browser/Pages/ProjectSitesPageTest.php
tests/BrowserTestCase.php
tests/Feature/Mail/AuthTokenExpiredTest.php
tests/Feature/Mail/AuthTokenExpiringTest.php
tests/cypress/component/CMakeLists.txt
tests/cypress/e2e/CMakeLists.txt

All of our browser tests currently require exclusivity because they change the `.env`.  It isn't actually necessary to run serially if we can guarantee that the only thing being changed in the `.env` is the `APP_URL`.  This PR resolves the issue by adding a new `RESOURCE_LOCK` and changing the existing browser tests to allow parallel execution.  This is especially important going forward because the browser tests are some of the longest-running tests we have.

Lock APP_URL in browser and cypress tests

---

docker/docker-compose.postgres.yml

Our docker compose configuration currently stores the postgres data filesystem in an anonymous volume.  This PR fixes the issue by changing the data volume path to the path described in the [docs](https://hub.docker.com/_/postgres).

Fix docker compose postgres volume path

---

app/Enums/BuildCommandType.php
app/Enums/BuildMeasurementType.php
app/Enums/TargetType.php
app/GraphQL/Scalars/NonNegativeIntegerMilliseconds.php
app/Models/Build.php
app/Models/BuildCommand.php
app/Models/BuildMeasurement.php
app/Models/Target.php
app/Providers/GraphQLServiceProvider.php
app/Validators/Schemas/Build.xsd
app/cdash/tests/CMakeLists.txt
app/cdash/xml_handlers/build_handler.php
app/cdash/xml_handlers/configure_handler.php
database/migrations/2024_11_04_202649_build_measurements.php
graphql/schema.graphql
phpstan-baseline.neon
tests/Feature/GraphQL/BuildCommandTypeTest.php
tests/Feature/GraphQL/BuildMeasurementTypeTest.php
tests/Feature/GraphQL/BuildTypeTest.php
tests/Feature/GraphQL/LabelTypeTest.php
tests/Feature/GraphQL/TargetTypeTest.php
tests/Feature/Submission/Instrumentation/BuildInstrumentationTest.php
tests/Feature/Submission/Instrumentation/data/Build.xml
tests/Feature/Submission/Instrumentation/data/result.json

This PR replaces the initial build instrumentation work in #2460 with a more complete version based on a working CMake/CTest [implementation](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9791).  See #2395 for the full feature request.
I plan to make a follow-up PR to add support for configure measurements once a handful of blocking database schema changes are completed.  Future PRs will also implement various UIs to display the data collected here.

Add build instrumentation API

---

app/Policies/UserPolicy.php
app/cdash/tests/CMakeLists.txt
graphql/schema.graphql
tests/Feature/GraphQL/QueryTypeTest.php
tests/Feature/GraphQL/SiteTypeTest.php
tests/Feature/GraphQL/UserTypeTest.php

Users' email addresses are currently considered public information.  This PR changes that, instead limiting access to users themselves and CDash administrators.  This opens the possibility for a user-specific configuration option to allow users to optionally display their email address in various places in the UI.  As part of this PR, new `me`, `user(id)`, and `users` fields have been added to the GraphQL schema.

Restrict user email access

---

app/Models/User.php
app/cdash/app/Model/User.php
phpstan-baseline.neon

This PR removes the reflection-based passthrough which allowed legacy User model fields and methods to be available via the Eloquent User model.  The legacy model is only used in the legacy notification system and will eventually be removed.

Remove legacy User model passthrough

---

app/cdash/tests/CMakeLists.txt

The `user-profile` Cypress test does not rely upon data from prior tests, but needs data it creates to remain in the database for the duration of the test.  This causes a conflict with the `install_2` "test" which resets the entire database, as seen in [this](https://github.com/Kitware/CDash/actions/runs/14577369657/job/40886347190) failing job.  This PR adds `user-profile` to the list of dependencies for the `install_2` test.

Add `user-profile` Cypress test to `install_2` dependency list

---

tests/cypress/e2e/CMakeLists.txt

Implicit dependencies between Cypress tests weren't caught in https://github.com/Kitware/CDash/pull/2790.  This PR resolves the issues by forcing Cypress tests for test-related pages to run after the `remove-build` test which operates on the same data.  This should fix the Cypress flakiness in CI we've observed over the course of the last few weeks.

Fix flaky test-related Cypress tests

---

Dockerfile

CDash's Debian-based Docker image runs as a non-root user (www-data) yet attempts to bind a privileged port (443) because we enable the ssl module for production builds. This causes "Permission denied" errors in some cases.
Change this configuration to only listen on port 8080 (which is where CDash's traffic is served by default anyway).

docker: stop listening on port 443

---

app/Models/TestOutput.php
app/cdash/tests/CMakeLists.txt
phpstan-baseline.neon
tests/Unit/app/Models/TestOutputTest.php

We currently base64 encode test output for Postgres, but not MySQL. This difference in behavior is a problem as we plan to drop suport for MySQL in CDash 4.0. Migrating data from MySQL to Postgres (using pgloader) results in a Postgres database that contains test output which is not base64 encoded. This currently results in an error when attempting to view this data on CDash.
Update `TestOutput::DecompressOutput()` to mitigate this issue by allowing Postgres-backed CDash instances to decompress data that originally came from a MySQL database, and thus isn't base64 encoded.

Increase robustness of `TestOutput::DecompressOutput()`

---

app/cdash/app/Controller/Api/TestDetails.php

When attaching multiple files to a single test (via CTestMeasurementFile), the download of any file in BuildDetails.php would always redirect to downloading the first file since the retrieved list of files was accessed at index 0.
This was fixed by replacing the index 0 by the actual file id in $_GET['fileid'] (-1 since file ids start at 1).

Fixed download of mulitple attached files

---

app/Http/Controllers/CDash.php
routes/web.php

The current default route handler was initially conceived as a way to integrate Laravel into the existing routing system.  This route handler only applies to a handful of legacy API routes at this point, falling through with a 404 otherwise.  This PR limits the scope of the default route handler to only apply to routes under `/api`, using Laravel's default route handler for the rest of the routes.  I also changed the visibility of most of the functions in the file to better reflect their purpose.

Limit scope of default route handler

---

Dockerfile

`wget` is only used to download `composer` as part of the Debian-based image build process.  The version of `wget` embedded in a number of recent CDash releases is vulnerable to [CVE-2024-38428](https://nvd.nist.gov/vuln/detail/CVE-2024-38428), causing security scanners to flag our images unnecessarily.  We already use `curl` for CDash itself, so we can simply replace all existing usages of `wget` with `curl` to resolve this issue.

Remove `wget` from Debian-based image

---

app/Models/Project.php
app/cdash/app/Model/Project.php
app/cdash/include/common.php
database/migrations/2025_04_29_184206_remove_project_site_maintainer_role.php

CDash previously allowed users to "claim" sites, in addition to a separate "site maintainer" access control level.  That site maintainer role was associated with notification options, not an access level with its own designated permissions.  Additionally, the difference between users who had claimed sites and users who had the site maintainer role was unclear to users.  The site maintainer role is now obsolete and serves no purpose in CDash today.

Remove "site maintainer" project access level

---

app/Models/BuildCommand.php
app/Models/BuildCommandOutput.php
app/Validators/Schemas/Build.xsd
app/cdash/tests/CMakeLists.txt
app/cdash/xml_handlers/build_handler.php
database/migrations/2025_04_30_110457_build_command_outputs.php
graphql/schema.graphql
tests/Feature/GraphQL/BuildCommandOutputTypeTest.php
tests/Feature/Submission/Instrumentation/BuildInstrumentationTest.php
tests/Feature/Submission/Instrumentation/data/Build.xml
tests/Feature/Submission/Instrumentation/data/result.json

Following the work started in https://github.com/Kitware/CDash/pull/2612, this PR adds supports for the `output` and `outputSizes` [snippet file](https://cmake.org/cmake/help/latest/manual/cmake-instrumentation.7.html#v1-snippet-file) fields.

Add support for build command outputs

---

Dockerfile
docker/cdash-site.conf

The UBI-based container currently sends logs to the same path the Debian container does, which means that they don't get redirected to stderr.  This PR removes our unintentional manual overrides, allowing apache logs to get sent to the container's stderr.  I plan to make a separate PR to resolve the CDash error logging issue.

Send httpd logs to stderr when using UBI as base

---

app/GraphQL/Mutations/RemoveProjectUser.php
app/Policies/ProjectPolicy.php
app/cdash/tests/CMakeLists.txt
graphql/schema.graphql
phpstan-baseline.neon
resources/js/vue/components/ProjectMembersPage.vue
resources/views/project/members.blade.php
tests/Browser/Pages/ProjectMembersPageTest.php
tests/Feature/GraphQL/Mutations/RemoveProjectUserTest.php

Following the work in https://github.com/Kitware/CDash/pull/2778, this PR adds an admin-only column containing a button which removes project members to the project members page.  As of now, anyone with project admin access can delete members.  I plan to make a follow-up PR which fine-tunes this behavior when 3rd-party authentication providers are used.

Add admin button to delete project members

---

app/GraphQL/Directives/FilterDirective.php
phpstan-baseline.neon
tests/Feature/GraphQL/FilterTest.php

As discussed in https://github.com/Kitware/CDash/issues/2777, it's not immediately clear that a filter input object like this is invalid:
```graphql
filters: {
gt: {id: "123"},
lt: {id: "456"},
}
```
This PR aims to address this confusion by explicitly prohibiting multiple fields from being used in the same filter object, instead of silently ignoring all but the first field.
Not addressed in this PR is this case:
```graphql
filters: {
eq: {
id: "123",
name: "foo",
},
}
```
A handful of separate changes need to be made before I can add validation to handle it, so I've deferred that work to a future PR.

Improve GraphQL filter validation

---

app/cdash/app/Model/BuildErrorFilter.php
app/cdash/app/Model/Project.php
app/cdash/xml_handlers/BazelJSON_handler.php
app/cdash/xml_handlers/GcovTar_handler.php
app/cdash/xml_handlers/SubProjectDirectories_handler.php
app/cdash/xml_handlers/abstract_submission_handler.php
app/cdash/xml_handlers/abstract_xml_handler.php
app/cdash/xml_handlers/build_handler.php
app/cdash/xml_handlers/coverage_handler.php
app/cdash/xml_handlers/coverage_log_handler.php
phpstan-baseline.neon

It's not currently possible to instantiate some types of submission handlers without beginning the parsing process.  This PR removes all database queries from submission handler controllers, allowing handlers to be instantiated and passed around safely.  This is incremental progress towards a larger refactoring goal, and should have no effect on the submission parsing process itself.

Remove database queries from submission handler constructors

---

app/Console/Kernel.php
app/Http/Controllers/Auth/LoginController.php
app/Http/Controllers/ProjectController.php
app/Http/Controllers/ProjectInvitationController.php
app/Listeners/SuccessfulLdapAuthListener.php
app/Policies/ProjectPolicy.php
config/cdash.php
tests/Feature/GraphQL/Mutations/InviteToProjectTest.php
tests/Feature/GraphQL/Mutations/RemoveProjectUserTest.php

It doesn't make sense to ever give users the ability to add or remove users to a project if a project's "LDAP filter" is set.  Even though it's currently possible to add and remove users manually when an LDAP filter is set, the changes will be overwritten automatically by the LDAP sync script.  This PR explicitly disallows manual membership changes by users of any access level, including global administrators.

Disable manual project membership when LDAP enabled

---

.github/workflows/ci.yml

Our current CI Docker image build uses QEMU emulation to build `arm64` images.  The `arm64` component of the build process takes a disproportionate amount of time, and is the longest-running job in our test suite.  Thanks to GitHub's new `arm64` runners, we can now build each architecture without emulation.

Use GHA arm64 runners for arm64 image build job

---

resources/js/vue/app.js
resources/js/vue/components/ProjectMembersPage.vue
resources/js/vue/components/SitesIdPage.vue
resources/js/vue/components/UserHomepage.vue
resources/js/vue/components/UsersPage.vue
resources/js/vue/components/shared/BuildSummaryCard.vue
resources/js/vue/components/shared/BuildSummaryCardStepSummary.vue
resources/js/vue/components/shared/DataTable.vue
resources/js/vue/components/shared/FilterBuilder.vue
resources/js/vue/components/shared/FilterGroup.vue
resources/js/vue/components/shared/FilterRow.vue
webpack.mix.js

Font Awesome is currently responsible for the majority of our overall Vue bundle size because it includes all of the available icons in the main bundle.  This PR removes the global icon library in favor of per-component includes.  The end result is that the main bundle size is reduced by 75%+.  As part of this work, I fixed an issue with the webpack runtime configuration which was missed in #2864.

Load minimal set of icons for each page

---

tests/cypress/e2e/sub-project-group-order.cy.js

https://github.com/Kitware/CDash/pull/2855 caused the `sub-project-group-order` Cypress test to run slightly slower, causing lots of test failures since then.  I believe this is due to a rendering optimization on the index page which renders the page in chunks.  This PR aims to address the issue by waiting for the page to fully render before moving on.  I plan to run the CI multiple times for this PR to gain confidence that this change actually does anything because I'm unable to reproduce the test failures locally.

Adjust waits in flaky `sub-project-group-order` test

---

phpstan-baseline.neon
tests/Browser/Pages/ProjectMembersPageTest.php
tests/Feature/GlobalInvitationAcceptanceTest.php
tests/Feature/GraphQL/Mutations/CreateGlobalInvitationTest.php
tests/Feature/GraphQL/Mutations/InviteToProjectTest.php
tests/Feature/GraphQL/Mutations/RevokeGlobalInvitationTest.php
tests/Feature/GraphQL/Mutations/RevokeProjectInvitationTest.php
tests/Feature/GraphQL/UserInvitationTypeTest.php
tests/Feature/ProjectInvitationAcceptanceTest.php

Several of the tests which generate placeholder email addresses have recently started experiencing sporadic failures due to tests violating unique constraints on various email columns.  This PR aims to address the issue by instead using emails generated from a larger set of possible options.

Fix sporadic email unique constraint testing issues

---

.eslintignore
composer.json
composer.lock
install.sh
resources/views/vendor/graphiql/index.blade.php

The library we use to provide GraphiQL [recently broke](https://github.com/mll-lab/laravel-graphiql/issues/53) due to an unpinned upstream dependency.  This PR fixes the issue by updating `laravel-graphiql` to the newest version which pins dependencies appropriately.  I also enabled asset downloading to prevent this issue from occurring in the future if the CDN ever goes down again.

Update `laravel-graphiql` to 4.0.1

---

composer.json
composer.lock

As described in https://github.com/Kitware/CDash/pull/2876, the version of `laravel-graphiql` we use contains unpinned dependencies which currently lead to GraphiQL being broken on all versions of CDash.  https://github.com/Kitware/CDash/pull/2876 implemented a long-term fix which will be released in CDash 4.0, but many users are likely to remain on 3.10 for some time while transitioning from MySQL to Postgres.  This PR makes a similar change in the 3.10 release series to get GraphiQL working again in CDash 3.x.

Bump `laravel-graphiql` to 3.3.3

---

public/.htaccess

This PR adds a primitive [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CSP) as another layer of protection against XSS attacks.  While a nonce- or hash-based approach is the ultimate goal, some of the legacy Javascript needs to be refactored before that is realistic.  As a basic starting point, this PR blocks all access to cross-origin scripts since CDash itself never uses scripts from a 3rd-party source.  This protects against one of the most common XSS attack vectors: small segments of malicious code which download a malicious payload from external sites.

Set basic Content Security Policy

---

app/Http/Controllers/AdminController.php
app/Utils/DatabaseCleanupUtils.php
app/cdash/include/common.php
phpstan-baseline.neon

A simple maintenance PR to remove an unused code path which contains an undefined variable.

Fix undefined variable code path in remove builds method

---

app/Jobs/ProcessSubmission.php
app/Models/Project.php
app/cdash/app/Model/Project.php
app/cdash/tests/test_createpublicdashboard.php
app/cdash/tests/test_pubproject.php
database/migrations/2025_05_12_145045_remove_emailadministrator_project_config.php
phpstan-baseline.neon
resources/js/vue/components/EditProject.vue

The "email administrator" project setting has gradually become obsolete, now only used to report submissions which cannot be parsed.  This is no longer necessary in light of our [recent effort](https://github.com/Kitware/CDash/pull/2804) to rethink the submission validation process.  This PR removes the setting and all related logic.

Remove "email administrator" project setting

---

app/cdash/include/common.php
resources/views/components/header.blade.php
tests/cypress/e2e/query-tests.cy.js
tests/cypress/e2e/view-test.cy.js

This fixes a bug where the default link to the "Query Tests" page would show all tests for Postgres-backed CDash instances.
This is because Postgres performs case sensitive comparisons by default, and test status is stored as "passed", "failed", or "notrun" in the database.

Use "passed" instead of "Passed" for default test filters

---

config/services.php
docs/authentication.md
tests/Feature/LoginAndRegistration.php

Some users may want to customize the text of the OAuth buttons to reflect internal names for providers we support.  This PR adds the ability to do so by setting `*_DISPLAY_NAME` environment variables for their respective OAuth2 providers.

Add option to customize OAuth button text

---

Dockerfile
install.sh

https://github.com/Kitware/CDash/pull/2876 added a command to download the assets for GraphiQL at container runtime.  In addition to causing containers to start more slowly, this approach can be problematic in air gapped networks or systems where the vendor directory is read-only.  Another downside is that the assets could be different when new container is deployed from the same image.  This PR changes the behavior to instead download the assets at image build time, or whenever the install command is run manually.

Download GraphiQL assets during Docker build

---

database/migrations/2025_05_19_172027_increase_testmeasurement_name_size.php

This change resolves the following type of database errors:
```
insert into "testmeasurement" ...  value too long for type character varying(70)
```

Increase the size of the testmeasurement.name field

---

public/.htaccess

[HTTP compression](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Compression) is supported by all major browsers, and enabling it is now considered to be a standard practice.  I observed a baseline transfer size improvement of 1-5% for all pages, plus a 10-60% improvement for pages with large amounts of text data in a development environment.  Network overhead is the biggest contributor to initial page render time, so reducing the number of bytes transmitted corresponds to a reduction in page load time.

Enable HTTP Compression

---

app/Http/Controllers/RemoteProcessingController.php
app/cdash/include/common.php
app/cdash/tests/test_donehandler.php
app/cdash/xml_handlers/abstract_xml_handler.php
app/cdash/xml_handlers/retry_handler.php
phpstan-baseline.neon

The name of the relevant config file is "filesystems", not "filesystem".

Fix configuration checks for local vs. remote storage

---

app/Policies/GlobalInvitationPolicy.php
app/cdash/tests/CMakeLists.txt
graphql/schema.graphql
phpstan-baseline.neon
tests/Feature/GraphQL/GlobalInvitationTypeTest.php
tests/Feature/GraphQL/ProjectInvitationTypeTest.php

https://github.com/Kitware/CDash/pull/2778 and https://github.com/Kitware/CDash/pull/2830 both suffer from a logical flaw which was missed in testing because the Laravel `assertJson(..., strict: true)` does not actually do an exact JSON match as it was believed to do.  This PR resolves the access control issues in these unreleased features.  I plan to make a separate PR to convert the rest of the `assertJson()` assertions throughout the codebase to `assertExactJson()`.

Fix project and global invitation access control issues

---

app/Http/Controllers/AdminController.php
app/Http/Controllers/MonitorController.php
app/Http/Controllers/SiteController.php
app/Providers/AppServiceProvider.php
app/Utils/SubmissionUtils.php
app/cdash/app/Controller/Api/Index.php
app/cdash/app/Controller/Api/QueryTests.php
app/cdash/app/Controller/Api/ViewTest.php
app/cdash/app/Model/BuildUpdate.php
app/cdash/app/Model/CoverageFileLog.php
app/cdash/app/Model/DynamicAnalysis.php
app/cdash/app/Model/Label.php
app/cdash/app/Model/Project.php
app/cdash/include/common.php
app/cdash/include/filterdataFunctions.php
app/cdash/public/api/v1/buildgroup.php
app/cdash/tests/kwtest/kw_db.php
app/cdash/tests/test_projectindb.php
config/database.php
phpstan-baseline.neon

This PR follows https://github.com/Kitware/CDash/pull/2885, removing almost all of the MySQL-specific logic throughout the codebase.  A couple database-specific code paths remain since changing them interferes with the test suite.  I plan to address them in a separate PR.

Remove MySQL-specific code paths

---

app/cdash/include/filterdataFunctions.php

Some users previously used MySQL's case-insensitivity to deliberately create case-insensitive filters for build and test names.  While it's not practical to implement case-insensitivity for very selective filters while retaining their current performance, there is no real difference in performance for filters which are not selective enough to make use of indexes.  This PR changes all of the "LIKE"-based filters to use "ILIKE" instead.  Note that this will make the "starts with" filter less performant, in exchange for maintaining consistency with the other LIKE-based filters.

Make partial text match filters case-insensitive

---

app/GraphQL/Mutations/JoinProject.php
app/GraphQL/Mutations/RemoveProjectUser.php
app/Http/Controllers/ProjectMembersController.php
app/Http/Controllers/SubscribeProjectController.php
app/Policies/ProjectPolicy.php
app/cdash/public/subscribeProject.xsl
app/cdash/tests/CMakeLists.txt
app/cdash/tests/test_email.php
graphql/schema.graphql
phpstan-baseline.neon
resources/js/vue/components/ProjectMembersPage.vue
resources/views/components/header.blade.php
tests/Browser/Pages/ProjectMembersPageTest.php
tests/Feature/GraphQL/Mutations/JoinProjectTest.php
tests/Feature/GraphQL/Mutations/RemoveProjectUserTest.php

This PR finishes our recent effort to modernize the project membership experience started in https://github.com/Kitware/CDash/pull/2778.  The join/leave functionality has been moved to the project members page, leaving `subscribeProject.php` as only a place to configure notifications.

Move join/leave project functionality to members page

---

webpack.mix.js

https://github.com/Kitware/CDash/pull/2864 introduced Webpack bundle splitting.  While the chunk names are based on a rolling integer number in production, they are deterministically computed based on the filename in development.  Browser caching causes this to be annoying in development.  This PR changes the naming scheme to instead depend on the content hash, eliminating the issue.

Use cache-busting Webpack chunk names in development

---

app/GraphQL/Directives/FilterDirective.php
phpstan-baseline.neon
tests/Feature/GraphQL/FilterTest.php

The existing GraphQL filter input currently only allows users to filter by fields directly on the underlying table being filtered.  This PR improves the filter input by allowing users to search by relationships as well.  In other words, it's now possible to answer queries like "give me the list of builds which have a test named xyz".  These filters can be infinitely nested, essentially giving users the ability to query anything in the CDash database, subject to access control limitations.  This is an extremely powerful capability which will enable improvements to existing pages, brand new pages which were not previously possible, and 3rd-party extensions using the API.

Add GraphQL relationship filters

---

app/cdash/tests/CMakeLists.txt
app/cdash/tests/autoremovebuilds/CMakeLists.txt
app/cdash/tests/test_issuecreation.php
tests/cypress/e2e/tests.cy.js

This PR supersedes https://github.com/Kitware/CDash/pull/2903, moving tests which have no dependencies to the parallel section at the beginning of the test suite instead of creating parallel blocks in the middle of the test suite.  This approach is far safer than the aggressive approach taken in https://github.com/Kitware/CDash/pull/2903, reducing the chances of additional flakiness being introduced.  In addition to improving the overall test time, these changes make it easier to debug tests late in the test by reducing the length of the longest dependency chain.

Clean up legacy test dependencies

---

app/cdash/tests/CMakeLists.txt

We've recently had quite a bout of flaky tests caused by CTest's test ordering.  This PR aims to fix at least part of the issue.

Reduce test flakiness

---

app/cdash/tests/CMakeLists.txt
phpstan.neon
tests/CMakeLists.txt
tests/cypress/component/CMakeLists.txt
tests/cypress/e2e/CMakeLists.txt

The first part of our test suite consists of a number of tests which can be run up to a relatively high parallel level.  Some of these tests require more than one processor, which causes thrashing when multiple tests are run concurrently.  This PR attempts to address the issue by specifying 2 processors for PHPStan, Cypress, and Dusk tests.

Specify multiple processors for resource-intensive tests

---

app/cdash/tests/case/CDash/Messaging/Subscription/UserSubscriptionBuilderTest.php
app/cdash/tests/case/CDash/Messaging/Topic/AuthoredTopicTest.php
app/cdash/tests/case/CDash/Messaging/Topic/ConfigureTopicTest.php
app/cdash/tests/case/CDash/Messaging/Topic/EmailSentTopicTest.php
app/cdash/tests/case/CDash/Messaging/Topic/TopicDecoratorTest.php
app/cdash/tests/case/CDash/Service/RepositoryServiceTest.php
phpstan-baseline.neon

`getMockForAbstractClass()` is deprecated and will be [removed](https://github.com/sebastianbergmann/phpunit/blob/11.5/DEPRECATIONS.md) in PHPUnit 12.  This PR addresses our usages of the method.

Fix abstract class mock deprecation warnings

---

tests/Feature/GraphQL/BuildCommandTypeTest.php
tests/Feature/GraphQL/Mutations/CreateGlobalInvitationTest.php
tests/Feature/GraphQL/Mutations/InviteToProjectTest.php
tests/Feature/GraphQL/ProjectTypeTest.php
tests/Feature/GraphQL/SiteTypeTest.php
tests/Feature/GraphQL/TargetTypeTest.php
tests/Feature/GraphQL/TestTypeTest.php
tests/Feature/LoginAndRegistration.php
tests/Feature/RouteAccessTest.php

PHPUnit 12 [removes](https://github.com/sebastianbergmann/phpunit/blob/11.5/DEPRECATIONS.md) support for doc comment parsing, instead using PHP's attributes to do the same thing.  This PR converts all of our data provider doc comments to PHP attributes in preparation for our upcoming migration to PHPUnit 12.

Move data providers to PHP attributes

---

app/Utils/RepositoryUtils.php

This commit fixes the following error.
```
production.ERROR: strtolower():
Argument #1 ($string) must be of type string, null given /cdash/app/Utils/RepositoryUtils.php:31
```

Check type of $cvsviewertype before converting to lowercase

---

Dockerfile

Our UBI Docker image uses PHP FPM. Its default behavior is to redirect stdout and stderr to /dev/null for worker processes.
Override this behavior by setting catch_workers_output = yes. This causes log messages to show up on stderr, which is the expected behavior for our container-based deployments.

Fix missing log messages for UBI images

---

app/Models/Note.php
app/Utils/NoteCreator.php
app/cdash/tests/test_removebuilds.php
database/migrations/2025_06_17_140642_drop_note_crc32.php
phpstan-baseline.neon
tests/Feature/GraphQL/NoteTypeTest.php

Modern versions of Postgres have good [hash index](https://www.postgresql.org/docs/current/hash-index.html) support, allowing us to efficiently perform equality comparisons on large text columns.  Our current crc32-based hashing system suffers from hash conflicts, in addition to adding unnecessary and easily-broken logic.  This PR replaces the crc32 column with a hash index and explicit equality comparison against all fields on insertion.

Replace `note` `crc32` column with hash index

---

resources/js/vue/components/BuildTestsPage.vue
resources/js/vue/components/shared/FilterGroup.vue
resources/js/vue/components/shared/FilterRow.vue

https://github.com/Kitware/CDash/pull/2889 broke the new GraphQL-based filter interface.  This PR restores that functionality, plus a handful of other minor changes to related code.

Fix GraphQL-based filter interface

---

graphql/schema.graphql
tests/Feature/GraphQL/CoverageTypeTest.php

This PR adds a `labels` field to the `Coverage` GraphQL type.

Expose coverage labels via GraphQL

---

app/Ldap/Rules/FilterRules.php
app/Models/User.php
app/Utils/LdapUtils.php
phpstan-baseline.neon
tests/Feature/LdapIntegration.php

Users who log in with LDAP are able to by synced to projects specifying an LDAP filter thanks to https://github.com/Kitware/CDash/pull/2282.  Unfortunately, users who are added via other authentication providers are not currently associated with an LDAP user and aren't able to be synced.  This PR resolves the issue by attempting to look up users by email (or other configured primary key) to get the associated LDAP GUID.

Sync LDAP GUID for users added via non-LDAP methods

---

app/Http/Controllers/DynamicAnalysisController.php
resources/js/vue/components/ViewDynamicAnalysis.vue
resources/js/vue/components/page-header/HeaderNav.vue

This PR continues our ongoing effort to standardize the build information displayed at the top of many of the build-specific information pages across the site.

Add common build info card to dynamic analysis page

---

app/cdash/app/Model/CoverageFileLog.php
database/migrations/2025_07_24_173132_coveragefilelog_bytea_to_text.php
phpstan-baseline.neon

The `coveragefilelog` `log` column stores text strings.  Even if it's not immediately human readable, the underlying data is still text.  Storing text data in a binary column type is an over-engineered abuse of Postgres' type system.  This PR changes the underlying column type to `text` for better compatibility with various parts of our PHP application layer.

Convert `coveragefilelog` `log` column to text

---

app/Http/Controllers/BuildController.php
app/cdash/tests/CMakeLists.txt
phpstan-baseline.neon
resources/js/vue/app.js
resources/js/vue/components/BuildTargetsPage.vue
routes/web.php
tests/Browser/Pages/BuildTargetsPageTest.php

Building on top of https://github.com/Kitware/CDash/pull/2612, this PR adds a new "build targets" page which displays a table of targets for a build if instrumentation data was submitted.  See https://github.com/Kitware/CDash/issues/2827 for more details about the outline for our new instrumentation-related pages.  I have a number of future improvements in mind for this page, including better support when viewing parent builds, correlation to errors & warnings with associated color highlighting, customizable timing or other measurement columns, a trace-style view of the targets or other at the top of the page.

Add build->targets UI

---

app/Http/Controllers/BuildPropertiesController.php
app/cdash/tests/test_buildproperties.php
phpstan-baseline.neon

The `buildproperties` test currently uses a hardcoded project name and hardcoded login credentials which conflict other tests in rare cases.  This PR resolves the issue by using a unique project name and eliminating the need for credentials.

Improve isolation of `buildproperties` test

---

resources/js/angular/views/viewBuildError.html

Using `href` attributes in AngularJS is discouraged because links will still have placeholders in them if users (or, more likely, web scrapers) attempt to click them before AngularJS has finished rendering.  Instead, it's preferable to use `ng-href`, which gets transformed into `href` by AngularJS.  This PR addresses various stack traces and logs associated with URLs containing AngularJS placeholders in a production system.

Use `ng-href` for AngularJS links

---

app/Console/Commands/QueueSubmissions.php
app/cdash/app/Lib/Repository/GitHub.php
app/cdash/app/Model/Build.php
app/cdash/app/Model/BuildConfigure.php
app/cdash/include/Messaging/Topic/MissingTestTopic.php
app/cdash/include/common.php
app/cdash/tests/case/CDash/TestUseCaseTest.php
app/cdash/tests/test_branchcoverage.php
app/cdash/tests/test_deferredsubmissions.php
app/cdash/tests/test_parallelsubmissions.php
app/cdash/tests/test_unparsedsubmissionshonorbuildid.php
phpstan-baseline.neon

IDEs and static analysis tools don't always understand Laravel's global include system, making it hard to fully trace code.  This PR resolves the issue by explicitly including everything by FQN.

Fix undefined class warnings

---

app/Http/Controllers/SubProjectController.php
app/cdash/public/api/v1/index.php
app/cdash/tests/CMakeLists.txt
config/cdash.php
phpstan-baseline.neon
resources/views/components/header.blade.php
tests/Feature/GlobalBannerTest.php

The current banner isn't shown on all pages, and it's currently impossible to view the global banner and project-specific banners at the same time.  This PR moves the global banner to the middle of the top bar, leaving the original banner as a project-specific feature.  A future PR will extend the project-specific banner to all project pages.

Move global banner text to top bar

---

app/Utils/TestCreator.php

Since https://github.com/Kitware/CDash/pull/2336, test measurements are no longer related to test outputs directly.  Their removal from the test output crc32 was overlooked, meaning that we're now missing opportunities to deduplicate test outputs more efficiently.  This is particularly impactful because some test measurements include variable measurements such as wall clock time, effectively meaning that we're not deduplicating at all.  This PR removes test measurements from the test output hash computation.

Remove measurements from test output crc32 computation

---

public/.htaccess

#2877 broke the image on the maintenance page because it's rendered inline.  This PR restores the image by changing our content security policy to allow inline images.

CSP: Allow inline images

---

docker/docker-compose.dev.yml
docker/docker-compose.minio.yml

See https://github.com/bitnami/containers/issues/83267 for the information about the switch on DockerHub from `bitnami` to `bitnamisecure`.
At the moment, the instances we use are not available in secure, so use the `bitnamilegacy` images.

Switch to bitnamilegacy for Docker

---

app/Http/Controllers/SubscribeProjectController.php
phpstan-baseline.neon
resources/js/vue/components/UserHomepage.vue

Since the merge of https://github.com/Kitware/CDash/pull/2898, user management is separate from project notification settings.  This PR updates the homepage link to take you to the new project members page instead of the project notifications page when attempting to join a project.

Update join project homepage link

---

app/cdash/app/Lib/Repository/GitHub.php

It's currently impossible to tell which project this exception is coming from.  For now, adding this information to the error message is sufficient.  In the future, it may be useful to switch this from an exception to a log message at a lower log level.

Add context to installation ID exception message

---

docker/docker-compose.postgres.yml
docker/docker-compose.production.yml

Update our docker compose configuration files to restart the webservice and database containers except for when they are explicitly shut down.

compose: configure containers to restart

---

app/cdash/app/Controller/Api/ViewTest.php
phpstan-baseline.neon

This issue has been generating stack traces in our logs for quite a while.  It's unclear how frequently real users use this feature, but web scrapers visit the download link on a regular basis.  Fixing the measurement columns appears to be nontrivial, so this PR just deletes them from the downloaded CSV.  These can be re-added in the future via the feature request process if sufficient interest exists.

Fix CSV download when measurements present

---

config/cdash.php
package-lock.json
package.json

https://github.com/Kitware/CDash/pull/3128 accidentally targeted `master` instead of `releases/4.4`.  This PR brings the version bump to 4.4.  I'll re-release 4.4 once this PR is merged.

Bump version to 4.4.0

---

app/cdash/include/dailyupdates.php
phpstan-baseline.neon

The deleted code does absolutely nothing besides wasting CPU cycles.  It's possible that something meant to use this at one point and is now broken, but we can address that via a separate PR if needed.

Delete unused daily updates code

---

tests/cypress/e2e/test-summary.cy.js
tests/cypress/e2e/tests.cy.js

`test-summary.cy.js` has been flaky for years and is quite a nuisance when unrelated changes modify the test timing subtly and upset this delicate test.  See the trouble merging https://github.com/Kitware/CDash/pull/3132 for an example.  My hypothesis is that somehow the rows in the table are not rendered deterministically.  This PR attempts to resolve that by sorting by build stamp.  I intend to run the tests 10 times before opening this for review to ensure that this fix actually does something.

Sort testSummary rows deterministically in e2e test

---

config/ldap.php

Logging every LDAP query is more in line with our `debug` log level usages rather than our `info` log level usages.

Change default LDAP logging level to `debug`

---

app/Http/Controllers/SubmissionController.php

Invalid hashes are probably associated with configuration issues for a small handful of projects, so it's helpful to have the project name in the log message.

Add project name to hash mismatch error log

---

app/Jobs/ProcessSubmission.php
app/Models/BuildFile.php
phpstan-baseline.neon

The submission handling process is currently a delicate mess which is difficult to change without breaking unrelated features.  This PR is part one of a cleanup of the submission process, using Eloquent wherever possible and eliminating unnecessary DB queries.  I'll perform a larger cleanup in a separate PR once this preliminary work is merged.

Simplify submission processing DB queries

---

package-lock.json
package.json

I forgot to remove `git-revision-webpack-plugin` from our `package.json` in https://github.com/Kitware/CDash/pull/3171.

Remove `git-revision-webpack-plugin` dependency

---

app/Http/Controllers/SubmissionController.php

While https://github.com/Kitware/CDash/pull/3172 was beneficial, I forgot to add the project to the other hash mismatch log message as well.  This PR fixes that, while also correcting the text of the message itself.

Update invalid hash log message
