Kitware/CDash

common.css
manageBuildGroup.xsl

@wakeup @jcfr This fixes the problem with the calendar's display while maintaining the appearance of the tabs on manageBuildGroup.php.  Take a look & let me know if it works as expected for you.

fix appearance of calendar widget

---

cdash/config.php
index.php
indexsubproject.xsl
models/project.php
models/subproject.php

A new config option to speed up rendering of index.php for projects with lots of subproject builds.

New option to disable the "last submission" column

---

cdash/do_submit.php

This seems to provide a modest performance improvement.

Use SQL transactions during submission

---

sql/pgsql/cdash-upgrade-2.0-2.4.sql
sql/pgsql/cdash-upgrade-2.0-2.6.sql

These should contain the same fixes as the recently merged fix_postgres branch.

update postgres upgrade sql files

---

tests/autoremovebuilds/CMakeLists.txt
tests/data/DeleteSubProject/Project.xml
tests/test_deletesubproject.php
xml_handlers/project_handler.php

(Safely) delete any subprojects that aren't included in a newly uploaded Project.xml file.

Delete old subprojects

---

manageOverview.php
overview.php
sql/mysql/cdash.sql
sql/pgsql/cdash.sql
upgrade.php

In my experiments using lots of subproject builds, this branch results in a 17x speedup over the previous version of overview.php.

Speedup rendering of overview.php

---

overview.php

We lost this distinction when we stopped querying child builds.

fix core/non-core coverage for overview.php

---

cdash/do_submit.php
cdash/sendemail.php
tests/data/EmailProjectExample/cdash_2.log

Email committers about broken builds when parsing Update.xml

fix broken emails

---

cdash/autoremove.php
models/clientjob.php

Delete old rows from the ``client_*`` (CDash@Home) tables in accordance with our pre-project expiration setting.

Autoremove jobs

---

models/feed.php

Fix incorrect pdo_insert_id() table reference after feed INSERT

---

index.php

This fixes the case where you just want to view the build results for a single subproject.

Fix display of per-subproject builds

---

javascript/cdash_angular.js
javascript/tabNavigation.js
tests/js/e2e_tests/manageSubProject.js

This makes our anchor tags a little bit uglier, but it restores the functionality of "open link in new tab".

Fix angular links

---

api/viewBuildError.php

This fixes a bug where viewBuildError would tell you to login even though you already did.

fix viewBuildError for private projects

---

tests/selenium/CMakeLists.txt
tests/test_compressedtest.php

As a foliow-up effort I will convert these to run using Protractor

disable failing tests

---

views/viewTest.html

A bug prevented this column header from being displayed properly.

Fix "Time Status" header on viewTest.php

---

tests/js/pages/login.page.js

This should help these tests pass more reliably.

Wait for login to complete during e2e tests

---

javascript/controllers/manageBuildGroup.js
javascript/controllers/manageSubProject.js
javascript/controllers/viewBuildError.js
javascript/controllers/viewTest.js
views/manageBuildGroup.html
views/manageSubProject.html
views/viewBuildError.html
views/viewTest.html

Display a spinner icon while we're waiting to render an AngularJS view.

show spinner while loading data

---

cdash/config.php
cdash/log.php

This is currently set to true but should be made false ASAP.

Add a configuration variable to disable logging to the database.

---

cdash/config.php
cdash/pdocore.php

Add support for persistent connections using mysql_pconnect.

---

googleauth_callback.php

Fix some issues that prevented us from enabling Google OAuth2 login on open.cdash.org

Bug fix for Google authentication

---

README.md
composer.json

Add basic installation instructions to README

---

api/v1/index.php
filterdataFunctions.php
javascript/controllers/index.js

Fix various issues I noticed while playing around with filters & subprojects.

Fix filter errors

---

models/build.php
tests/data/GithubPR/Build.xml
tests/data/GithubPR/Configure.xml
tests/data/GithubPR/Project.xml
tests/data/GithubPR/Test.xml
tests/test_github_PR_comment.php
xml_handlers/build_handler.php
xml_handlers/configure_handler.php

Comment when a build fails to configure.
Include the name of the SubProject that failed (if any).

improvements to Github PR integration

---

api/v1/index.php

Fix a bug where the configure column would erroneously be hidden when it was non-empty.

Bug fix for configure column

---

ajax/getsubprojectdependencies.php
ajax/getviewcoverage.php
api/v1/buildgroup.php
api/v1/filterdata.php
api/v1/index.php
api/v1/index_old.php
api/v1/manageBuildGroup.php
api/v1/manageSubProject.php
api/v1/subproject.php
api/v1/viewBuildError.php
api/v1/viewNotes.php
api/v1/viewProjects.php
api/v1/viewSubProjects.php
api/v1/viewTest.php
cdash/common.php
cdash/do_submit.php
tests/test_api.php
views/manageBuildGroup.html

`json_encode` returns FALSE if it encounters a string that isn't utf-8.

Ensure strings are utf-8 before calling json_encode

---

views/viewTest.html

Also make labels sortable and remove inline style.

Tooltips to explain columns

---

api/v1/buildgroup.php

Bug fix, this functionality previously did not work as expected.

Fix deletion of dynamic build group rows

---

CMakeLists.txt
composer.lock

Run composer update prior to automated testing

Automatically run composer update

---

tests/selenium/test_querytestsfilters.php

Filter rows are now automatically re-indexed when one is removed.

Fix failing test

---

api/v1/viewTest.php
tests/CMakeLists.txt
tests/data/TestHistory/Test_1.xml
tests/data/TestHistory/Test_2.xml
tests/test_testhistory.php

Add a test for viewTest.php's "History" column.

Cover test history

---

public/js/controllers/index.js
public/views/index.html

Remember whether the user prefers simple or advanced view for
this project.

Cache simple/advanced view setting in a cookie

---

public/api/v1/queryTests.php

It was pointing to index.php instead.

Fix next for queryTests.php

---

include/CDash/Database.php
include/common.php
include/pdocore.php
public/api/v1/filterdata.php
public/api/v1/hasfile.php
public/importBackup.php
public/install.php
public/mobile/old_index.php
tests/kwtest/kw_test_manager.php
tests/kwtest/simpletest/detached.php
tests/kwtest/simpletest/eclipse.php
tests/kwtest/simpletest/parser.php

I figured it was quicker to just fix these rather than file a bug.

Fix errors and warnings logged during testing

---

public/login.php

Generate a new session token upon authentication.

Prevent session fixation

---

config/config.php
public/editUser.php
public/install.php
public/register.php
tests/test_edituser.php
tests/test_login.php

Add a new configuration option to config.php to enforce a minimum password length on all new & updated accounts.

minimum password length

---

models/buildnote.php
models/coveragefile.php
xml_handlers/coverage_log_handler.php
xml_handlers/note_handler.php

The only non-whitespace change in this PR is updating ``buildnote.php`` to call ``add_log`` as opposed to ``echo`` when reporting errors.
I'm splitting these commits out into their own PR so that a future, meatier branch will be easier to review.

Re-indent more files

---

include/ctestparserutils.php
models/build.php
models/coveragefile.php
models/coveragesummary.php
tests/CMakeLists.txt
tests/data/InsightExperimentalExample/Insight_Experimental_CoverageLog.xml
tests/data/InsightExperimentalExample/Insight_Experimental_Update.xml
tests/data/InsightExperimentalExample/Insight_Experimental_Upload.xml
tests/js/e2e_tests/viewBuildError.js
tests/test_notesapi.php
tests/test_sequenceindependence.php
xml_handlers/GcovTar_handler.php
xml_handlers/JavaJSONTar_handler.php
xml_handlers/configure_handler.php
xml_handlers/coverage_handler.php
xml_handlers/coverage_junit_handler.php
xml_handlers/coverage_log_handler.php
xml_handlers/dynamic_analysis_handler.php
xml_handlers/note_handler.php
xml_handlers/testing_handler.php
xml_handlers/testing_junit_handler.php
xml_handlers/testing_nunit_handler.php
xml_handlers/update_handler.php
xml_handlers/upload_handler.php

We now get the same results no matter what order the XML files are parsed in.  This is another big step towards parallel submission processing.

Sequence independence

---

public/api/v1/build.php

Fix SQL injection vulnerability by escaping this user-specified parameter.

Escape user-specified buildid

---

public/api/v1/index.php
public/api/v1/queryTests.php
public/api/v1/viewTest.php

We can't use this flag yet because we still support PHP 5.3

Don't use ENT_HTML5 flag

---

composer.json
composer.lock
include/createRSS.php

I had to re-factor to simplify the write to file anyway, so it seemed sensible to clean up the construction of the XML too.

Tidy RSS feed creation

---

public/js/controllers/index.js
public/js/controllers/queryTests.js
public/js/controllers/testSummary.js
public/js/controllers/viewSubProjects.js
public/js/controllers/viewTest.js
public/views/index.html
tests/js/e2e_tests/multiSort.js
tests/js/e2e_tests/sort_index.js

Write a cookie whenever the user changes how our tables are sorted

Cache sorting preferences

---

include/do_submit.php
include/submission_functions.php

Fix the ajax/ajax 404 in the async case.

No more ajax/ajax 404s

---

tests/test_aggregatecoverage.php

@zackgalbreath @BetsyMcPhail PTAL.

Add missing license header

---

models/build.php
models/coveragefilelog.php
tests/CMakeLists.txt
tests/data/AggregateSubProjectCoverage/debug_case/experimental/Coverage.xml
tests/data/AggregateSubProjectCoverage/debug_case/experimental/CoverageLog-0.xml
tests/data/AggregateSubProjectCoverage/debug_case/production/Coverage.xml
tests/data/AggregateSubProjectCoverage/debug_case/production/CoverageLog-0.xml
tests/data/AggregateSubProjectCoverage/debug_case/thirdparty/Coverage.xml
tests/data/AggregateSubProjectCoverage/debug_case/thirdparty/CoverageLog-0.xml
tests/data/AggregateSubProjectCoverage/release_case/experimental/Coverage.xml
tests/data/AggregateSubProjectCoverage/release_case/experimental/CoverageLog-0.xml
tests/data/AggregateSubProjectCoverage/release_case/production/Coverage.xml
tests/data/AggregateSubProjectCoverage/release_case/production/CoverageLog-0.xml
tests/data/AggregateSubProjectCoverage/release_case/thirdparty/Coverage.xml
tests/data/AggregateSubProjectCoverage/release_case/thirdparty/CoverageLog-0.xml
tests/test_aggregatesubprojectcoverage.php

Generate aggregate coverage information for SubProject builds too.

Aggregate coverage for SubProject builds

---

circle.yml

Improvements to our CircleCI integration

---

include/cdashmail.php

Fix multiple recipient emails

---

tests/test_buildgetdate.php

Hopefully it is now immune to switches between Standard & Daylight Saving Time.

Fix buildgetdate test

---

include/common.php
public/api/v1/compareCoverage.php
public/api/v1/index.php
public/api/v1/manageBuildGroup.php
public/api/v1/manageSubProject.php
public/api/v1/viewProjects.php
public/api/v1/viewSubProjects.php
public/js/controllers/manageBuildGroup.js
public/views/manageBuildGroup.html
public/views/partials/build.html
public/views/partials/header.html
public/views/partials/parentbuild.html
public/views/viewProjects.html

Make better use of ``get_dashboard_JSON()``

Remove copied & pasted code

---

composer.json
composer.lock
include/login_functions.php
public/api/v1/getCsrfToken.php
public/googleauth_callback.php
public/js/cdashOauth2.js
public/login.php
public/login.xsl

@zackgalbreath and I spoke about this a little, but for others - this is basically just an implementation of "Remember Me" for Google OAuth logins (hence the dependency on #264). As such, the UI should probably indicate that.
This is running on the dev instance right now, with a minor tweak due to an issue with the csrfToken I'm going to try to clarify to @zackgalbreath tomorrow.

Google OAuth remember me

---

public/js/controllers/queryTests.js
public/views/partials/header.html
public/views/queryTests.html
tests/js/e2e_tests/filterLabels.js
tests/js/e2e_tests/multiSort.js

Added pagination (like index and viewTests) instead.

Remove the hardcoded limit=200 parameter on queryTests

---

include/filterdataFunctions.php
models/project.php
public/api/v1/index.php
public/createProject.php
public/createProject.xsl
public/js/controllers/index.js
public/upgrade.php
sql/mysql/cdash.sql
sql/pgsql/cdash.sql
tests/test_actualtrilinossubmission.php
tests/test_filtertestlabels.php

* Better performance when filtering tests by label on index.php.
* Make label filter sharing a per-project option.

improve filtering by labels

---

xml_handlers/GcovTar_handler.php

Make sure start time, end time, and submit time time are set
when we create a new build as part of this feature.
Also make sure the file path is set correctly relative to the
SubProject's source directory.

Improve support for coverage across SubProjects

---

public/api/v1/expectedbuild.php

Don't require an admin account to see how long a build has been AWOL.

Allow non-administrative read access to expectedbuild.php

---

public/js/controllers/index.js

This commit fixes a bug where the user interface would sometimes not update after a build is manually removed.

Fix UI update on remove build

---

public/js/controllers/index.js

Previously we recorded one sorting cookie and applied this to all
buildgroups.  Now we store a separate cookie for each buildgroup
so users can specify different sorting criteria for each one.

Remember sorting on a per-buildgroup basis

---

public/api/v1/viewNotes.php
public/api/v1/viewProjects.php
public/js/cdash_angular.js
public/js/controllers/compareCoverage.js
public/js/controllers/index.js
public/js/controllers/manageBuildGroup.js
public/js/controllers/manageOverview.js
public/js/controllers/manageSubProject.js
public/js/controllers/overview.js
public/js/controllers/queryTests.js
public/js/controllers/testDetails.js
public/js/controllers/testSummary.js
public/js/controllers/viewBuildError.js
public/js/controllers/viewNotes.js
public/js/controllers/viewProjects.js
public/js/controllers/viewSubProjects.js
public/js/controllers/viewTest.js
public/views/partials/footer.html

Time how long AngularJS takes to render the page and add this value to the number reported in the footer.

Honest generation time

---

public/views/index.html

Don't use one-time binding with dynamic sorting.

Restore sorting for coverage table

---

models/buildtest.php
public/api/v1/viewTest.php
public/views/viewTest.html

Looking up test history & summary is the slowest part of this page.  Load this data via AJAX no matter how many tests are present.

Speedup viewTest.php

---

gulpfile.js
public/api/v1/index.php
public/js/controllers/index.js
public/js/controllers/overview.js
public/js/controllers/viewNotes.js
public/js/linechart.js
public/js/services/anchors.js
public/views/index.html
public/views/overview.html

Also clean up how anchor tags work in general on our AngularJS pages.

Add anchor tags to overview.php

---

include/common.php
include/upgrade_functions.php
models/dynamicanalysissummary.php
public/api/v1/index.php
public/api/v1/overview.php
public/upgrade.php
public/views/index.html
sql/mysql/cdash-upgrade-2.0-2.4.sql
sql/mysql/cdash.sql
sql/pgsql/cdash-upgrade-2.0-2.4.sql
sql/pgsql/cdash.sql
tests/CMakeLists.txt
tests/data/SubProjectDynamicAnalysis/DynamicAnalysis_1.xml
tests/data/SubProjectDynamicAnalysis/DynamicAnalysis_2.xml
tests/data/SubProjectDynamicAnalysis/DynamicAnalysis_3.xml
tests/test_dynamicanalysissummary.php
xml_handlers/dynamic_analysis_handler.php

A new table to keep track of how many dynamic analysis defects were found by a build.  Querying this summary table is faster than doing a sum over ``dynamicanalysisdefects::value``.

Dynamic analysis summary

---

include/filterdataFunctions.php
public/api/v1/filterdata.php
public/js/controllers/filters.js
tests/test_indexfilters.php

This makes it possible for users to search for a build that built a specific version of the code.

new index.php filter: Revision

---

public/api/v1/overview.php
public/css/common.css
public/js/controllers/overview.js
public/views/overview.html

The columns are now the build groups and the rows are now the subproject groups (if any).  This makes for a more compact display of information.

Transpose the coverage table on overview.php

---

public/js/controllers/filters.js
public/views/index.html
public/views/partials/filterdataTemplate.html

* Link to filter documentation for each specific page.
* Make the 'Help' link on index.php actually go somewhere.

Fixes for our documentation links

---

app.sample.yaml
include/login_functions.php

PTAL @cpatrick @danlamanna @zackgalbreath.

Miscellaneous App Engine fixes

---

models/project.php
models/subproject.php
public/js/controllers/viewSubProjects.js
tests/CMakeLists.txt
tests/test_viewsubprojects.php

Fix a few issues discovered while investigating #387.

Fix a couple bugs on viewSubProjects.php

---

public/upgrade.php
sql/mysql/cdash.sql
sql/pgsql/cdash.sql

Since we now have a filter that examines this field we should make it fast to search.

Add index on buildupdate::revision

---

include/common.php
public/ajax/buildinfogroup.php
public/ajax/expectedbuildgroup.php
public/ajax/finduserproject.php
public/ajax/findusers.php
public/ajax/getfeed.php
public/ajax/showbuildhistory.php
public/ajax/showbuildtimegraph.php
public/ajax/showbuildupdategraph.php
public/ajax/showcoveragegraph.php
public/ajax/showprojectupdategraph.php
public/ajax/showtestfailuregraph.php
public/groupsDescription.php

This change makes it so we link to index.php rather than
viewSubProjects.php for a project that has had all of its
subprojects deleted.

Only count active subprojects in get_projects

---

CTestCustom.cmake.in
public/scheduleSummary.php

* Clean up a few stray failing tests on our nightly builds.
* Exclude third party code from our coverage report.

Miscellaneous minor fixes

---

public/api/v1/index.php
public/api/v1/viewSubProjects.php
public/views/compareCoverage.html
public/views/index.html

Instead simply treat this as another type of error

Remove special handling of "date is in the future"

---

include/common.php

Inf and NaN cannot be JSON encoded

Remove infinity and NaN values before JSON encoding

---

include/repository.php

This should further prevent us from being rate limited.

Cache GitHub API calls with memcached

---

public/api/v1/viewBuildError.php
public/js/controllers/viewBuildError.js
public/views/viewBuildError.html
tests/js/e2e_tests/viewBuildError.js
tests/test_builddetails.php

@zackgalbreath This also fixes a minor issue with pluralization of a heading which required some changes in the e2e test looking for specific html tags.

Add pagination to viewBuildError

---

public/api/v1/viewTest.php
public/views/viewTest.html
tests/CMakeLists.txt
tests/test_csvexport.php

Apparently this functionality stopped working at some point.  Fix it and add a test to make sure that it keeps working.

Fix exporting tests to CSV

---

composer.json
composer.lock
config/config.php
include/cdashmail.php

Add support to email via SendGrid API

---

models/build.php

Search for the parent first, then find the corresponding child.  This results in better performance when we have many builds that share the same name.

Break up previous build query for subprojects

---

models/image.php
models/test.php
public/displayImage.php
tests/CMakeLists.txt
tests/data/ImageComparisonTest.xml
tests/test_imagecomparison.php

Users on open.cdash.org reported that some images were not displaying correctly.  This PR addresses the underlying issues.

Don't escape images

---

composer.json
composer.lock
public/googleauth_callback.php

This resolves some issues being raised on GAE.
@jamiesnape You added the lines around `Google_Config` from #383 which aren't very clear to me now. Regardless, the `Google_Config` class has been removed in the 1 -> 2 upgrade - will this break anything you're utilizing?

Upgrade Google API client

---

public/api/v1/viewTest.php
public/js/controllers/viewTest.js
public/views/viewTest.html

This page typically loads quickly, but it could get hung up by an AJAX call on the previous page (viewTest.php).

Speed up rendering of testDetails.php

---

public/ajax/showtestfailuregraph.php
public/ajax/showtestmeasurementdatagraph.php
public/ajax/showtestpassinggraph.php
public/ajax/showtesttimegraph.php
tests/CMakeLists.txt
tests/test_testgraphpermissions.php

These graphs would show "You are not authorized to access this page" even for properly authenticated users.

Fix test graphs for private projects

---

include/ctestparser.php

This has broken some things, but I'm putting the PR in case @zackgalbreath has any ideas.
The main issue I'm encountering is that as it stands parsing can fail for a tarball for example, but the submission will still be considered successful.

Make submissions return false when parsing fails

---

include/do_submit.php

Only specify Content-Type and Content-Length for POST requests.

Get parallel submits working for nginx

---

public/upgrade.php
sql/mysql/cdash.sql
sql/pgsql/cdash.sql

This improves the performance of remove_build().

Add index to label2test::buildid

---

public/monitor.php

This can take a very long time to calculate, depending on the content
of your database.

Remove echo_project_data_sizes from monitor.php

---

include/common.php

Check if an uploadfile is a URL before attempting to unlink it.

Do not attempt to delete uploaded URLs

---

include/index_functions.php
public/api/v1/index.php
public/views/index.html
tests/trilinos_submission_test.php

For Version Control Systems that have a concept of revision, show this value in the Update column rather than the number of files that changed since the previous build.

Show revision instead of number of files updated

---

include/sendemail.php
models/buildupdate.php

This change transfers the responsibility of the database query to the model.

xfer responsibility of db call to model - update summary

---

include/sendemail.php
models/build.php
models/builderror.php
models/buildfailure.php
models/label.php
models/subproject.php
public/api/v1/viewBuildError.php
tests/data/SubProjectExample/cdash_1.log
tests/test_buildmodel.php

This change transfers responsibility of db query to the model.

xfer responsibility of db query to model - build errors and failures summary

---

tests/singletest.php
tests/test_projectwebpage.php

These changes get the whole test suite passing for MySQL & Postgres using PHP7

Get tests passing for PHP7

---

include/upgrade_functions.php
public/upgrade.php

Speed up the upgrade path initially introduced in #506.  This makes the relevant upgrade functions must quicker to execute, particularly for instances with lots of data.
I tested this locally with ~900,000 configure rows.
The initial ALTER TABLE still took a while (5-10 mins)
The rest of the migration process completed in 3.5 minutes.

Improve performance of configure upgrade path

---

models/site.php
models/userproject.php
public/user.php

Use models and PDO whenever possible.  This is in preparation of converting this page from XSL to AngularJS.

Cleanup user.php

---

public/ajax/showtestmeasurementdatagraph.php

Allow spaces in measurement names

---

models/build.php
models/buildinformation.php
public/viewConfigure.php
public/viewConfigure.xsl
tests/CMakeLists.txt
tests/data/MultipleSubprojects/Build.xml
tests/data/MultipleSubprojects/Configure.xml
tests/data/MultipleSubprojects/Project.xml
tests/data/MultipleSubprojects/Test.xml
tests/test_multiplesubprojects.php
xml_handlers/build_handler.php
xml_handlers/configure_handler.php
xml_handlers/testing_handler.php

Support mapping one or more labels to a subproject.
Build.xml and Test.xml files can contain results from multiple subprojects. All subprojects in the build will share a Configure.xml file.
Replaces #376.

Allow multiple subprojects per upload file

---

public/api/v1/testOverview.php
public/js/controllers/testOverview.js
public/views/testOverview.html
tests/test_testoverview.php

* Show max execution time per test
* Allow user to include passed tests in results
* Allow user to specify sort order via URI

Upgrade testOverview.php to allow users to find long running tests

---

config/config.php
gulpfile.js
include/common.php
include/dailyupdates.php
include/do_submit.php
models/authtoken.php
models/project.php
models/userproject.php
npm-shrinkwrap.json
package.json
public/api/v1/authtoken.php
public/api/v1/createProject.php
public/api/v1/project.php
public/api/v1/user.php
public/api/v1/viewProjects.php
public/css/common.css
public/js/cdash_angular.js
public/js/controllers/createProject.js
public/js/controllers/user.js
public/submit.php
public/upgrade.php
public/views/createProject.html
public/views/user.html
sql/mysql/cdash-upgrade-2.0-2.6.sql
sql/mysql/cdash.sql
sql/pgsql/cdash-upgrade-2.0-2.6.sql
sql/pgsql/cdash.sql
tests/CMakeLists.txt
tests/kwtest/kw_web_tester.php
tests/test_authtoken.php

Allow admins to require authentication tokens for submissions to their project.

Add support for authenticated submissions

---

public/footer.xsl
public/views/partials/footer.html

Change this link to point to our GitHub issues page.

Update "Report Problems" link in footer

---

include/common.php
include/login_functions.php
public/user.php

* Fix bug that prevented login when `$CDASH_LOCKOUT_ATTEMPTS` > 0.
* Restore display of error messages upon unsuccessful login.

Fix bugs with new login procedure

---

include/filterdataFunctions.php
public/api/v1/filterdata.php
tests/test_testoverview.php

The new options are SubProject and Test Name.

Add more filter options to testOverview

---

public/js/controllers/index.js
public/js/controllers/manageBuildGroup.js
public/js/services/modal.js
public/views/index.html
public/views/manageBuildGroup.html
public/views/partials/build.html
tests/js/e2e_tests/manageBuildGroup.js
tests/js/e2e_tests/remove_build.js

- This removes system modals (e.g. window.confirm) and replaces it with application modals.
bryon.bean@kitware.com

refactor -- refactors app to use application modals

---

README.md

Settle on the wiki as a source of truth (for now anyway).

De-duplicate installation instructions

---

include/common.php
include/login_functions.php
models/project.php
public/manageProjectRoles.php
public/recoverPassword.php
public/register.php

Encapsulate random password generation

---

public/views/index.html
public/views/manageBuildGroup.html
public/views/manageMeasurements.html

Common usage is Cancel on the left, Apply on the right

Reverse order of modal buttons

---

models/build.php
tests/data/SubProjectNextPrevious/Build_2.xml
tests/data/SubProjectNextPrevious/Configure_2.xml
tests/data/SubProjectNextPrevious/Notes_2.xml
tests/data/SubProjectNextPrevious/Test_2.xml
tests/test_subprojectnextprevious.php

This PR fixes a bug in how we detect what changed between two consecutive SubProject builds.

Fix subscripts for SubProject builds

---

public/ajax/getviewcoverage.php
public/manageClient.php
tests/test_excludesubprojects.php

PTAL @zackgalbreath. (I found this while testing something else)

Fixed typo in test

---

public/ajax/getviewcoverage.php
tests/CMakeLists.txt
tests/data/CoverageDirectories/Coverage.xml
tests/data/CoverageDirectories/CoverageLog-0.xml
tests/test_coveragedirectories.php

Fix how getviewcoverage.php searches for files in a directory

---

tests/js/e2e_tests/conf.js.in
tests/js/e2e_tests/viewSubProjects.js

- tests should now pass using chromedriver > 2.33

Fixes tests for new window behavior using chromedriver > 2.33

---

public/editUser.php
public/editUser.xsl
tests/test_edituser.php
tests/test_passwordrotation.php

Require old password to set new password

---

public/views/viewSubProjects.html

All the other views already have this set

Add charset to viewSubProjects.html

---

include/common.php
public/api/v1/buildProperties.php
public/api/v1/computeClassifier.php
public/api/v1/timeline.php
public/buildProperties.php
public/css/common.css
public/js/controllers/buildProperties.js
public/js/directives/autocomplete.js
public/js/services/comparators.js
public/js/services/modal.js
public/views/buildProperties.html
sql/mysql/cdash-upgrade-2.0-2.6.sql
sql/mysql/cdash.sql
sql/pgsql/cdash-upgrade-2.0-2.6.sql
sql/pgsql/cdash.sql
tests/CMakeLists.txt
tests/data/BuildProperties/clean.json
tests/data/BuildProperties/compile_error.json
tests/data/BuildProperties/fixed.json
tests/data/BuildProperties/test_failure.json
tests/data/BuildProperties/warning.json
tests/test_buildproperties.php
xml_handlers/BuildPropertiesJSON_handler.php

Allow users to upload arbitrary key/value pairs associated with their builds
Provide analytics to correlate such properties with build defects

Add support for arbitrary build properties

---

models/build.php
models/buildtest.php
public/api/v1/testDetails.php
public/css/cdash.css
public/css/colorblind.css
public/css/common.css
public/views/testDetails.html
tests/CMakeLists.txt
tests/data/TimeStatus/Test_1.xml
tests/data/TimeStatus/Test_2.xml
tests/data/TimeStatus/Test_3.xml
tests/data/TimeStatus/Test_4.xml
tests/data/TimeStatus/Test_5.xml
tests/test_timestatus.php

Also add a test for this functionality and misc. cleanup

Show threshold for tests failing the time status check

---

tests/test_seconds_from_interval.php

Fix -- Fixes Failure of Test When Testing Year Was Leap Year

---

public/views/testSummary.html

Similar issue / solution to #316.

Restore sorting for Test Summary table

---

public/api/v1/testSummary.php

Similar to https://github.com/Kitware/CDash/commit/96bfa910dc35c040cf4ba15640d2e8d9cb8e4c60

Fix sorting by time on Time Summary

---

include/CDash/Database.php
include/pdo.php
tests/case/CDash/DatabaseTest.php

- Moves pdo_execute to Database
- Deprecates pdo_execute

Refactor -- Deprecate pdo_execute move it to Database

---

public/api/v1/user.php

This fixes the following error:
Fatal error:  Class 'BuildUpdate' not found

Use BuildUpdate class from user API

---

app/Model/Test.php
tests/case/CDash/TestUseCaseTest.php
xml_handlers/testing_handler.php

Fix a bug where the full command line was not being properly recorded for some tests.
#690

Fix test command line

---

xml_handlers/BazelJSON_handler.php
xml_handlers/BuildPropertiesJSON_handler.php
xml_handlers/CDashSubmissionHandlerInterface.php
xml_handlers/GcovTar_handler.php
xml_handlers/JSCoverTar_handler.php
xml_handlers/JavaJSONTar_handler.php
xml_handlers/NonSaxHandler.php
xml_handlers/SubProjectDirectories_handler.php
xml_handlers/abstract_handler.php
xml_handlers/build_handler.php
xml_handlers/configure_handler.php
xml_handlers/dynamic_analysis_handler.php
xml_handlers/testing_handler.php
xml_handlers/update_handler.php

This returns an array of all the Builds that were created or updated by the parser.

Define a getBuilds() method for all xml_handlers

---

app/Model/Build.php
include/ctestparser.php
public/submit.php

Fix a couple minor bugs not directly related to other tasks in progress.

Miscellaneous cleanup

---

app/Model/Build.php
include/do_submit.php

Split a couple more minor bug fixes into a separate PR to keep our topic branches more concise.

A couple more miscellaneous fixes

---

app/Model/Build.php
app/Model/BuildConfigure.php
app/Model/Site.php

When `$CDASH_BERNARD_SUBMISSION` is enabled we configure PDO to throw an exception whenever an SQL error occurs.  For this reason, we now need to catch expected exceptions for queries where unique key errors may occur during race conditions.

Catch exceptions expected due to unique keys

---

public/upgrade.php

Supplemental SQL files were accidentally not being read

Bug fix for upgrade scripts

---

public/api/v1/index.php
tests/test_email.php

We show a yellow dot in the update field if the currently logged in user contributed changes to this build.

Restore user updates (yellow dot) on index.php

---

docker-compose.yml
docker.md
php.ini
scripts/bash/misc.bash

Improve default Docker settings and documentation (follow up)

---

app/Model/BuildErrorFilter.php

Fixes bug introduced when implementing #753

Fix typo in BuildErrorFilter

---

tests/test_compressedtest.php

fix: fixes viewvcs viewer being used on git revisions

---

include/common.php
public/css/common.css
public/views/partials/header.html
xml_handlers/update_handler.php

Fixes a few defects we noticed after the most recent update of open.cdash.org

Post-deploy fixes

---

tests/manageCoverageTest.php

This test has been flaky on CircleCI lately.
I tracked it down to the build not being successfully inserted into the
database before the validation script checks for it.
Revamp this validation script to add a max 10 second wait for the build to
appear before failing.

Make 'simple' test more robust

---

app/Model/Repository.php

Was already added in PR #673 but I guess it was missed during the merge of some code restructuring that was going on in parallel.

Add Phabricator Git VCS viewer again

---

CMakeLists.txt
tests/CMakeLists.txt

This was replaced by unit tests for GitHub statuses and checks

Remove old GitHub PR test

---

app/Model/BuildGroup.php
app/Model/BuildGroupRule.php
public/api/v1/buildgroup.php
public/api/v1/manageBuildGroup.php
public/js/controllers/manageBuildGroup.js
tests/CMakeLists.txt
tests/test_putdynamicbuilds.php

Create rules for the submitted list of dynamic builds.
Soft-delete any old rules that were not included on this new list.

new API endpoint to PUT a list of dynamic builds

---

app/cdash/public/manageProjectRoles.php

@zackgalbreath  if you have time to review and merge.

STYLE: Fixing messages for old CVS/SVN

---

app/cdash/public/js/controllers/head.js

Teach the calendar to insert the new date before any filter query parameters.

Fix buggy interact between Calendar and next/prev links

---

app/cdash/include/do_submit.php
app/cdash/public/views/index.html
app/cdash/xml_handlers/testing_junit_handler.php

Use consistent terminology to be less confusing

Prefer the term 'group' to 'track'

---

app/cdash/include/Messaging/Notification/Email/Mail.php

More gracefully handle invalid email addresses

---

app/cdash/public/views/partials/buildgroup.html

Fixes #912 
Rebased copy of  #916

Use encoded project name for [view timeline] link

---

app/cdash/tests/data/TruncateOutput/Build_both.xml
app/cdash/tests/data/TruncateOutput/Build_stderr.xml
app/cdash/tests/data/TruncateOutput/Build_stdout.xml
app/cdash/tests/data/TruncateOutput/Build_suppressed.xml
app/cdash/tests/test_truncateoutput.php
app/cdash/xml_handlers/build_handler.php

* Consider stdout and stderr separately
* Remove suppressed warnings before truncating other output

Improve behavior of CDASH_LARGE_TEXT_LIMIT

---

docker/cdash.docker
webpack.mix.js

also make laravel-mix less spammy for local development

Upgrade docker image to use latest node LTS version

---

CMakeLists.txt
app/Http/Kernel.php
app/Http/Middleware/CheckDatabaseConnection.php
app/cdash/config/config.php
app/cdash/include/pdo.php
app/cdash/public/api/v1/index.php
app/cdash/public/install.php
app/cdash/tests/case/CDash/ConfigTest.php
app/cdash/tests/test_autoremovebuilds_on_submit.php
app/cdash/tests/test_parallelsubmissions.php
app/cdash/tests/trilinos_submission_test.php

Redirect to install.php (as appropriate) from more pages than just index.php.

Add middleware to check database connection

---

.env.example
app/Console/Commands/MigrateConfig.php
app/cdash/app/Model/Project.php
app/cdash/config/config.php
app/cdash/include/autoremove.php
app/cdash/include/do_submit.php
app/cdash/public/api/v1/index.php
app/cdash/public/submit.php
app/cdash/tests/data/BuildModel/configure2.xml
app/cdash/tests/test_limitedbuilds.php
config/cdash.php
tests/Feature/MigrateConfigCommandTest.php

Automatically delete the oldest builds for a project rather than blocking new submissions.

Improve limited builds functionality

---

docs/install.md

* Distinguish between initial install vs. upgrade steps
* Specify what version of npm we expect

More documentation updates

---

app/cdash/public/views/index.html
app/cdash/public/views/partials/build.html
resources/js/components/EditProject.vue
resources/js/components/TestDetails.vue

Some browsers mark these as unsafe

Remove use of href="javascript;" links

---

app/cdash/public/api/v1/viewDynamicAnalysis.php

This makes it much less likely that we will run out of memory while
generating large lists of dynamic analysis defects.

Chunk SQL results on viewDynamicAnalysis.php

---

app/cdash/public/api/v1/testGraph.php
app/cdash/public/api/v1/testSummary.php
app/cdash/tests/test_managemeasurements.php
resources/js/components/TestDetails.vue
tests/Spec/test-details.spec.js

Also improve our automated tests to make sure these bugs stay fixed.

Fix various minor defects discovered during manual testing

---

.php_cs.dist

Add bootstrap/cache to the list of style-excluded dirs

---

docs/install.md

Run `npm run dev` after the configuration environment has been set.

Clarify install docs

---

app/Console/Commands/MigrateConfig.php
package-lock.json
package.json

https://github.com/advisories/GHSA-92xj-mqp7-vmcj

Update laravel-mix to resolve security alert

---

app/cdash/app/Model/AuthToken.php

Fix "never expires" date for auth tokens

---

app/cdash/include/Messaging/Notification/Email/Mail.php

Define $status even when an exception gets thrown

---

app/cdash/app/Model/DynamicAnalysis.php
app/cdash/tests/CMakeLists.txt
app/cdash/tests/data/DynamicAnalysisLogs/Build.xml
app/cdash/tests/data/DynamicAnalysisLogs/Configure.xml
app/cdash/tests/data/DynamicAnalysisLogs/DynamicAnalysis.xml
app/cdash/tests/data/DynamicAnalysisLogs/Test.xml
app/cdash/tests/test_dynamicanalysislogs.php

Fix a bug where only the last kilobyte was being stored in the database.
Fixes #1097

Store full dynamic analysis output logs

---

app/cdash/public/api/v1/index.php
app/cdash/tests/trilinos_submission_test.php

Fix links to SubProjects in the 'SubProject Dependencies' table

---

package-lock.json
package.json

Also run `npm audit fix --force` and allow laravel-mix to update some of its dependencies.

Update laravel-mix to 6.0.23

---

app/cdash/sql/mysql/cdash.sql
app/cdash/sql/pgsql/cdash.sql
app/cdash/tests/CMakeLists.txt
app/cdash/tests/data/DynamicAnalysisDefectLongType/DynamicAnalysis.xml
app/cdash/tests/test_dynamicanalysisdefectlongtype.php
database/migrations/2021_07_06_084122_increase_dynamic_analysis_defect_type_size.php

Bump the size of this column from 50 to 255 characters

Increase size of dynamicanalysisdefect::type

---

app/cdash/app/Lib/Repository/GitHub.php

Update CDash for changes to the GitHub API library that we use.
https://github.com/KnpLabs/php-github-api/blob/master/UPGRADE-3.0.md#authentication-methods

Fix GitHub App functionality

---

app/cdash/include/filterdataFunctions.php
app/cdash/tests/CMakeLists.txt
app/cdash/tests/data/QueryTestsFilterLabels/Test_1.xml
app/cdash/tests/data/QueryTestsFilterLabels/Test_2.xml
app/cdash/tests/test_querytestsfilterlabels.php

This filter would sometimes return builds that do not contain the specified label.
Closes #1191

Bug fix for Labels filter on queryTests.php

---

app/cdash/include/ctestparser.php
app/cdash/tests/CMakeLists.txt
app/cdash/tests/data/LotsOfSubProjects/After.xml
app/cdash/tests/data/LotsOfSubProjects/Before.xml
app/cdash/tests/test_lotsofsubprojects.php

Fix parsing of XML files with lots of subprojects

---

app/cdash/app/Model/CoverageFileLog.php

Handle string coverage count in AddLine

---

app/cdash/app/Controller/Api/TestDetails.php
app/cdash/app/Controller/Api/ViewNotes.php

* test details page
* build notes page

Remove a couple more extra '/'s from 'Up' links

---

docker/cdash.docker

Assign ownership of apache2 config files to the www-data user

Modify directory permissions for Docker image

---

.dockerignore
docker/common.docker

Add copy commands for the `lang` subdirectory and for the two phpstan files.

Copy newest additions in common image

---

app/cdash/include/api_common.php
app/cdash/include/common.php
app/cdash/public/api/v1/addUserNote.php
phpstan-baseline.neon

This PR follows https://github.com/Kitware/CDash/pull/1341, and simplifies a handful of small functions which are currently only being used in a limited number of locations.

Simplify common code

---

app/cdash/public/css/common.css

A lot of the CSS in `common.css` no longer has any references and is now stale.  This PR cleans up the dead code.

Delete stale CSS

---

app/cdash/public/api/v1/buildgroup.php

Fixes a permissions issue where unauthorized users could perform build group administration actions.

Verify buildgroup administration privileges

---

app/cdash/include/Messaging/Notification/Email/Mail.php
app/cdash/include/Messaging/Notification/Mailer.php
phpstan-baseline.neon

Fixes https://github.com/Kitware/CDash/issues/1238.
I also cleaned up the rest of `Mail.php` and `Mailer.php` along the way.

Fix typo in email settings

---

app/cdash/include/api_common.php
phpstan-baseline.neon

Fixes a flaw where project access controls could be circumvented to unwittingly leak project data.

Fix project access controls

---

app/Http/Controllers/AdminController.php

Fixes #1509 by adding a missing import.

Fix missing import in `AdminController`

---

app/Console/Commands/SetVersion.php
app/Http/Controllers/AdminController.php
app/cdash/include/common.php
docker/bash/cdash.bash
phpstan-baseline.neon

Fixes #1516 by creating a new Artisan command which sets the database schema version and is run during the installation process.

Set database schema version on install

---

app/Http/Controllers/TestController.php

The test details page is currently missing a title.
Before:
After:

Add title to test details page

---

app/cdash/public/views/partials/logout.html

This AngularJS partial seems to be unused.  There is no logout page, and Laravel handles the entire process.

Delete unused logout AngularJS partial

---

app/Http/Controllers/DynamicAnalysisController.php
app/cdash/app/Controller/Api/TestOverview.php

This PR fixes two page titles which were missed in https://github.com/Kitware/CDash/pull/1555.

Fix inconsistent titles (again)

---

app/cdash/tests/test_upgrade.php
database/migrations/2023_08_14_200318_user_foreign_keys.php

This PR makes progress towards #1442 by adding foreign key constraints to every column which references user IDs.

Add foreign key constraints for all userids

---

app/Http/Controllers/BuildController.php
app/Models/Label.php
app/Services/TestCreator.php
app/cdash/app/Model/Coverage.php
app/cdash/app/Model/Label.php
phpstan-baseline.neon

This PR continues our ongoing effort to use Eloquent for all of our models.

Convert backend of `Label` model to Eloquent

---

app/Http/Controllers/BuildController.php
resources/js/components/BuildSummary.vue
tests/Spec/build-summary.spec.js

Closes https://github.com/Kitware/CDash/issues/794.

Add labels to build summary page

---

app/Http/Controllers/TestController.php

`testSummary.php` currently executes a separate query to get the status for each row on the page.  Querying the database iteratively like this results in poor performance for large projects.
The offending query has been converted to a single larger query.

Optimize repeated `testSummary.php` query

---

app/Exceptions/Handler.php

We currently simulate the behavior of the default Laravel error handler.  This approach doesn't handle some types of exceptions properly.  This PR introduces an updated error handler which modifies the result of the error handler rather than attempting to simulate it.
The contents of this PR were originally part of #1742.

Refactor error handler

---

app/Models/Project.php

A variety of relationships between the `User` model and the `Project` model have been defined.  The changes in this PR were originally from #1742, and have been split into a separate PR to get the changes merged faster.

Create new relationships between User and Project models

---

app/cdash/app/Controller/Api/QueryTests.php
database/migrations/2023_11_09_182206_test_labels_index.php

Improve test label query with index

---

app/cdash/app/Controller/Api/Index.php

Cherry-picks https://github.com/Kitware/CDash/pull/1797 to the CDash 3.2 release branch.

Backport date filter bugfix

---

app/Models/Build.php
app/Models/BuildTest.php
app/Models/Project.php
app/Models/Test.php
app/Models/TestLabel.php
app/Models/TestMeasurement.php
app/Models/TestOutput.php

This PR contains some preliminary work I did a few months ago to set up Eloquent relationships between the various test-related models.  The work to make use of these relationships is currently stalled, and I will create a future PR with those changes.  In the meantime, I have created this PR to prevent myself from duplicating work unnecessarily.  I plan to test these relationships as part of the GraphQL testing suite once #1772 is merged.

Set up test-related Eloquent relationships

---

resources/js/components/page-header/HeaderMenu.vue

Handle missing menu field in `HeaderMenu` Vue template

---

app/cdash/public/js/cdash_angular.js
package-lock.json
package.json
webpack.mix.js

`angular-clipboard` appears to be unused, so I have deleted it.

Remove unused `angular-clipboard` dependency

---

.github/release.yml

https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

Add GH template for automatic release notes

---

LICENSE

Bump license year to 2024

---

resources/js/components/UserHomepage.vue

Closes https://github.com/Kitware/CDash/issues/1712.

Add link to user profile page

---

.env.example
app/Jobs/ProcessSubmission.php
app/cdash/app/Lib/Repository/GitHub.php
app/cdash/config/config.php
app/cdash/public/api/v1/GitHub/webhook.php
app/cdash/tests/case/CDash/Api/GitHubWebhookTest.php
app/cdash/tests/case/CDash/Lib/Repository/GitHubTest.php
config/cdash.php
phpstan-baseline.neon

also fix message delays for sqs-fifo queues

Improve configuration for GitHub App support

---

app/cdash/include/autoremove.php
phpstan-baseline.neon

Also complete the transition to using Laravel's DB facade in this file.

Remove hardcoded "LIMIT 10" in autoremove.php

---

app/Jobs/ProcessSubmission.php
app/cdash/include/autoremove.php

Supersedes https://github.com/Kitware/CDash/pull/2017 (resolves conflict).

Merge patches from 3.2 into 3.3

---

app/cdash/app/Controller/Api/Timeline.php
app/cdash/tests/test_timeline.php
phpstan-baseline.neon

Fix HTTP 500 error for testOverview + filters timeline

---

app/cdash/tests/CMakeLists.txt
app/cdash/tests/data/StartTimeFromUpload/Upload.xml
app/cdash/tests/test_starttimefromupload.php
app/cdash/xml_handlers/upload_handler.php
phpstan-baseline.neon

Teach CDash to use this newly provided data from CTest:
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9292

Parse `<Time>` attribute from Upload.xml

---

database/migrations/2024_03_23_144609_siteinformation_fk.php

Closes https://github.com/Kitware/CDash/issues/2105.

Add foreign-key constraint to `siteinformation` table

---

app/cdash/public/api/v1/manageBuildGroup.php
phpstan-baseline.neon

Fix check for any site for wildcard group

---

app/cdash/app/Model/Build.php
database/migrations/2024_05_06_151132_buildinformation_nullable.php

Don't overwrite build information on upload

---

app/cdash/public/api/v1/index.php

Catch DivisionByZeroError on index.php

---

config/cdash.php
package-lock.json
package.json

Bump patch version and fix version reported in footer for installation from release tarballs.
Fixes #2280

Fix reported version when installing from release tarballs

---

app/Console/Commands/UpdateLdapProjectMembership.php
app/Console/Kernel.php
app/Http/Controllers/ProjectController.php
app/Listeners/SuccessfulLdapAuthListener.php
app/Models/Project.php
app/Models/User.php
app/Providers/EventServiceProvider.php
app/Utils/LdapUtils.php
app/cdash/app/Model/Project.php
database/migrations/2024_06_14_125557_ldap_project_membership.php
graphql/schema.graphql
phpstan-baseline.neon
resources/js/components/EditProject.vue
tests/Feature/LdapIntegration.php

Closes https://github.com/Kitware/CDash/issues/1983.  This PR implements the ability to specify project membership by LDAP group membership.

Add support for LDAP-based project access

---

app/cdash/include/ctestparser.php
app/cdash/tests/case/PHPUnitTestTest.php
app/cdash/xml_handlers/GcovTar_handler.php
phpstan-baseline.neon

A follow up PR to https://github.com/Kitware/CDash/pull/2335 to fix some of the php errors uncovered by the changes it made.

Fix "inccorect case" phpstan errors in submission handler class references

---

app/Http/Controllers/CoverageController.php
app/Http/Controllers/ManageProjectRolesController.php
app/Http/Controllers/ProjectController.php
app/Utils/AuthTokenUtil.php
app/cdash/app/Model/Project.php
app/cdash/app/Model/UserProject.php
app/cdash/include/common.php
app/cdash/public/api/v1/manageBuildGroup.php
app/cdash/tests/test_issuecreation.php
phpstan-baseline.neon

The legacy UserProject model will eventually be superseded by Eloquent relationships between the User and Project models.  This PR contains incremental progress towards the goal of getting rid of this legacy model.  I expect to finish this refactor in a separate PR once a handful of other changes are complete.  For now, most of the "easy" work is done.

Refactor legacy UserProject model

---

config/cdash.php
package-lock.json
package.json

Revert "Bump version to 3.5.0"

---

.eslintignore
resources/js/components/AllProjects.vue
resources/js/components/BuildConfigure.vue
resources/js/components/BuildNotes.vue
resources/js/components/BuildSummary.vue
resources/js/components/BuildUpdate.vue
resources/js/components/EditProject.vue
resources/js/components/ManageAuthTokens.vue
resources/js/components/ManageMeasurements.vue
resources/js/components/TestDetails.vue
resources/js/components/UserHomepage.vue
resources/js/components/ViewDynamicAnalysis.vue
resources/js/components/page-header/HeaderMenu.vue
resources/js/components/page-header/HeaderNav.vue
resources/views/project/view-all-projects.blade.php

All existing files with errors were completely ignored when `eslint` was added.  This incremental PR addresses the ignored errors in Vue files throughout the codebase.

Lint ignored Vue files

---

database/migrations/2024_10_29_154630_subproject2subproject_foreign_keys.php

This continues our ongoing effort described in https://github.com/Kitware/CDash/issues/2093 to add foreign-key constraints wherever possible for better data integrity.

Add subproject2subproject foreign-key constraints

---

app/Jobs/ProcessSubmission.php
app/cdash/app/Model/Project.php
app/cdash/app/Model/Subscriber.php
app/cdash/include/Messaging/Subscription/Subscription.php
app/cdash/include/Messaging/Topic/Topic.php
app/cdash/include/sendemail.php
app/cdash/tests/case/CDash/ConfigUseCaseTest.php
app/cdash/tests/case/CDash/Messaging/Subscription/CommitAuthorSubscriptionBuilderTest.php
app/cdash/tests/case/CDash/Messaging/Subscription/UserSubscriptionBuilderTest.php
app/cdash/tests/case/CDash/XmlHandler/BuildHandlerTest.php
app/cdash/tests/case/CDash/XmlHandler/ConfigureHandlerTest.php
app/cdash/tests/case/CDash/XmlHandler/DynamicAnalysisHandlerTest.php
app/cdash/tests/case/CDash/XmlHandler/TestingHandlerTest.php
app/cdash/tests/case/CDash/XmlHandler/UpdateHandlerTest.php
app/cdash/xml_handlers/abstract_xml_handler.php
app/cdash/xml_handlers/actionable_build_interface.php
app/cdash/xml_handlers/build_handler.php
app/cdash/xml_handlers/configure_handler.php
app/cdash/xml_handlers/coverage_handler.php
app/cdash/xml_handlers/coverage_junit_handler.php
app/cdash/xml_handlers/coverage_log_handler.php
app/cdash/xml_handlers/dynamic_analysis_handler.php
app/cdash/xml_handlers/note_handler.php
app/cdash/xml_handlers/project_handler.php
app/cdash/xml_handlers/testing_handler.php
app/cdash/xml_handlers/testing_j_unit_handler.php
app/cdash/xml_handlers/update_handler.php
app/cdash/xml_handlers/upload_handler.php
phpstan-baseline.neon

The various submission handlers were not originally developed under a strict inheritance hierarchy, and while their behavior is often similar, there are many slight differences between them.  This PR contains incremental work towards complete standardization of the submission handlers.

Clean up misc. submission handler inconsistencies

---

graphql/schema.graphql
tests/Feature/GraphQL/SiteTypeTest.php

Closes https://github.com/Kitware/CDash/issues/1985

Add top-level site field to GraphQL API

---

app/cdash/app/Model/BuildEmail.php
app/cdash/include/Messaging/Notification/Email/Mail.php
app/cdash/tests/kwtest/kw_web_tester.php
phpstan-baseline.neon

Call cdashmail() from Notification/Email/Mail.php

---

LICENSE

Update license year to 2025

---

docker/docker-entrypoint.sh

Make sure the expected storage directories exist on worker containers.

Create storage directories for worker containers

---

config/cdash.php

This PR cleans up the last remaining references to a number of unused config options.

Remove unused config options

---

app/cdash/include/common.php
phpstan-baseline.neon

A bit of spring cleaning to remove functions which have been rendered obsolete since my last pass through `common.php`.

Delete unused `common.php` functions

---

app/Http/Controllers/SubmissionController.php

When "abort"-ing out of the SubmissionController, move that file from `inbox` to the `failed` folder.

Introduce move to correct storage for failing submissions

---

app/cdash/app/Model/Repository.php
app/cdash/tests/kwtest/kw_web_tester.php
app/cdash/tests/test_builddetails.php
database/migrations/2025_04_17_133618_repository_viewer_types.php

This PR finishes the work started in https://github.com/Kitware/CDash/pull/2795.

Remove remaining legacy repository logic

---

.gitignore

This PR makes the git diff more readable inside new containers.

Update `.gitignore` list

---

app/Http/Controllers/TestController.php
app/cdash/include/dailyupdates.php

This PR cleans up a couple minor errors I noticed in the logs of open.cdash.org.
By reducing some of these more common error messages, hopefully it will be easier to notice if anything more serious goes wrong on our production systems.

Fix a couple errors I noticed in our logs

---

phpstan-baseline.neon
tests/Feature/LoginAndRegistration.php
tests/Traits/CreatesUsers.php

This PR addresses deprecation warnings in `LoginAndRegistration` in preparation for our upcoming migration to PHPUnit 12.

Refactor `LoginAndRegistration` test

---

composer.json
composer.lock

Follows https://github.com/Kitware/CDash/pull/2940, https://github.com/Kitware/CDash/pull/2939, https://github.com/Kitware/CDash/pull/2938, and https://github.com/Kitware/CDash/pull/2937.

Upgrade to PHPUnit 12

---

app/Http/Controllers/CoverageController.php
app/Http/Controllers/ProjectController.php
app/Http/Controllers/ViewProjectsController.php
app/cdash/app/Model/Project.php
app/cdash/include/common.php
app/cdash/tests/test_displayimage.php
phpstan-baseline.neon

This PR contains a collection of miscellaneous changes to the legacy project model which didn't easily fit into other PRs, but which I frequently notice as I'm navigating throughout the codebase.

Clean up legacy project model

---

app/Jobs/ProcessSubmission.php

When CDash fails to parse a submission it moves the file from `inprogress/` to `failed/`. Wrap this call in a try/catch to prevent the worker from crashing if this move operation itself fails within the error handler.

Catch filesystem exception in error handler

---

app/Http/Controllers/SubmissionController.php
phpstan-baseline.neon

This PR adds logging at the `info` level for all types of rejected submissions.

Improve submission-time logging

---

app/Utils/LdapUtils.php
tests/Feature/LdapIntegration.php

https://github.com/Kitware/CDash/pull/2985 failed to consider projects which set an invalid LDAP filter, leading all LDAP syncing to fail if any project has a bad LDAP filter.  This PR handles the error and prints a warning.

Handle invalid project LDAP filters

---

tests/Feature/GraphQL/BuildTypeTest.php
tests/Feature/GraphQL/LabelTypeTest.php

Fixes the test flake observed in https://github.com/Kitware/CDash/actions/runs/18207382087/job/51840810691.

Fix label text test conflicts
